[input]
entrypoint                = 0x80000400
elf_path                  = "../iggy/build/iggy.elf"
rom_file_path             = "../iggy/baserom.z64"
output_func_path          = "../iggypc/RecompiledFuncs"
relocatable_sections_path = "iggy_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80000400", size = 104 },
  { name = "func_80000468", size = 532 },
  { name = "func_8000067C", size = 84 },
  { name = "func_800006D0", size = 208 },
  { name = "func_800007A0", size = 424 },
  { name = "func_80000948", size = 216 },
  { name = "func_80000A20", size = 52 },
  { name = "func_80000A54", size = 60 },
  { name = "func_80000A90", size = 36 },
  { name = "func_80000AB4", size = 384 },
  { name = "func_80000C34", size = 36 },
  { name = "func_80000C58", size = 168 },
  { name = "func_80000D04", size = 1596 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
