[input]
entrypoint                = 0x80000400
elf_path                  = "../fifa98rd/build/fifa98rd.elf"
rom_file_path             = "../fifa98rd/baserom.z64"
output_func_path          = "../fifa98rdpc/RecompiledFuncs"
relocatable_sections_path = "fifa98rd_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80000400", size = 80 },
  { name = "func_80000450", size = 120 },
  { name = "func_800004C8", size = 248 },
  { name = "func_800005C0", size = 60 },
  { name = "func_800005FC", size = 68 },
  { name = "func_80000640", size = 164 },
  { name = "func_800006E4", size = 108 },
  { name = "func_80000750", size = 1472 },
  { name = "osInvalDCache", size = 176 },
  { name = "osInvalICache", size = 128 },
  { name = "func_80000E40", size = 224 },
  { name = "func_80000F20", size = 16 },
  { name = "osInitialize", size = 656 },
  { name = "osVirtualToPhysical", size = 128 },
  { name = "func_80001240", size = 16 },
  { name = "func_80001250", size = 16 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_80001270", size = 80 },
  { name = "func_800012C0", size = 80 },
  { name = "func_80001310", size = 16 },
  { name = "func_80001854", size = 232 },
  { name = "func_8000193C", size = 256 },
  { name = "func_80001A3C", size = 72 },
  { name = "func_80001A84", size = 396 },
  { name = "osWritebackDCache", size = 128 },
  { name = "func_80001CA0", size = 96 },
  { name = "func_80001D00", size = 96 },
  { name = "func_80001D60", size = 44 },
  { name = "__ull_rem", size = 60 },
  { name = "__ull_div", size = 60 },
  { name = "func_80001E04", size = 44 },
  { name = "func_80001E30", size = 60 },
  { name = "__ll_div", size = 92 },
  { name = "__ll_mul", size = 48 },
  { name = "func_80001EF8", size = 96 },
  { name = "func_80001F58", size = 156 },
  { name = "func_80001FF4", size = 44 },
  { name = "_bzero", size = 160 },
  { name = "func_800020C0", size = 192 },
  { name = "func_80002180", size = 48 },
  { name = "func_800021B0", size = 64 },
  { name = "func_800021F0", size = 1700 },
  { name = "func_80002894", size = 232 },
  { name = "func_8000297C", size = 244 },
  { name = "osSetEventMesg", size = 112 },
  { name = "osSetIntMask", size = 160 },
  { name = "osDestroyThread", size = 256 },
  { name = "func_80002C80", size = 256 },
  { name = "osEPiRawStartDma", size = 560 },
  { name = "__osDisableInt", size = 32 },
  { name = "__osRestoreInt", size = 32 },
  { name = "osCreatePiManager", size = 400 },
  { name = "func_80003180", size = 240 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "func_800032A0", size = 80 },
  { name = "func_800032F0", size = 68 },
  { name = "func_80003334", size = 44 },
  { name = "osGetThreadPri", size = 32 },
  { name = "osSetThreadPri", size = 224 },
  { name = "osCreateThread", size = 336 },
  { name = "func_800035B0", size = 1168 },
  { name = "osStartThread", size = 336 },
  { name = "osSendMesg", size = 336 },
  { name = "osRecvMesg", size = 320 },
  { name = "func_80003E20", size = 96 },
  { name = "func_80003E80", size = 80 },
  { name = "func_80003ED0", size = 80 },
  { name = "func_80003F20", size = 80 },
  { name = "func_80003F70", size = 80 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
