[input]
entrypoint                = 0x80140000
elf_path                  = "../dragonking/build/dragonking.elf"
rom_file_path             = "../dragonking/baserom.z64"
output_func_path          = "../dragonkingpc/RecompiledFuncs"
relocatable_sections_path = "dragonking_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80140000", size = 64 },
  { name = "func_80140040", size = 108 },
  { name = "func_801400AC", size = 516 },
  { name = "func_801402B0", size = 764 },
  { name = "func_801405AC", size = 152 },
  { name = "func_80140644", size = 164 },
  { name = "func_801406E8", size = 48 },
  { name = "func_80140718", size = 48 },
  { name = "func_80140748", size = 192 },
  { name = "func_80140808", size = 1220 },
  { name = "func_80140CCC", size = 680 },
  { name = "func_80140F74", size = 16 },
  { name = "func_80140F84", size = 92 },
  { name = "func_80140FE0", size = 504 },
  { name = "func_801411D8", size = 56 },
  { name = "func_80141210", size = 336 },
  { name = "func_80141360", size = 584 },
  { name = "func_801415A8", size = 176 },
  { name = "func_80141658", size = 232 },
  { name = "func_80141740", size = 236 },
  { name = "func_8014182C", size = 172 },
  { name = "func_801418D8", size = 72 },
  { name = "func_80141920", size = 148 },
  { name = "func_801419B4", size = 260 },
  { name = "func_80141AB8", size = 472 },
  { name = "func_80141C90", size = 128 },
  { name = "func_80141D10", size = 416 },
  { name = "func_80141EB0", size = 320 },
  { name = "func_80141FF0", size = 116 },
  { name = "func_80142064", size = 68 },
  { name = "func_801420A8", size = 48 },
  { name = "func_801420D8", size = 68 },
  { name = "func_8014211C", size = 1348 },
  { name = "func_80142660", size = 192 },
  { name = "func_80142720", size = 544 },
  { name = "func_80142940", size = 48 },
  { name = "func_80142970", size = 2340 },
  { name = "func_80143294", size = 100 },
  { name = "func_801432F8", size = 1412 },
  { name = "func_8014387C", size = 84 },
  { name = "func_801438D0", size = 576 },
  { name = "func_80143B10", size = 832 },
  { name = "func_80143E50", size = 240 },
  { name = "func_80143F40", size = 604 },
  { name = "func_8014419C", size = 976 },
  { name = "func_8014456C", size = 912 },
  { name = "func_801448FC", size = 560 },
  { name = "func_80144B2C", size = 776 },
  { name = "func_80144E34", size = 240 },
  { name = "func_80144F24", size = 472 },
  { name = "func_801450FC", size = 328 },
  { name = "func_80145244", size = 336 },
  { name = "func_80145394", size = 188 },
  { name = "func_80145450", size = 640 },
  { name = "func_801456D0", size = 864 },
  { name = "func_80145A30", size = 276 },
  { name = "func_80145B44", size = 532 },
  { name = "func_80145D58", size = 56 },
  { name = "func_80145D90", size = 116 },
  { name = "func_80145E04", size = 56 },
  { name = "func_80145E3C", size = 152 },
  { name = "func_80145ED4", size = 148 },
  { name = "func_80145F68", size = 1168 },
  { name = "func_801463F8", size = 768 },
  { name = "func_801466F8", size = 448 },
  { name = "func_801468B8", size = 712 },
  { name = "func_80146B80", size = 708 },
  { name = "func_80146E44", size = 2252 },
  { name = "func_80147710", size = 552 },
  { name = "func_80147938", size = 140 },
  { name = "func_801479C4", size = 1988 },
  { name = "func_80148188", size = 1376 },
  { name = "func_801486E8", size = 1784 },
  { name = "func_80148DE0", size = 648 },
  { name = "func_80149068", size = 316 },
  { name = "func_801491A4", size = 152 },
  { name = "func_8014923C", size = 408 },
  { name = "func_801493D4", size = 132 },
  { name = "func_80149458", size = 376 },
  { name = "func_801495D0", size = 3064 },
  { name = "func_8014A1C8", size = 56 },
  { name = "func_8014A200", size = 88 },
  { name = "func_8014A258", size = 84 },
  { name = "func_8014A2AC", size = 168 },
  { name = "func_8014A354", size = 4 },
  { name = "func_8014A358", size = 3400 },
  { name = "func_8014B0A0", size = 2344 },
  { name = "func_801A2118", size = 48 },
  { name = "func_801A2148", size = 192 },
  { name = "osWritebackDCache", size = 128 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "osCreateThread", size = 336 },
  { name = "func_801A2438", size = 16 },
  { name = "func_801A296C", size = 232 },
  { name = "func_801A2A54", size = 256 },
  { name = "func_801A2B54", size = 72 },
  { name = "func_801A2B9C", size = 396 },
  { name = "__osDisableInt", size = 32 },
  { name = "__osRestoreInt", size = 32 },
  { name = "osSetIntMask", size = 160 },
  { name = "osDestroyThread", size = 256 },
  { name = "osInitialize", size = 672 },
  { name = "func_801A31B8", size = 16 },
  { name = "osInvalICache", size = 128 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_801A3258", size = 16 },
  { name = "func_801A3268", size = 96 },
  { name = "osRecvMesg", size = 320 },
  { name = "osSetEventMesg", size = 112 },
  { name = "func_801A3478", size = 80 },
  { name = "osSetThreadPri", size = 224 },
  { name = "osSetTimer", size = 224 },
  { name = "osStartThread", size = 336 },
  { name = "func_801A37D8", size = 64 },
  { name = "func_801A3818", size = 140 },
  { name = "func_801A38A4", size = 376 },
  { name = "func_801A3A1C", size = 116 },
  { name = "func_801A3A90", size = 392 },
  { name = "osGetCount", size = 16 },
  { name = "func_801A3C28", size = 16 },
  { name = "osSendMesg", size = 336 },
  { name = "func_801A3D88", size = 284 },
  { name = "osSpTaskLoad", size = 352 },
  { name = "osSpTaskStartGo", size = 68 },
  { name = "osVirtualToPhysical", size = 128 },
  { name = "func_801A40C8", size = 192 },
  { name = "func_801A4188", size = 48 },
  { name = "func_801A41B8", size = 16 },
  { name = "__osSpSetPc", size = 64 },
  { name = "func_801A4208", size = 144 },
  { name = "osCreateViManager", size = 392 },
  { name = "func_801A4420", size = 472 },
  { name = "osGetThreadPri", size = 32 },
  { name = "func_801A4618", size = 336 },
  { name = "func_801A4768", size = 16 },
  { name = "osViSetEvent", size = 112 },
  { name = "osViSetMode", size = 112 },
  { name = "osViSetSpecialFeatures", size = 448 },
  { name = "osViSwapBuffer", size = 80 },
  { name = "func_801A4A68", size = 864 },
  { name = "osViBlack", size = 112 },
  { name = "func_801A4E38", size = 80 },
  { name = "func_801A4E88", size = 48 },
  { name = "func_801A4EB8", size = 80 },
  { name = "osContStartReadData", size = 196 },
  { name = "osContGetReadData", size = 168 },
  { name = "func_801A5074", size = 244 },
  { name = "func_801A5168", size = 176 },
  { name = "osInvalDCache", size = 176 },
  { name = "func_801A52C8", size = 80 },
  { name = "func_801A5318", size = 68 },
  { name = "func_801A535C", size = 44 },
  { name = "func_801A5388", size = 248 },
  { name = "func_801A5480", size = 136 },
  { name = "osContInit", size = 504 },
  { name = "func_801A5700", size = 208 },
  { name = "func_801A57D0", size = 248 },
  { name = "osGetTime", size = 144 },
  { name = "osEepromProbe", size = 112 },
  { name = "osEepromWrite", size = 432 },
  { name = "func_801A5B78", size = 268 },
  { name = "func_801A5C84", size = 548 },
  { name = "osEepromRead", size = 496 },
  { name = "func_801A6098", size = 272 },
  { name = "osEepromLongRead", size = 320 },
  { name = "osEepromLongWrite", size = 320 },
  { name = "func_801A6428", size = 96 },
  { name = "osCreatePiManager", size = 400 },
  { name = "func_801A6618", size = 224 },
  { name = "func_801A66F8", size = 224 },
  { name = "func_801A67D8", size = 1776 },
  { name = "func_801A6EBC", size = 232 },
  { name = "func_801A6FA4", size = 244 },
  { name = "func_801A7098", size = 240 },
  { name = "func_801A7188", size = 948 },
  { name = "func_801A7538", size = 96 },
  { name = "func_801A7598", size = 80 },
  { name = "func_801A75E8", size = 80 },
  { name = "func_801A7638", size = 80 },
  { name = "func_801A7688", size = 68 },
  { name = "func_801A76CC", size = 44 },
  { name = "osPiStartDma", size = 272 },
  { name = "osJamMesg", size = 336 },
  { name = "func_801A7958", size = 48 },
  { name = "func_801A7988", size = 784 },
  { name = "func_801A7C98", size = 160 },
  { name = "func_801A7D38", size = 44 },
  { name = "__ull_rem", size = 60 },
  { name = "__ull_div", size = 60 },
  { name = "func_801A7DDC", size = 44 },
  { name = "func_801A7E08", size = 60 },
  { name = "__ll_div", size = 92 },
  { name = "__ll_mul", size = 48 },
  { name = "func_801A7ED0", size = 96 },
  { name = "func_801A7F30", size = 156 },
  { name = "func_801A7FCC", size = 44 },
  { name = "func_801A7FF8", size = 44 },
  { name = "func_801A8024", size = 40 },
  { name = "func_801A804C", size = 76 },
  { name = "func_801A8098", size = 48 },
  { name = "func_801A80BC", size = 92 },
  { name = "func_801A8118", size = 1648 },
  { name = "func_801A8788", size = 1616 },
  { name = "func_801A8DD8", size = 672 },
  { name = "func_801A9078", size = 256 },
  { name = "func_801A9178", size = 144 },
  { name = "func_801A9208", size = 1392 },
  { name = "func_801A9778", size = 1360 },
  { name = "func_801A9CC8", size = 56 },
  { name = "func_801A9D00", size = 164 },
  { name = "func_801A9DA4", size = 212 },
  { name = "func_801A9E78", size = 212 },
  { name = "func_801A9F4C", size = 632 },
  { name = "func_801AA1C4", size = 60 },
  { name = "func_801AA200", size = 52 },
  { name = "func_801AA234", size = 40 },
  { name = "func_801AA25C", size = 60 },
  { name = "func_801AA298", size = 44 },
  { name = "func_801AA2C4", size = 44 },
  { name = "func_801AA2F0", size = 60 },
  { name = "func_801AA32C", size = 40 },
  { name = "func_801AA354", size = 44 },
  { name = "func_801AA380", size = 96 },
  { name = "func_801AA3E0", size = 28 },
  { name = "func_801AA3FC", size = 28 },
  { name = "func_801AA418", size = 100 },
  { name = "func_801AA47C", size = 100 },
  { name = "func_801AA4E0", size = 72 },
  { name = "func_801AA528", size = 80 },
  { name = "func_801AA578", size = 92 },
  { name = "func_801AA5D4", size = 256 },
  { name = "func_801EA718", size = 1984 },
  { name = "func_801EAF18", size = 592 },
  { name = "func_801EB718", size = 592 },
  { name = "func_801EB968", size = 1392 },
  { name = "func_801EC718", size = 592 },
  { name = "func_801ED168", size = 3312 },
]

exact_size_funcs = [

]

[patches]
stubs = [
  "func_801EA718",
  "func_801EAF18",
  "func_801EB718",
]
