[input]
entrypoint                = 0x80000400
elf_path                  = "../g1080snowboarding/build/g1080snowboarding.elf"
rom_file_path             = "../g1080snowboarding/baserom.z64"
output_func_path          = "../g1080snowboardingpc/RecompiledFuncs"
relocatable_sections_path = "g1080snowboarding_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80000400", size = 96 },
  { name = "func_80000460", size = 80 },
  { name = "func_800004B0", size = 104 },
  { name = "func_80000518", size = 80 },
  { name = "func_80000568", size = 116 },
  { name = "func_800005DC", size = 48 },
  { name = "func_8000060C", size = 84 },
  { name = "func_80000660", size = 328 },
  { name = "func_800007A8", size = 204 },
  { name = "func_80000874", size = 12 },
  { name = "func_80000880", size = 56 },
  { name = "func_800008B8", size = 212 },
  { name = "func_8000098C", size = 12 },
  { name = "func_80000998", size = 64 },
  { name = "func_800009D8", size = 176 },
  { name = "func_80000A88", size = 16 },
  { name = "func_80000A98", size = 156 },
  { name = "func_80000B34", size = 144 },
  { name = "func_80000BC4", size = 16 },
  { name = "func_80000BD4", size = 136 },
  { name = "func_80000C5C", size = 148 },
  { name = "func_80000CF0", size = 252 },
  { name = "func_80000DEC", size = 668 },
  { name = "func_80001088", size = 164 },
  { name = "func_8000112C", size = 300 },
  { name = "func_80001258", size = 52 },
  { name = "func_8000128C", size = 552 },
  { name = "func_800014B4", size = 12 },
  { name = "func_800014C0", size = 12 },
  { name = "func_800014CC", size = 28 },
  { name = "func_800014E8", size = 156 },
  { name = "func_80001584", size = 76 },
  { name = "func_800015D0", size = 220 },
  { name = "func_800016AC", size = 16 },
  { name = "func_800016BC", size = 140 },
  { name = "func_80001748", size = 204 },
  { name = "func_80001814", size = 76 },
  { name = "func_80001860", size = 16 },
  { name = "func_80001870", size = 36 },
  { name = "func_80001894", size = 8 },
  { name = "func_8000189C", size = 12 },
  { name = "func_800018A8", size = 236 },
  { name = "func_80001994", size = 552 },
  { name = "func_80001BBC", size = 244 },
  { name = "func_80001CB0", size = 64 },
  { name = "func_80001CF0", size = 492 },
  { name = "func_80001EDC", size = 536 },
  { name = "func_800020F4", size = 220 },
  { name = "func_800021D0", size = 248 },
  { name = "func_800022C8", size = 732 },
  { name = "func_800025A4", size = 172 },
  { name = "func_80002650", size = 268 },
  { name = "func_8000275C", size = 132 },
  { name = "func_800027E0", size = 176 },
  { name = "osSetIntMask", size = 160 },
  { name = "osInitialize", size = 1152 },
  { name = "func_80002DB0", size = 96 },
  { name = "func_80002E10", size = 44 },
  { name = "__ull_rem", size = 60 },
  { name = "__ull_div", size = 60 },
  { name = "func_80002EB4", size = 44 },
  { name = "func_80002EE0", size = 60 },
  { name = "__ll_div", size = 92 },
  { name = "__ll_mul", size = 48 },
  { name = "func_80002FA8", size = 96 },
  { name = "func_80003008", size = 156 },
  { name = "func_800030A4", size = 44 },
  { name = "func_800030D0", size = 256 },
  { name = "func_800031D0", size = 16 },
  { name = "func_800031E0", size = 16 },
  { name = "osWritebackDCache", size = 128 },
  { name = "func_80003270", size = 16 },
  { name = "func_80003C24", size = 232 },
  { name = "func_80003D0C", size = 256 },
  { name = "func_80003E0C", size = 72 },
  { name = "func_80003E54", size = 16 },
  { name = "func_80003E64", size = 380 },
  { name = "func_80003FF0", size = 64 },
  { name = "osDestroyThread", size = 272 },
  { name = "func_80004140", size = 1700 },
  { name = "func_800047E4", size = 232 },
  { name = "func_800048CC", size = 244 },
  { name = "func_800049C0", size = 144 },
  { name = "func_80004A50", size = 224 },
  { name = "osVirtualToPhysical", size = 128 },
  { name = "func_80004BB0", size = 88 },
  { name = "func_80004C08", size = 116 },
  { name = "func_80004C7C", size = 108 },
  { name = "func_80004CE8", size = 208 },
  { name = "func_80004DB8", size = 264 },
  { name = "func_80004EC0", size = 80 },
  { name = "func_80004F10", size = 208 },
  { name = "osRecvMesg", size = 320 },
  { name = "func_80005120", size = 192 },
  { name = "osSetEventMesg", size = 112 },
  { name = "func_80005250", size = 256 },
  { name = "osInvalICache", size = 128 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "osInvalDCache", size = 192 },
  { name = "func_800054C0", size = 116 },
  { name = "func_80005534", size = 80 },
  { name = "func_80005584", size = 108 },
  { name = "func_800055F0", size = 208 },
  { name = "func_800056C0", size = 48 },
  { name = "osEPiRawStartDma", size = 560 },
  { name = "osCreatePiManager", size = 460 },
  { name = "func_80005AEC", size = 276 },
  { name = "func_80005C00", size = 80 },
  { name = "func_80005C50", size = 68 },
  { name = "func_80005C94", size = 44 },
  { name = "osCartRomInit", size = 256 },
  { name = "osSendMesg", size = 336 },
  { name = "osCreateThread", size = 336 },
  { name = "func_80006060", size = 1168 },
  { name = "osGetThreadPri", size = 32 },
  { name = "osSetThreadPri", size = 224 },
  { name = "func_800065F0", size = 80 },
  { name = "func_80006640", size = 16 },
  { name = "func_80006650", size = 96 },
  { name = "__osDisableInt", size = 32 },
  { name = "__osRestoreInt", size = 32 },
  { name = "__osRdbSend", size = 704 },
  { name = "func_800069B0", size = 12 },
  { name = "func_800069BC", size = 148 },
  { name = "func_80006A50", size = 72 },
  { name = "func_80006A98", size = 84 },
  { name = "func_80006AEC", size = 52 },
  { name = "func_80006B20", size = 52 },
  { name = "func_80006B54", size = 60 },
  { name = "func_80006B90", size = 508 },
  { name = "func_80006D8C", size = 588 },
  { name = "func_80006FD8", size = 128 },
  { name = "func_80007058", size = 12 },
  { name = "func_80007064", size = 168 },
  { name = "func_8000710C", size = 112 },
  { name = "func_8000717C", size = 484 },
  { name = "func_80007360", size = 152 },
  { name = "func_800073F8", size = 168 },
  { name = "func_800074A0", size = 288 },
  { name = "func_800075C0", size = 416 },
  { name = "func_80007760", size = 124 },
  { name = "func_800077DC", size = 128 },
  { name = "func_8000785C", size = 264 },
  { name = "func_80007964", size = 308 },
  { name = "func_80007A98", size = 756 },
  { name = "func_80007D8C", size = 104 },
  { name = "func_80007DF4", size = 328 },
  { name = "func_80007F3C", size = 660 },
  { name = "osStopThread", size = 208 },
  { name = "func_800082A0", size = 76 },
  { name = "func_800082EC", size = 220 },
  { name = "func_800083C8", size = 32 },
  { name = "func_800083E8", size = 72 },
  { name = "func_80008430", size = 36 },
  { name = "func_80008454", size = 68 },
  { name = "func_80008498", size = 20 },
  { name = "func_800084AC", size = 36 },
  { name = "func_800084D0", size = 172 },
  { name = "func_8000857C", size = 232 },
  { name = "func_80008664", size = 448 },
  { name = "func_80008824", size = 12 },
  { name = "func_80008830", size = 348 },
  { name = "func_8000898C", size = 552 },
  { name = "func_80008BB4", size = 148 },
  { name = "func_80008C48", size = 196 },
  { name = "func_80008D0C", size = 64 },
  { name = "func_80008D4C", size = 188 },
  { name = "func_80008E08", size = 48 },
  { name = "func_80008E38", size = 104 },
  { name = "func_80008EA0", size = 48 },
  { name = "func_80008ED0", size = 224 },
  { name = "func_80008FB0", size = 80 },
  { name = "func_80009000", size = 48 },
  { name = "func_80009030", size = 132 },
  { name = "func_800090B4", size = 148 },
  { name = "func_80009148", size = 168 },
  { name = "func_800091F0", size = 168 },
  { name = "func_80009298", size = 348 },
  { name = "func_800093F4", size = 336 },
  { name = "func_80009544", size = 184 },
  { name = "func_800095FC", size = 180 },
  { name = "func_800096B0", size = 100 },
  { name = "func_80009714", size = 352 },
  { name = "func_80009874", size = 272 },
  { name = "func_80009984", size = 280 },
  { name = "func_80009A9C", size = 196 },
  { name = "func_80009B60", size = 208 },
  { name = "func_80009C30", size = 16 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_80009C50", size = 416 },
  { name = "func_80009DF0", size = 96 },
  { name = "func_80009E50", size = 80 },
  { name = "func_80009EA0", size = 16 },
  { name = "func_80009EB0", size = 400 },
  { name = "func_8000A040", size = 80 },
  { name = "func_8000A090", size = 80 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "osStartThread", size = 336 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
