/**
 * main.cpp — Star Fox 64 PC port entry point. Generated by recompilator/scaffold_app.py.
 *
 * The MINIMAL game profile (the sm64pc/lodpc pattern): ROM identity/validation,
 * recompiled-section registration, renderer/audio/input wiring, the entrypoint, a
 * crash handler, and diagnostic logging. Every game-specific value below comes from
 * recon (ROM header, XXH3, entrypoint) — there are NO addresses from any other game.
 *
 * Engine: ../engine (the single agnostic engine: rt64 + runtime). Cross-platform by
 * construction — Windows / Linux / macOS / Linux-ARM. Pick a target with the
 * CMakePresets in this directory (e.g. `cmake --preset linux-arm64`). Keep this file free
 * of throwaway debug probes; put those behind an env var in the engine, or a local edit.
 */

#if defined(_WIN32)
#include <Windows.h>
#include <commdlg.h>   // OPENFILENAMEA / GetOpenFileNameA
#endif
#include <string>
#include <filesystem>
#include <cstdlib>
#include <cstdio>
#include <atomic>

#define SDL_MAIN_HANDLED
#include "SDL.h"
#include "SDL_syswm.h"

#include "recomp.h"
#include "librecomp/game.hpp"
#include "librecomp/overlays.hpp"
#include "librecomp/sections.h"
#include "ultramodern/ultramodern.hpp"
#include "ultramodern/renderer_context.hpp"
#include "ultramodern/error_handling.hpp"

#ifndef RDPC_CONSOLE_ONLY
#include "rt64_renderer.hpp"
#endif
#ifdef RDPC_CAPTURE_CHAIN
#include "lle_console.h"   // preservation-core console renderer (RDPC_LLE_CONSOLE=1) + blit_tick
#endif

ultramodern::audio_callbacks_t    get_audio_callbacks();
ultramodern::input::callbacks_t   get_input_callbacks();
recomp::rsp::callbacks_t          get_rsp_callbacks();
void starfox64_audio_init();
void starfox64_input_init();

// ── Star Fox 64 game identity (recon: ROM header + XXH3) ───────────────────────
// NFXE rev 1.1 (Rev A) — recompiled 2026-07-30 from a retail cartridge (DreamDump64,
// re-dump verified byte-stable). SHA1: 09f0d105f476b00efa5303a3ebc42e60a7753b7a.
// Ucode note: both consumed ucode images verified byte-identical to rev 1.0 (Rev A's 80
// gfx-ucode byte diffs all live in the unconsumed spare region past file 0x1430).
static constexpr uint64_t STARFOX64_ROM_HASH        = 0x163FD3FC3813F54EULL;
static constexpr uint32_t STARFOX64_ENTRYPOINT_VRAM = 0x80000400;

extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);

#include "recomp_overlays.inl"

static SDL_Window* sdl_window = nullptr;
extern std::atomic<double> g_cv64_present_fps;   // present-FPS counter (engine global)

// Cross-platform error dialog: native MessageBox on Windows, SDL elsewhere.
static void starfox64_show_error(const char* title, const char* msg) {
#if defined(_WIN32)
    MessageBoxA(nullptr, msg, title, MB_ICONERROR | MB_OK);
#else
    SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, title, msg, nullptr);
#endif
}

static ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
    if (SDL_InitSubSystem(SDL_INIT_VIDEO) != 0) {
        starfox64_show_error("SDL_InitSubSystem Error", SDL_GetError());
    }
    return nullptr;
}

static ultramodern::renderer::WindowHandle
create_window(ultramodern::gfx_callbacks_t::gfx_data_t /*gfx_data*/)
{
    Uint32 win_flags = SDL_WINDOW_RESIZABLE;
#if !defined(_WIN32)
    win_flags |= SDL_WINDOW_VULKAN;   // Linux + macOS (MoltenVK) render via Vulkan
#endif
#ifdef RDPC_CAPTURE_CHAIN
    if (preservation_core::lleconsole::active()) {
        // Console mode (RDPC_LLE_CONSOLE=1): no Vulkan window; GL only for the accelerated
        // upscale presenter (RDPC_LLE_GPU_PRESENT=1). Ported verbatim from cv64pc (game #5).
        win_flags = SDL_WINDOW_RESIZABLE;
        if (const char* fs = std::getenv("RDPC_LLE_FULLSCREEN"); fs && fs[0] == '1')
            win_flags |= SDL_WINDOW_FULLSCREEN_DESKTOP;
        if (const char* gp = std::getenv("RDPC_LLE_GPU_PRESENT"); gp && gp[0] == '1')
            win_flags |= SDL_WINDOW_OPENGL;
    }
#endif
    sdl_window = SDL_CreateWindow(
        "Star Fox 64 PC",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        1920, 1080,
        win_flags);
    if (!sdl_window) {
        starfox64_show_error("Window Creation Error", SDL_GetError());
        std::exit(1);
    }

#if defined(_WIN32)
    SDL_SysWMinfo wm_info;
    SDL_VERSION(&wm_info.version);
    SDL_GetWindowWMInfo(sdl_window, &wm_info);
    return ultramodern::renderer::WindowHandle{
        wm_info.info.win.window,
        GetCurrentThreadId()
    };
#elif defined(__APPLE__)
    SDL_SysWMinfo wm_info;
    SDL_VERSION(&wm_info.version);
    SDL_GetWindowWMInfo(sdl_window, &wm_info);
    SDL_MetalView mv = SDL_Metal_CreateView(sdl_window);   // CAMetalLayer-backed view for MoltenVK
    return ultramodern::renderer::WindowHandle{ wm_info.info.cocoa.window, SDL_Metal_GetLayer(mv) };
#else
    return sdl_window;   // ultramodern::renderer::WindowHandle == SDL_Window* on Linux/Android
#endif
}

static void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t /*gfx_data*/) {
    SDL_Event evt;
    while (SDL_PollEvent(&evt)) {
        if (evt.type == SDL_QUIT) {
            ultramodern::quit();
        }
    }
#ifdef RDPC_CAPTURE_CHAIN
    // Console mode: present the latest VI frame from the preservation core (owner thread).
    preservation_core::lleconsole::blit_tick(sdl_window);
#endif
    {
        static double last_fps = -1.0;
        double fps = g_cv64_present_fps.load(std::memory_order_relaxed);
        if (sdl_window != nullptr && fps != last_fps) {
            last_fps = fps;
            char title[80];
            snprintf(title, sizeof(title), "Star Fox 64 PC  -  %.1f FPS", fps);
            SDL_SetWindowTitle(sdl_window, title);
        }
    }
}

static std::unique_ptr<ultramodern::renderer::RendererContext>
starfox64_create_render_context(uint8_t* rdram, ultramodern::renderer::WindowHandle window_handle, bool developer_mode) {
#ifdef RDPC_CAPTURE_CHAIN
    // Console mode (RDPC_LLE_CONSOLE=1): the preservation-core console replaces RT64 entirely.
    if (preservation_core::lleconsole::active()) {
        // Game-agnostic submit seam (organ Move 1): register before the first send_dl.
        extern void sf64_lle_console_submit();
        preservation_core::lleconsole::set_submit_callback(&sf64_lle_console_submit);
        return preservation_core::lleconsole::create_console_context(rdram);
    }
#endif
#ifdef RDPC_CONSOLE_ONLY
    // PLAN V3 amendment A: no RT64 in this binary. Console mode is the only renderer.
    starfox64_show_error("Renderer", "Console-only build: set RDPC_LLE_CONSOLE=1 (console.sh).");
    std::exit(1);
#else
    return starfox64::renderer::create_render_context(rdram, window_handle, developer_mode);
#endif
}

static void starfox64_message_box(const char* msg) {
    starfox64_show_error("Star Fox 64 — Error", msg);
}

#if defined(_WIN32)
static LONG WINAPI starfox64_unhandled_exception(EXCEPTION_POINTERS* ep) {
    fflush(stderr);
    DWORD  code = ep->ExceptionRecord->ExceptionCode;
    void*  addr = ep->ExceptionRecord->ExceptionAddress;
    ULONG_PTR* info = ep->ExceptionRecord->ExceptionInformation;
    HMODULE hmod = nullptr;
    GetModuleHandleExA(
        GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
        GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
        (LPCSTR)addr, &hmod);
    ULONG_PTR rva = hmod ? (ULONG_PTR)addr - (ULONG_PTR)hmod : 0;
    char detail[64] = "";
    if (code == EXCEPTION_ACCESS_VIOLATION && ep->ExceptionRecord->NumberParameters >= 2) {
        snprintf(detail, sizeof(detail), "\nAccess: %s 0x%llX",
            info[0] == 0 ? "READ" : "WRITE", (unsigned long long)info[1]);
    }
    char msg[1024];
    snprintf(msg, sizeof(msg),
        "UNHANDLED EXCEPTION\n\nCode:        0x%08X\nAddress:     0x%p\n"
        "RVA (map):   0x%08llX%s\n\nThis offset matches a line in starfox64pc.map.\n"
        "Compare Address against the exe base BEFORE map lookups.\n\nThread: %u",
        code, addr, (unsigned long long)rva, detail, GetCurrentThreadId());
    fprintf(stderr, "%s\n", msg);
    fflush(stderr);
    __try {
        HMODULE exe = GetModuleHandleA(nullptr);
        CONTEXT* ctx = ep->ContextRecord;
        if (exe != nullptr && ctx != nullptr) {
            const uintptr_t* sp = (const uintptr_t*)ctx->Rsp;
            fprintf(stderr, "[crashstack] Rsp=0x%p — call sites in starfox64pc.exe (base=0x%p), nearest first:\n",
                    (void*)ctx->Rsp, (void*)exe);
            int found = 0;
            for (int i = 0; i < 128 && found < 16; i++) {
                uintptr_t ret = sp[i];
                HMODULE m = nullptr;
                if (GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                                       GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                                       (LPCSTR)ret, &m) && m == exe) {
                    fprintf(stderr, "[crashstack]   stack+0x%03X  RVA=0x%08llX\n",
                            (unsigned)(i * 8), (unsigned long long)(ret - (uintptr_t)exe));
                    found++;
                }
            }
            fprintf(stderr, "[crashstack] (%d call sites found)\n", found);
            fflush(stderr);
        }
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        fprintf(stderr, "[crashstack] (stack scan faulted — Rsp corrupt)\n"); fflush(stderr);
    }
    MessageBoxA(nullptr, msg, "Star Fox 64 — Crash", MB_ICONERROR | MB_OK);
    return EXCEPTION_CONTINUE_SEARCH;
}
#endif // _WIN32 (crash handler)

static void starfox64_vi_callback() {}
static void starfox64_gfx_init_callback() {}

static std::string starfox64_get_thread_name(const OSThread* t) {
    return "starfox64_" + std::to_string(t->id);
}

static void prompt_for_rom(const char* rom_hint) {
    std::filesystem::path rom_path;

#if defined(_WIN32)
    if (rom_hint && *rom_hint) {
        rom_path = rom_hint;
    } else {
        OPENFILENAMEA ofn   = {};
        char          path[MAX_PATH] = {};
        ofn.lStructSize = sizeof(ofn);
        ofn.lpstrFilter = "N64 ROM Files\0*.z64;*.n64;*.v64\0All Files\0*.*\0";
        ofn.lpstrFile   = path;
        ofn.nMaxFile    = MAX_PATH;
        ofn.lpstrTitle  = "Select Star Fox 64 ROM";
        ofn.Flags       = OFN_FILEMUSTEXIST | OFN_PATHMUSTEXIST;
        if (!GetOpenFileNameA(&ofn)) {
            starfox64_show_error("ROM Required",
                "A Star Fox 64 ROM is required.\n"
                "Please supply your own legally obtained copy.");
            std::exit(0);
        }
        rom_path = path;
    }
#else
    // No native file dialog wired off Windows: take the ROM path from argv[1] or the
    // STARFOX64_ROM env var (e.g. an SBC/console that already has the ROM at a known path).
    if (!rom_hint || !*rom_hint) rom_hint = std::getenv("STARFOX64_ROM");
    if (!rom_hint || !*rom_hint) {
        starfox64_show_error("ROM Required",
            "Pass the Star Fox 64 ROM path as the first argument,\n"
            "or set the STARFOX64_ROM environment variable.");
        std::exit(0);
    }
    rom_path = rom_hint;
#endif

    std::u8string out_id = u8"starfox64_us_r11";   // must match entry.game_id (the ROM Error of 2026-08-24)
    auto err = recomp::select_rom(rom_path, out_id);
    switch (err) {
    case recomp::RomValidationError::Good:
        return;
    case recomp::RomValidationError::IncorrectRom:
    case recomp::RomValidationError::IncorrectVersion:
        starfox64_show_error("Wrong ROM",
            "The selected ROM does not match Star Fox 64.\n"
            "Expected SHA1: d8b1088520f7c5f81433292a9258c1184afa1457");
        std::exit(1);
    case recomp::RomValidationError::NotARom:
        starfox64_show_error("Not an N64 ROM", "The selected file does not appear to be an N64 ROM.");
        std::exit(1);
    default:
        starfox64_show_error("ROM Error", "Failed to read the selected ROM file.");
        std::exit(1);
    }
}

static int starfox64_app_main(int argc, char** argv)
{
    const char* rom_hint = (argc > 1) ? argv[1] : nullptr;

#if defined(_WIN32)
    SetUnhandledExceptionFilter(starfox64_unhandled_exception);
#endif
    SDL_SetMainReady();

#if defined(_WIN32)
    const char* appdata = std::getenv("APPDATA");
    if (!appdata) appdata = ".";
    std::filesystem::path config_path = std::filesystem::path(appdata) / "starfox64pc";
#else
    const char* xdg  = std::getenv("XDG_CONFIG_HOME");
    const char* home = std::getenv("HOME");
    std::filesystem::path config_base =
        (xdg && *xdg) ? std::filesystem::path(xdg)
                      : (home ? std::filesystem::path(home) / ".config"
                              : std::filesystem::path("."));
    std::filesystem::path config_path = config_base / "starfox64pc";
#endif
    std::filesystem::create_directories(config_path);

    {
        std::filesystem::path log_path = config_path / "starfox64pc_diag.log";
        FILE* f = nullptr;
#if defined(_WIN32)
        freopen_s(&f, log_path.string().c_str(), "w", stderr);
#else
        f = freopen(log_path.string().c_str(), "w", stderr);
#endif
        if (f) { setvbuf(f, nullptr, _IONBF, 0); fprintf(stderr, "[starfox64pc] diagnostic log started\n"); }
        std::filesystem::path stdout_path = config_path / "starfox64pc_stdout.log";
        FILE* fout = nullptr;
#if defined(_WIN32)
        freopen_s(&fout, stdout_path.string().c_str(), "w", stdout);
#else
        fout = freopen(stdout_path.string().c_str(), "w", stdout);
#endif
        if (fout) { setvbuf(fout, nullptr, _IONBF, 0); fprintf(stdout, "[starfox64pc] stdout log started\n"); }
    }

    recomp::register_config_path(config_path);

    recomp::GameEntry entry{};
    entry.rom_hash           = STARFOX64_ROM_HASH;
    entry.internal_name      = "Star Fox 64";
    entry.game_id            = u8"starfox64_us_r11";   // distinct save/config identity for the 1.1 cart build
    entry.mod_game_id        = "";
    entry.save_type          = recomp::SaveType::Eep4k;
    entry.is_enabled         = true;
    entry.entrypoint_address = STARFOX64_ENTRYPOINT_VRAM;
    entry.entrypoint         = recomp_entrypoint;
    recomp::register_game(entry);

    recomp::overlays::register_overlays(
        recomp::overlays::overlay_section_table_data_t{
            .code_sections      = section_table,
            .num_code_sections  = sizeof(section_table) / sizeof(section_table[0]),
            .total_num_sections = num_sections,
        },
        recomp::overlays::overlays_by_index_t{
            .table = overlay_sections_by_index,
            .len   = sizeof(overlay_sections_by_index) / sizeof(overlay_sections_by_index[0]),
        });

    recomp::check_all_stored_roms();
    std::u8string game_id = u8"starfox64_us_r11";   // must match entry.game_id
    if (!recomp::is_rom_valid(game_id)) {
        prompt_for_rom(rom_hint);
        recomp::check_all_stored_roms();
        if (!recomp::is_rom_valid(game_id)) {
            starfox64_show_error("Error", "ROM validation failed after selection.");
            return 1;
        }
    }

    SDL_Init(SDL_INIT_AUDIO);
    starfox64_audio_init();
    starfox64_input_init();

    recomp::start_game(game_id);

    (void)0;
    recomp::Configuration cfg{};
    cfg.project_version      = { 0, 1, 0, "" };
    cfg.rsp_callbacks        = get_rsp_callbacks();
    cfg.renderer_callbacks   = { .create_render_context = starfox64_create_render_context };
    cfg.audio_callbacks      = get_audio_callbacks();
    cfg.input_callbacks      = get_input_callbacks();
    cfg.gfx_callbacks        = {
        .create_gfx    = create_gfx,
        .create_window = create_window,
        .update_gfx    = update_gfx,
    };
    cfg.events_callbacks     = {
        .vi_callback       = starfox64_vi_callback,
        .gfx_init_callback = starfox64_gfx_init_callback,
    };
    cfg.error_handling_callbacks = { .message_box = starfox64_message_box };
    cfg.threads_callbacks    = { .get_game_thread_name = starfox64_get_thread_name };
    cfg.message_queue_control = {
        .requeue_timer = true,
        .requeue_sp    = true,
        .requeue_si    = true,
        .requeue_ai    = false,
        .requeue_vi    = false,
        .requeue_pi    = false,
        .requeue_dp    = true,
    };

    recomp::start(cfg);

    SDL_Quit();
    return 0;
}

// ── Entry point: GUI WinMain on Windows, standard main() on Linux/macOS ────────
#if defined(_WIN32)
int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int) {
    return starfox64_app_main(__argc, __argv);   // CRT-provided argc/argv
}
#else
int main(int argc, char** argv) {
    return starfox64_app_main(argc, argv);
}
#endif
