[input]
entrypoint                = 0x80300000
elf_path                  = "../allstarbaseball99/build/allstarbaseball99.elf"
rom_file_path             = "../allstarbaseball99/baserom.z64"
output_func_path          = "../allstarbaseball99pc/RecompiledFuncs"
relocatable_sections_path = "allstarbaseball99_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80300000", size = 64 },
  { name = "func_80300068", size = 236 },
  { name = "func_80300154", size = 24 },
  { name = "func_8030016C", size = 56 },
  { name = "func_803001A4", size = 68 },
  { name = "func_803001E8", size = 52 },
  { name = "func_8030021C", size = 80 },
  { name = "func_8030026C", size = 4 },
  { name = "func_80300270", size = 208 },
  { name = "func_80300340", size = 428 },
  { name = "func_803004EC", size = 216 },
  { name = "func_803005C4", size = 52 },
  { name = "func_803005F8", size = 60 },
  { name = "func_80300634", size = 36 },
  { name = "func_80300658", size = 384 },
  { name = "func_803007D8", size = 36 },
  { name = "func_803007FC", size = 4 },
  { name = "func_80300800", size = 56 },
  { name = "func_80300838", size = 48 },
  { name = "func_80300868", size = 56 },
  { name = "func_803008A0", size = 60 },
  { name = "func_803008DC", size = 72 },
  { name = "func_80300924", size = 64 },
  { name = "func_80300964", size = 220 },
  { name = "func_80300A40", size = 60 },
  { name = "func_80300A7C", size = 276 },
  { name = "func_80300B90", size = 120 },
  { name = "func_80300C08", size = 236 },
  { name = "func_80300CF4", size = 204 },
  { name = "func_80300DC0", size = 116 },
  { name = "func_80300E34", size = 432 },
  { name = "func_80300FE4", size = 256 },
  { name = "func_803010E4", size = 204 },
  { name = "func_803011B0", size = 592 },
  { name = "func_80301400", size = 184 },
  { name = "func_803014B8", size = 32 },
  { name = "func_803014D8", size = 76 },
  { name = "func_80301524", size = 144 },
  { name = "func_803015B4", size = 144 },
  { name = "func_80301644", size = 104 },
  { name = "func_803016AC", size = 196 },
  { name = "func_80301770", size = 200 },
  { name = "func_80301838", size = 112 },
  { name = "func_803018A8", size = 76 },
  { name = "func_80301918", size = 172 },
  { name = "func_803019C4", size = 28 },
  { name = "func_803019E0", size = 28 },
  { name = "func_803019FC", size = 12 },
  { name = "func_80301A08", size = 12 },
  { name = "func_80301A14", size = 1004 },
  { name = "func_80301EC0", size = 108 },
  { name = "func_80301F2C", size = 92 },
  { name = "func_80301F88", size = 776 },
  { name = "func_803249A8", size = 32 },
  { name = "func_80333EBC", size = 32 },
  { name = "func_80350694", size = 16 },
  { name = "func_80390820", size = 4 },
  { name = "func_803913C8", size = 12 },
  { name = "func_803928E0", size = 12 },
  { name = "func_803AE9D0", size = 16 },
  { name = "func_803AEB44", size = 16 },
  { name = "func_803FC0C4", size = 16 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
