[input]
entrypoint                = 0x80000400
elf_path                  = "../legendofzeldatheoc/build/legendofzeldatheoc.elf"
rom_file_path             = "../legendofzeldatheoc/build/baserom_dec.z64"
output_func_path          = "../legendofzeldatheocpc/RecompiledFuncs"
relocatable_sections_path = "legendofzeldatheoc_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80000400", size = 96 },
  { name = "func_80000460", size = 56 },
  { name = "func_80000498", size = 264 },
  { name = "func_800005A0", size = 156 },
  { name = "func_8000063C", size = 436 },
  { name = "func_800007F0", size = 108 },
  { name = "func_8000085C", size = 388 },
  { name = "func_800009E0", size = 116 },
  { name = "func_80000A54", size = 164 },
  { name = "func_80000AF8", size = 20 },
  { name = "func_80000B0C", size = 412 },
  { name = "func_80000CA8", size = 128 },
  { name = "func_80000D28", size = 200 },
  { name = "func_80000DF0", size = 124 },
  { name = "func_80000E6C", size = 244 },
  { name = "func_80000F60", size = 160 },
  { name = "func_80001000", size = 236 },
  { name = "func_800010EC", size = 360 },
  { name = "func_80001254", size = 76 },
  { name = "func_800012A0", size = 112 },
  { name = "func_80001310", size = 16 },
  { name = "func_80001320", size = 24 },
  { name = "func_80001338", size = 20 },
  { name = "func_8000134C", size = 236 },
  { name = "func_80001438", size = 52 },
  { name = "func_8000146C", size = 36 },
  { name = "func_80001490", size = 224 },
  { name = "func_80001564", size = 12 },
  { name = "func_80001570", size = 48 },
  { name = "func_800015A0", size = 28 },
  { name = "func_800015BC", size = 28 },
  { name = "func_800015D8", size = 28 },
  { name = "func_800015F4", size = 12 },
  { name = "func_80001600", size = 480 },
  { name = "func_800017E0", size = 176 },
  { name = "func_80001890", size = 184 },
  { name = "func_80001948", size = 68 },
  { name = "func_8000198C", size = 276 },
  { name = "func_80001AA0", size = 152 },
  { name = "func_80001B38", size = 76 },
  { name = "func_80001B84", size = 60 },
  { name = "func_80001BC0", size = 108 },
  { name = "func_80001C2C", size = 80 },
  { name = "func_80001C7C", size = 80 },
  { name = "func_80001CCC", size = 84 },
  { name = "func_80001D20", size = 64 },
  { name = "func_80001D60", size = 80 },
  { name = "func_80001DB0", size = 68 },
  { name = "func_80001DF4", size = 44 },
  { name = "osSendMesg", size = 336 },
  { name = "osStopThread", size = 192 },
  { name = "osRecvMesg", size = 320 },
  { name = "func_80002170", size = 44 },
  { name = "__ull_rem", size = 60 },
  { name = "__ull_div", size = 60 },
  { name = "func_80002214", size = 44 },
  { name = "func_80002240", size = 60 },
  { name = "__ll_div", size = 92 },
  { name = "__ll_mul", size = 48 },
  { name = "func_80002308", size = 96 },
  { name = "func_80002368", size = 156 },
  { name = "func_80002404", size = 44 },
  { name = "func_80002430", size = 16 },
  { name = "func_80002964", size = 232 },
  { name = "func_80002A4C", size = 256 },
  { name = "func_80002B4C", size = 72 },
  { name = "func_80002B94", size = 396 },
  { name = "func_80002D30", size = 64 },
  { name = "osDestroyThread", size = 272 },
  { name = "_bzero", size = 160 },
  { name = "osCreateThread", size = 336 },
  { name = "osInitialize", size = 680 },
  { name = "func_80003318", size = 264 },
  { name = "func_80003420", size = 16 },
  { name = "func_80003430", size = 16 },
  { name = "osWritebackDCache", size = 128 },
  { name = "osViGetNextFramebuffer", size = 64 },
  { name = "osCreatePiManager", size = 384 },
  { name = "func_80003680", size = 1040 },
  { name = "func_80003A90", size = 208 },
  { name = "osVirtualToPhysical", size = 128 },
  { name = "osViBlack", size = 112 },
  { name = "func_80003C50", size = 80 },
  { name = "osGetThreadId", size = 32 },
  { name = "osSetIntMask", size = 160 },
  { name = "osViSetMode", size = 112 },
  { name = "func_80003DD0", size = 192 },
  { name = "osGetMemSize", size = 288 },
  { name = "osSetEventMesg", size = 192 },
  { name = "func_80004070", size = 80 },
  { name = "osEPiStartDma", size = 224 },
  { name = "osInvalICache", size = 128 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "osInvalDCache", size = 176 },
  { name = "func_80004300", size = 48 },
  { name = "osJamMesg", size = 336 },
  { name = "osSetThreadPri", size = 224 },
  { name = "osGetThreadPri", size = 32 },
  { name = "func_80004580", size = 352 },
  { name = "func_800046E0", size = 480 },
  { name = "osGetTime", size = 144 },
  { name = "func_80004950", size = 140 },
  { name = "func_800049DC", size = 376 },
  { name = "func_80004B54", size = 116 },
  { name = "func_80004BC8", size = 392 },
  { name = "osGetCount", size = 16 },
  { name = "func_80004D60", size = 80 },
  { name = "func_80004DB0", size = 16 },
  { name = "func_80004DC0", size = 784 },
  { name = "func_800050D0", size = 96 },
  { name = "__osDisableInt", size = 112 },
  { name = "__osRestoreInt", size = 32 },
  { name = "func_800051C0", size = 320 },
  { name = "func_80005300", size = 768 },
  { name = "func_80005600", size = 48 },
  { name = "osEPiReadIo", size = 80 },
  { name = "osCartRomInit", size = 352 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_800057F0", size = 16 },
  { name = "func_80005800", size = 80 },
  { name = "func_80005850", size = 96 },
  { name = "func_800058B0", size = 80 },
  { name = "func_80005900", size = 16 },
  { name = "func_80005910", size = 352 },
  { name = "osSetTimer", size = 224 },
  { name = "func_80005B50", size = 80 },
  { name = "osCreateViManager", size = 384 },
  { name = "func_80005D20", size = 400 },
  { name = "func_80005EB0", size = 16 },
  { name = "osStartThread", size = 336 },
  { name = "func_80006010", size = 112 },
  { name = "func_80006080", size = 48 },
  { name = "func_80006178", size = 80 },
  { name = "func_800061C8", size = 72 },
]

exact_size_funcs = [

]

[patches]
stubs = [
  "func_80004070",
  "func_80006178",
]
