[input]
entrypoint                = 0x80200400
elf_path                  = "../maddennfl2000/build/maddennfl2000.elf"
rom_file_path             = "../maddennfl2000/baserom.z64"
output_func_path          = "../maddennfl2000pc/RecompiledFuncs"
relocatable_sections_path = "maddennfl2000_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80200400", size = 16 },
  { name = "func_80200410", size = 168 },
  { name = "func_802004B8", size = 300 },
  { name = "func_802005E4", size = 4 },
  { name = "func_802005E8", size = 280 },
  { name = "func_80200700", size = 156 },
  { name = "func_8020079C", size = 664 },
  { name = "func_80200A34", size = 4 },
  { name = "osInvalICache", size = 128 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "func_80203B7C", size = 64 },
  { name = "func_8020EDF4", size = 16 },
  { name = "func_8021028C", size = 16 },
  { name = "func_8021DFEC", size = 16 },
  { name = "func_80223680", size = 32 },
  { name = "func_802275B8", size = 16 },
  { name = "func_802284E8", size = 32 },
  { name = "func_8022E018", size = 32 },
  { name = "func_80234094", size = 128 },
  { name = "func_802365E8", size = 32 },
  { name = "func_8023A0A0", size = 80 },
  { name = "func_8023B3E0", size = 48 },
  { name = "func_8023BF98", size = 48 },
  { name = "func_8025C758", size = 16 },
  { name = "func_8025CCE0", size = 16 },
  { name = "func_8026D758", size = 16 },
  { name = "func_8027B9EC", size = 60 },
  { name = "func_8027BA28", size = 60 },
  { name = "func_8027BA64", size = 60 },
  { name = "func_8027BAA0", size = 60 },
  { name = "func_8027BADC", size = 60 },
  { name = "func_8027BB18", size = 60 },
  { name = "func_8027BB54", size = 60 },
  { name = "func_8027BB90", size = 60 },
  { name = "func_8027BBCC", size = 60 },
  { name = "func_8027BC08", size = 60 },
  { name = "func_8027BC44", size = 60 },
  { name = "func_8027BC80", size = 60 },
  { name = "func_8027BCBC", size = 60 },
  { name = "func_8027BCF8", size = 60 },
  { name = "func_8027BD34", size = 60 },
  { name = "func_8027BD70", size = 60 },
  { name = "func_8027BDAC", size = 60 },
  { name = "func_8027BDE8", size = 60 },
  { name = "func_8027BE24", size = 60 },
  { name = "func_8027BE60", size = 60 },
  { name = "func_8027BE9C", size = 60 },
  { name = "func_8027BED8", size = 60 },
  { name = "func_8027BF14", size = 60 },
  { name = "func_8027BF50", size = 60 },
  { name = "func_8027BF8C", size = 60 },
  { name = "func_8027BFC8", size = 60 },
  { name = "func_8027C004", size = 60 },
  { name = "func_8027C040", size = 72 },
  { name = "func_8027D040", size = 304 },
  { name = "func_8028B510", size = 16 },
  { name = "func_8028D8F8", size = 16 },
  { name = "func_80292498", size = 16 },
  { name = "func_802A3770", size = 16 },
  { name = "func_802A4E54", size = 96 },
  { name = "func_802A5770", size = 80 },
  { name = "func_802A74C8", size = 16 },
  { name = "func_802ABDA0", size = 64 },
  { name = "func_802AD6D0", size = 32 },
  { name = "func_802BB624", size = 16 },
  { name = "func_802C1B50", size = 80 },
  { name = "func_802C2724", size = 16 },
  { name = "func_802C2BF8", size = 16 },
  { name = "func_802C5CF0", size = 60 },
  { name = "func_802C5D2C", size = 112 },
  { name = "func_802C651C", size = 16 },
  { name = "func_802D5C7C", size = 16 },
  { name = "func_802D9378", size = 64 },
  { name = "func_802E362C", size = 80 },
  { name = "func_802F5498", size = 16 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
