[input]
entrypoint                = 0x80000400
elf_path                  = "../wwfwarzone/build/wwfwarzone.elf"
rom_file_path             = "../wwfwarzone/baserom.z64"
output_func_path          = "../wwfwarzonepc/RecompiledFuncs"
relocatable_sections_path = "wwfwarzone_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80000400", size = 16 },
  { name = "func_8000043C", size = 152 },
  { name = "func_800004D4", size = 108 },
  { name = "func_80000540", size = 200 },
  { name = "func_80000608", size = 436 },
  { name = "func_800007BC", size = 216 },
  { name = "func_80000894", size = 52 },
  { name = "func_800008C8", size = 60 },
  { name = "func_80000904", size = 36 },
  { name = "func_80000928", size = 384 },
  { name = "func_80000AA8", size = 40 },
  { name = "func_800018C4", size = 28 },
  { name = "func_8000F48C", size = 16 },
  { name = "func_8001B9DC", size = 16 },
  { name = "func_8002D948", size = 16 },
  { name = "func_80043DF8", size = 16 },
  { name = "func_80046BD0", size = 32 },
  { name = "func_800837E0", size = 32 },
  { name = "func_80085D34", size = 16 },
  { name = "func_800AD390", size = 32 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
