[input]
entrypoint                = 0x8004B400
elf_path                  = "../hexen/build/hexen.elf"
rom_file_path             = "../hexen/baserom.z64"
output_func_path          = "../hexenpc/RecompiledFuncs"
relocatable_sections_path = "hexen_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_8004B400", size = 80 },
  { name = "func_8004B4AC", size = 148 },
  { name = "func_8004B540", size = 524 },
  { name = "func_8004B74C", size = 148 },
  { name = "func_8004B7E0", size = 212 },
  { name = "func_8004B8B4", size = 396 },
  { name = "func_8004BA40", size = 204 },
  { name = "func_8004BB0C", size = 52 },
  { name = "func_8004BB40", size = 152 },
  { name = "func_8004BBD8", size = 616 },
  { name = "func_8004BE40", size = 84 },
  { name = "func_8004BE94", size = 592 },
  { name = "func_8004C0E4", size = 412 },
  { name = "func_8004C280", size = 200 },
  { name = "func_8004C348", size = 576 },
  { name = "func_8004C588", size = 404 },
  { name = "func_8004C71C", size = 144 },
  { name = "func_8004C7AC", size = 144 },
  { name = "func_8004C83C", size = 72 },
  { name = "func_8004C884", size = 276 },
  { name = "func_8004C998", size = 480 },
  { name = "func_8004CB78", size = 224 },
  { name = "func_8004CC58", size = 208 },
  { name = "func_8004CD28", size = 784 },
  { name = "func_8004D038", size = 64 },
  { name = "func_8004D078", size = 452 },
  { name = "func_8004D23C", size = 452 },
  { name = "func_8004D400", size = 124 },
  { name = "func_8004D47C", size = 144 },
  { name = "func_8004D50C", size = 100 },
  { name = "func_8004D570", size = 116 },
  { name = "func_8004D5E4", size = 32 },
  { name = "func_8004D604", size = 604 },
  { name = "func_8004D860", size = 116 },
  { name = "func_8004D8D4", size = 56 },
  { name = "func_8004D90C", size = 272 },
  { name = "func_8004DA1C", size = 88 },
  { name = "func_8004DA74", size = 24 },
  { name = "func_8004DA8C", size = 140 },
  { name = "func_8004DB18", size = 152 },
  { name = "func_8004DBB0", size = 188 },
  { name = "func_8004DC6C", size = 52 },
  { name = "func_8004DCA0", size = 68 },
  { name = "func_8004DCE4", size = 32 },
  { name = "func_8004DD04", size = 48 },
  { name = "func_8004DD34", size = 88 },
  { name = "func_8004DD8C", size = 84 },
  { name = "func_8004DDE0", size = 608 },
  { name = "func_8004E040", size = 516 },
  { name = "func_8004E244", size = 484 },
  { name = "func_8004E428", size = 152 },
  { name = "func_8004E4C0", size = 764 },
  { name = "func_8004E7BC", size = 12 },
  { name = "func_8004E7C8", size = 88 },
  { name = "func_8004E820", size = 372 },
  { name = "func_8004E994", size = 1104 },
  { name = "func_8004EDE4", size = 204 },
  { name = "func_8004EEB0", size = 192 },
  { name = "func_8004EF70", size = 192 },
  { name = "func_8004F030", size = 76 },
  { name = "func_8004F07C", size = 64 },
  { name = "func_8004F0BC", size = 888 },
  { name = "func_8004F434", size = 1200 },
  { name = "func_8004F8E4", size = 116 },
  { name = "func_8004F958", size = 156 },
  { name = "func_8004F9F4", size = 184 },
  { name = "func_8004FAAC", size = 108 },
  { name = "func_8004FB18", size = 76 },
  { name = "func_8004FB64", size = 148 },
  { name = "func_8004FBF8", size = 116 },
  { name = "func_8004FC6C", size = 188 },
  { name = "func_8004FD28", size = 56 },
  { name = "func_8004FD60", size = 64 },
  { name = "func_8004FDA0", size = 764 },
  { name = "func_8005009C", size = 372 },
  { name = "func_80050210", size = 456 },
  { name = "func_800503D8", size = 64 },
  { name = "func_80050418", size = 408 },
  { name = "func_800505B0", size = 56 },
  { name = "func_800505E8", size = 280 },
  { name = "func_80050700", size = 492 },
  { name = "func_800508EC", size = 52 },
  { name = "func_80050920", size = 700 },
  { name = "func_80050BDC", size = 1300 },
  { name = "func_800510F0", size = 376 },
  { name = "func_80051268", size = 436 },
  { name = "func_8005141C", size = 16 },
  { name = "func_8005142C", size = 76 },
  { name = "func_80051478", size = 24 },
  { name = "func_80051490", size = 8 },
  { name = "func_80051498", size = 192 },
  { name = "func_80051558", size = 200 },
  { name = "func_80051620", size = 28 },
  { name = "func_8005163C", size = 48 },
  { name = "func_8005166C", size = 56 },
  { name = "func_800516A4", size = 60 },
  { name = "func_800516E0", size = 8 },
  { name = "func_800516E8", size = 84 },
  { name = "func_8005173C", size = 12 },
  { name = "func_80051748", size = 24 },
  { name = "func_80051760", size = 12 },
  { name = "func_8005176C", size = 76 },
  { name = "func_800517B8", size = 216 },
  { name = "func_80051890", size = 12 },
  { name = "func_8005189C", size = 8 },
  { name = "func_800518A4", size = 12 },
  { name = "func_800518B0", size = 8 },
  { name = "func_800518B8", size = 84 },
  { name = "func_8005190C", size = 120 },
  { name = "func_80051984", size = 56 },
  { name = "func_800519BC", size = 8 },
  { name = "func_800519C4", size = 12 },
  { name = "func_800519D0", size = 8 },
  { name = "func_800519D8", size = 28 },
  { name = "func_800519F4", size = 40 },
  { name = "func_80051A1C", size = 24 },
  { name = "func_80051A34", size = 48 },
  { name = "func_80051A64", size = 8 },
  { name = "func_80051A6C", size = 8 },
  { name = "func_80051A74", size = 92 },
  { name = "func_80051AD0", size = 24 },
  { name = "func_80051AE8", size = 88 },
  { name = "func_80051B40", size = 84 },
  { name = "func_80051B94", size = 84 },
  { name = "func_80051BE8", size = 24 },
  { name = "func_80051C00", size = 164 },
  { name = "func_80051CA4", size = 80 },
  { name = "func_80051CF4", size = 788 },
  { name = "func_80052008", size = 176 },
  { name = "func_800520B8", size = 392 },
  { name = "func_80052240", size = 112 },
  { name = "func_800522B0", size = 56 },
  { name = "func_800522E8", size = 8 },
  { name = "func_800522F0", size = 240 },
  { name = "func_800523E0", size = 256 },
  { name = "func_800524E0", size = 180 },
  { name = "func_80052594", size = 400 },
  { name = "func_80052724", size = 460 },
  { name = "func_800528F0", size = 56 },
  { name = "func_80052928", size = 40 },
  { name = "func_80052950", size = 40 },
  { name = "func_80052978", size = 136 },
  { name = "func_80052A00", size = 132 },
  { name = "func_80052A84", size = 180 },
  { name = "func_80052B38", size = 180 },
  { name = "func_80052BEC", size = 180 },
  { name = "func_80052CA0", size = 24 },
  { name = "func_80052CB8", size = 12 },
  { name = "func_80052CC4", size = 12 },
  { name = "func_80052CD0", size = 208 },
  { name = "func_80052DA0", size = 272 },
  { name = "func_80052EB0", size = 112 },
  { name = "osInitialize", size = 672 },
  { name = "osCreateThread", size = 336 },
  { name = "osStartThread", size = 336 },
  { name = "osCreatePiManager", size = 400 },
  { name = "osCreateViManager", size = 392 },
  { name = "func_80053778", size = 472 },
  { name = "osSetThreadPri", size = 224 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "osViSetEvent", size = 112 },
  { name = "osSetEventMesg", size = 176 },
  { name = "osViSetMode", size = 112 },
  { name = "osViSwapBuffer", size = 80 },
  { name = "osContSetCh", size = 112 },
  { name = "func_80053CB0", size = 80 },
  { name = "func_80053D00", size = 160 },
  { name = "func_80053DA0", size = 484 },
  { name = "func_80053F84", size = 176 },
  { name = "func_80054034", size = 384 },
  { name = "func_800541B4", size = 556 },
  { name = "func_800543E0", size = 8 },
  { name = "func_800543E8", size = 136 },
  { name = "func_80054470", size = 80 },
  { name = "func_800544C0", size = 304 },
  { name = "osViSetSpecialFeatures", size = 448 },
  { name = "func_800547B0", size = 64 },
  { name = "osWritebackDCache", size = 128 },
  { name = "osInvalICache", size = 128 },
  { name = "osInvalDCache", size = 176 },
  { name = "osContInit", size = 504 },
  { name = "func_80054B98", size = 208 },
  { name = "func_80054C68", size = 248 },
  { name = "osContStartReadData", size = 196 },
  { name = "osContGetReadData", size = 168 },
  { name = "func_80054ECC", size = 244 },
  { name = "osRecvMesg", size = 320 },
  { name = "osPfsIsPlug", size = 404 },
  { name = "func_80055294", size = 224 },
  { name = "func_80055374", size = 188 },
  { name = "osPiStartDma", size = 272 },
  { name = "func_80055540", size = 36 },
  { name = "func_80055564", size = 92 },
  { name = "osSendMesg", size = 336 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "osVirtualToPhysical", size = 128 },
  { name = "func_800557C0", size = 560 },
  { name = "func_800559F0", size = 96 },
  { name = "func_80055A50", size = 340 },
  { name = "func_80055BA4", size = 108 },
  { name = "func_80055C10", size = 696 },
  { name = "func_80055EC8", size = 120 },
  { name = "func_80055F40", size = 72 },
  { name = "func_80055F88", size = 88 },
  { name = "func_80055FE0", size = 96 },
  { name = "func_80056040", size = 96 },
  { name = "func_800560A0", size = 404 },
  { name = "func_80056234", size = 92 },
  { name = "func_80056290", size = 84 },
  { name = "func_800562E4", size = 76 },
  { name = "func_80056330", size = 516 },
  { name = "osPfsInitPak", size = 160 },
  { name = "func_800565D4", size = 220 },
  { name = "func_800566B0", size = 528 },
  { name = "func_800568C0", size = 432 },
  { name = "func_80056A70", size = 304 },
  { name = "func_80056BA0", size = 416 },
  { name = "func_80056D40", size = 1012 },
  { name = "func_80057134", size = 512 },
  { name = "func_80057334", size = 172 },
  { name = "func_800573E0", size = 224 },
  { name = "func_800574C0", size = 880 },
  { name = "func_80057830", size = 640 },
  { name = "func_80057AB0", size = 516 },
  { name = "func_80057CB4", size = 236 },
  { name = "func_80057DA0", size = 688 },
  { name = "func_80058050", size = 248 },
  { name = "func_80058148", size = 136 },
  { name = "func_800581D0", size = 1516 },
  { name = "func_800587BC", size = 740 },
  { name = "func_80058AA0", size = 416 },
  { name = "osAiSetFrequency", size = 352 },
  { name = "func_80058DA0", size = 48 },
  { name = "func_80058DD0", size = 36 },
  { name = "func_80058DF4", size = 56 },
  { name = "func_80058E2C", size = 52 },
  { name = "func_80058E60", size = 96 },
  { name = "osAiSetNextBuffer", size = 176 },
  { name = "osAiGetLength", size = 16 },
  { name = "func_80058F80", size = 8 },
  { name = "func_80058F88", size = 88 },
  { name = "func_80058FE0", size = 56 },
  { name = "func_80059018", size = 96 },
  { name = "func_80059078", size = 24 },
  { name = "func_80059090", size = 48 },
  { name = "func_800590C0", size = 8 },
  { name = "func_800590C8", size = 664 },
  { name = "func_80059360", size = 768 },
  { name = "func_80059660", size = 80 },
  { name = "func_800596B0", size = 232 },
  { name = "func_80059798", size = 328 },
  { name = "func_800598E0", size = 160 },
  { name = "osGetTime", size = 144 },
  { name = "func_80059A10", size = 128 },
  { name = "func_80059A90", size = 144 },
  { name = "func_80059B20", size = 160 },
  { name = "func_80059BC0", size = 144 },
  { name = "func_80059C50", size = 160 },
  { name = "func_80059CF0", size = 144 },
  { name = "func_80059D80", size = 448 },
  { name = "func_80059F40", size = 16 },
  { name = "func_80059F50", size = 16 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_80059F70", size = 80 },
  { name = "func_80059FC0", size = 80 },
  { name = "func_8005A010", size = 16 },
  { name = "func_8005A544", size = 232 },
  { name = "func_8005A62C", size = 256 },
  { name = "func_8005A72C", size = 72 },
  { name = "func_8005A774", size = 16 },
  { name = "func_8005A784", size = 380 },
  { name = "func_8005A910", size = 96 },
  { name = "func_8005A970", size = 96 },
  { name = "func_8005A9D0", size = 44 },
  { name = "__ull_rem", size = 60 },
  { name = "__ull_div", size = 60 },
  { name = "func_8005AA74", size = 44 },
  { name = "func_8005AAA0", size = 60 },
  { name = "__ll_div", size = 92 },
  { name = "__ll_mul", size = 48 },
  { name = "func_8005AB68", size = 96 },
  { name = "func_8005ABC8", size = 156 },
  { name = "func_8005AC64", size = 44 },
  { name = "func_8005AC90", size = 160 },
  { name = "func_8005AD30", size = 80 },
  { name = "func_8005AD80", size = 1764 },
  { name = "func_8005B464", size = 232 },
  { name = "func_8005B54C", size = 244 },
  { name = "__osDisableInt", size = 32 },
  { name = "__osRestoreInt", size = 32 },
  { name = "func_8005B680", size = 64 },
  { name = "func_8005B6C0", size = 80 },
  { name = "func_8005B710", size = 68 },
  { name = "func_8005B754", size = 44 },
  { name = "osGetThreadPri", size = 32 },
  { name = "func_8005B7A0", size = 224 },
  { name = "func_8005B880", size = 224 },
  { name = "func_8005B960", size = 944 },
  { name = "func_8005BD10", size = 140 },
  { name = "func_8005BD9C", size = 376 },
  { name = "func_8005BF14", size = 116 },
  { name = "func_8005BF88", size = 392 },
  { name = "func_8005C110", size = 336 },
  { name = "func_8005C260", size = 16 },
  { name = "func_8005C270", size = 864 },
  { name = "osGetCount", size = 16 },
  { name = "func_8005C5E0", size = 80 },
  { name = "func_8005C630", size = 68 },
  { name = "func_8005C674", size = 44 },
  { name = "osViBlack", size = 112 },
  { name = "osSetIntMask", size = 160 },
  { name = "osSpTaskYielded", size = 128 },
  { name = "osViGetNextFramebuffer", size = 64 },
  { name = "osViGetCurrentFramebuffer", size = 64 },
  { name = "func_8005C8B0", size = 268 },
  { name = "osSpTaskLoad", size = 360 },
  { name = "osSpTaskStartGo", size = 76 },
  { name = "osDpSetNextBuffer", size = 176 },
  { name = "func_8005CC20", size = 32 },
  { name = "osSetTimer", size = 224 },
  { name = "func_8005CD20", size = 176 },
  { name = "osJamMesg", size = 336 },
  { name = "func_8005CF20", size = 48 },
  { name = "func_8005CF50", size = 1648 },
  { name = "func_8005D5C0", size = 1616 },
  { name = "func_8005DC10", size = 44 },
  { name = "func_8005DC3C", size = 40 },
  { name = "func_8005DC64", size = 76 },
  { name = "func_8005DCB0", size = 192 },
  { name = "func_8005DD70", size = 256 },
  { name = "func_8005DE70", size = 136 },
  { name = "func_8005DEF8", size = 48 },
  { name = "func_8005DF28", size = 184 },
  { name = "func_8005DFE0", size = 368 },
  { name = "func_8005E150", size = 16 },
  { name = "func_8005E160", size = 160 },
  { name = "func_8005E200", size = 368 },
  { name = "func_8005E370", size = 144 },
  { name = "func_8005E400", size = 124 },
  { name = "func_8005E47C", size = 252 },
  { name = "func_8005E578", size = 844 },
  { name = "func_8005E8C4", size = 356 },
  { name = "func_8005EA28", size = 516 },
  { name = "func_8005EC2C", size = 280 },
  { name = "func_8005ED44", size = 668 },
  { name = "func_8005EFE0", size = 112 },
  { name = "osEepromRead", size = 532 },
  { name = "func_8005F264", size = 348 },
  { name = "func_8005F3C0", size = 508 },
  { name = "func_8005F5BC", size = 372 },
  { name = "func_8005F730", size = 16 },
  { name = "func_8005F740", size = 48 },
  { name = "func_8005F770", size = 68 },
  { name = "func_8005F7B4", size = 84 },
  { name = "func_8005F808", size = 84 },
  { name = "func_8005F85C", size = 136 },
  { name = "func_8005F8E4", size = 168 },
  { name = "func_8005F98C", size = 164 },
  { name = "func_8005FA30", size = 160 },
  { name = "func_8005FAD0", size = 1088 },
  { name = "func_8005FF10", size = 160 },
  { name = "func_8005FFB0", size = 48 },
  { name = "func_8005FFE0", size = 288 },
  { name = "func_80060100", size = 468 },
  { name = "func_800602D4", size = 940 },
  { name = "func_80060680", size = 300 },
  { name = "func_800607AC", size = 1188 },
  { name = "func_80060C50", size = 236 },
  { name = "func_80060D3C", size = 532 },
  { name = "func_80060F50", size = 40 },
  { name = "func_80060F78", size = 236 },
  { name = "func_80061064", size = 224 },
  { name = "func_80061144", size = 464 },
  { name = "func_80061314", size = 664 },
  { name = "func_800615AC", size = 176 },
  { name = "func_8006165C", size = 1364 },
  { name = "func_80061BB0", size = 48 },
  { name = "func_80061BE0", size = 224 },
  { name = "func_80061CC0", size = 52 },
  { name = "func_80061CF4", size = 140 },
  { name = "func_80061D80", size = 48 },
  { name = "osDestroyThread", size = 256 },
  { name = "func_80061EB0", size = 240 },
  { name = "func_80061FA0", size = 96 },
  { name = "func_80062000", size = 80 },
  { name = "func_80062050", size = 80 },
  { name = "func_800620A0", size = 16 },
  { name = "func_800620B0", size = 16 },
  { name = "func_800620C0", size = 784 },
  { name = "func_800623D0", size = 16 },
  { name = "__osSpSetPc", size = 64 },
  { name = "func_80062420", size = 144 },
  { name = "func_800624B0", size = 48 },
  { name = "func_800624E0", size = 48 },
  { name = "func_80062510", size = 672 },
  { name = "func_800627B0", size = 1392 },
  { name = "func_80062D20", size = 1360 },
  { name = "func_80063270", size = 176 },
  { name = "func_80063320", size = 208 },
  { name = "func_800633F0", size = 32 },
  { name = "func_80063410", size = 168 },
  { name = "func_800634B8", size = 184 },
  { name = "func_80063570", size = 392 },
  { name = "func_800636F8", size = 396 },
  { name = "func_80063884", size = 548 },
  { name = "func_80063AA8", size = 604 },
  { name = "func_80063D04", size = 24 },
  { name = "func_80063D1C", size = 836 },
  { name = "func_80064060", size = 128 },
  { name = "func_800640E0", size = 256 },
  { name = "func_800641E0", size = 144 },
  { name = "func_80064270", size = 700 },
  { name = "func_8006452C", size = 152 },
  { name = "func_800645C4", size = 1820 },
  { name = "func_80064CE0", size = 272 },
  { name = "func_80064DF0", size = 108 },
  { name = "func_80064E5C", size = 180 },
  { name = "func_80064F10", size = 128 },
  { name = "func_8006B5C0", size = 124 },
  { name = "func_8006B63C", size = 276 },
  { name = "func_8006BD40", size = 2616 },
  { name = "func_80077D00", size = 16 },
  { name = "func_80077DC0", size = 32 },
  { name = "func_80077DE0", size = 16 },
  { name = "func_80077DF0", size = 16 },
  { name = "func_80077E80", size = 16 },
  { name = "func_80078020", size = 16 },
  { name = "func_8007DBDC", size = 32 },
  { name = "func_8007DBFC", size = 32 },
  { name = "func_8007DC1C", size = 12 },
  { name = "func_8007DC28", size = 484 },
  { name = "func_8007DE0C", size = 460 },
  { name = "func_8007E050", size = 32 },
  { name = "func_8007E070", size = 80 },
  { name = "func_8007E0C0", size = 7960 },
  { name = "func_80082280", size = 4 },
  { name = "func_80085448", size = 16 },
  { name = "func_80085B14", size = 4 },
  { name = "func_80089620", size = 128 },
  { name = "func_80089D58", size = 48 },
  { name = "func_800A7A64", size = 80 },
  { name = "func_800CBFE0", size = 16 },
  { name = "func_8012D6E0", size = 48 },
]

exact_size_funcs = [

]

[patches]
stubs = [
  "func_8012D6E0",
]
