/**
 * main.cpp — Star Wars Shadows of the Empire PC port entry point. Generated by recompilator/scaffold_app.py.
 *
 * The MINIMAL game profile (the sm64pc/lodpc pattern): ROM identity/validation,
 * recompiled-section registration, renderer/audio/input wiring, the entrypoint, a
 * crash handler, and diagnostic logging. Every game-specific value below comes from
 * recon (ROM header, XXH3, entrypoint) — there are NO addresses from any other game.
 *
 * Engine: ../engine (the single agnostic engine: rt64 + runtime). Cross-platform by
 * construction — Windows / Linux / macOS / Linux-ARM. Pick a target with the
 * CMakePresets in this directory (e.g. `cmake --preset linux-arm64`). Keep this file free
 * of throwaway debug probes; put those behind an env var in the engine, or a local edit.
 */

#if defined(_WIN32)
#include <Windows.h>
#include <commdlg.h>   // OPENFILENAMEA / GetOpenFileNameA
#endif
#include <string>
#include <filesystem>
#include <cstdlib>
#include <cstdio>
#include <atomic>

#define SDL_MAIN_HANDLED
#include "SDL.h"
#include "SDL_syswm.h"

#include "recomp.h"
#include "librecomp/game.hpp"
#include "librecomp/overlays.hpp"
#include "librecomp/diag_cap.h"   // console seam ported from snowkidspc (2026-07-31 batch)
#include "librecomp/sections.h"
#include "ultramodern/ultramodern.hpp"
#include "ultramodern/renderer_context.hpp"
#include "ultramodern/error_handling.hpp"

#ifndef RDPC_CONSOLE_ONLY
#include "rt64_renderer.hpp"
#endif

ultramodern::audio_callbacks_t    get_audio_callbacks();
ultramodern::input::callbacks_t   get_input_callbacks();
recomp::rsp::callbacks_t          get_rsp_callbacks();
void shadows_audio_init();
void shadows_input_init();

// ── Star Wars Shadows of the Empire game identity (recon: ROM header + XXH3) ───────────────────────
// SHA1: 271c285f6e5069133ab27a2a8324d4651591e35d · internal name "Star Wars Shadows of the Empire"
static constexpr uint64_t SHADOWS_ROM_HASH        = 0xF6EC015C003FC799ULL;
static constexpr uint32_t SHADOWS_ENTRYPOINT_VRAM = 0x80000400;

extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);

#include "recomp_overlays.inl"
#include "ram_shadow_pins.inl"   // phase-2 static set (shadows_ram; merge_recomp_sets.py) — call before recomp::start
extern "C" void recomp_baremetal_set_svc_poster(void (*)(uint8_t*, recomp_context*), uint32_t);   // [hverify-direct]

// console seam ported from snowkidspc (2026-07-31 batch)
#ifdef RDPC_CAPTURE_CHAIN
#include "lle_console.h"   // preservation-core console renderer (RDPC_LLE_CONSOLE=1) + blit_tick
#include "console_input.h" // the evdev input organ -- lets console mode run with no SDL video at all
#endif

static SDL_Window* sdl_window = nullptr;
extern std::atomic<double> g_cv64_present_fps;   // present-FPS counter (engine global)

// Cross-platform error dialog: native MessageBox on Windows, SDL elsewhere.
static void shadows_show_error(const char* title, const char* msg) {
#if defined(_WIN32)
    MessageBoxA(nullptr, msg, title, MB_ICONERROR | MB_OK);
#else
    SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, title, msg, nullptr);
#endif
}

static ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
// console seam ported from snowkidspc (2026-07-31 batch)
#ifdef RDPC_CONSOLE_ONLY
    // THE CONSOLE CONTRACT (2026-07-25). SDL video was kept alive here for exactly one
    // reason: SDL's keyboard and gamepad state ride the video backend, so skipping it
    // starved input (the 07-24 lesson). The cost was DRM master -- which the presentation
    // organ needs to own the mode and the scanout. preservation_core::input reads
    // controllers straight from the kernel, so that dependency is gone: when the organ
    // comes up, SDL video is never initialised and DRM master is free to take.
    if (preservation_core::input::init()) {
        // GPU-present tier (repc 4K: GPU upscale via SDL_Renderer) still needs SDL video even
        // though the evdev organ owns input -- only the organ-scanout path frees DRM master.
        const char* gp = std::getenv("RDPC_LLE_GPU_PRESENT");
        if (gp == nullptr || gp[0] != (char)49) {
            return nullptr;
        }
    }
    fprintf(stderr, "[console] input organ opened no devices -- keeping SDL video so input still works\n");
#endif
    if (SDL_InitSubSystem(SDL_INIT_VIDEO) != 0) {
        shadows_show_error("SDL_InitSubSystem Error", SDL_GetError());
    }
    return nullptr;
}

static ultramodern::renderer::WindowHandle
create_window(ultramodern::gfx_callbacks_t::gfx_data_t /*gfx_data*/)
{
// console seam ported from snowkidspc (2026-07-31 batch)
#ifdef RDPC_CONSOLE_ONLY
    // Organ up => no SDL video => no window to create. The presentation organ scans out
    // directly. Window consumers are already null-safe (blit_tick early-returns; the FPS
    // title is guarded on a non-null window).
    if (preservation_core::input::active()) {
        const char* gp = std::getenv("RDPC_LLE_GPU_PRESENT");   // GPU tier keeps its window
        if (gp == nullptr || gp[0] != (char)49) {
            return nullptr;
        }
    }
#endif
    Uint32 win_flags = SDL_WINDOW_RESIZABLE;
#if !defined(_WIN32)
    win_flags |= SDL_WINDOW_VULKAN;   // Linux + macOS (MoltenVK) render via Vulkan
#endif
#ifdef RDPC_CAPTURE_CHAIN
    if (preservation_core::lleconsole::active()) {
        // Console mode (RDPC_LLE_CONSOLE=1): no Vulkan window; GL only for the accelerated
        // upscale presenter (RDPC_LLE_GPU_PRESENT=1). Ported verbatim from starfox64pc (game #6).
        win_flags = SDL_WINDOW_RESIZABLE;
        if (const char* fs = std::getenv("RDPC_LLE_FULLSCREEN"); fs && fs[0] == '1')
            win_flags |= SDL_WINDOW_FULLSCREEN_DESKTOP;
        if (const char* gp = std::getenv("RDPC_LLE_GPU_PRESENT"); gp && gp[0] == '1')
            win_flags |= SDL_WINDOW_OPENGL;
    }
#endif
    sdl_window = SDL_CreateWindow(
        "Star Wars Shadows of the Empire PC",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        1920, 1080,
        win_flags);
    if (!sdl_window) {
        shadows_show_error("Window Creation Error", SDL_GetError());
        std::exit(1);
    }

#if defined(_WIN32)
    SDL_SysWMinfo wm_info;
    SDL_VERSION(&wm_info.version);
    SDL_GetWindowWMInfo(sdl_window, &wm_info);
    return ultramodern::renderer::WindowHandle{
        wm_info.info.win.window,
        GetCurrentThreadId()
    };
#elif defined(__APPLE__)
    SDL_SysWMinfo wm_info;
    SDL_VERSION(&wm_info.version);
    SDL_GetWindowWMInfo(sdl_window, &wm_info);
    SDL_MetalView mv = SDL_Metal_CreateView(sdl_window);   // CAMetalLayer-backed view for MoltenVK
    return ultramodern::renderer::WindowHandle{ wm_info.info.cocoa.window, SDL_Metal_GetLayer(mv) };
#else
    return sdl_window;   // ultramodern::renderer::WindowHandle == SDL_Window* on Linux/Android
#endif
}

static void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t /*gfx_data*/) {
    SDL_Event evt;
    while (SDL_PollEvent(&evt)) {
        if (evt.type == SDL_QUIT) {
            ultramodern::quit();
        }
    }
// console seam ported from snowkidspc (2026-07-31 batch)
#ifdef RDPC_CAPTURE_CHAIN
    // Console mode: present the latest VI frame from the preservation core (owner thread).
    preservation_core::lleconsole::blit_tick(sdl_window);
#endif
    {
        static double last_fps = -1.0;
        double fps = g_cv64_present_fps.load(std::memory_order_relaxed);
        if (sdl_window != nullptr && fps != last_fps) {
            last_fps = fps;
            char title[80];
            snprintf(title, sizeof(title), "Star Wars Shadows of the Empire PC  -  %.1f FPS", fps);
            SDL_SetWindowTitle(sdl_window, title);
        }
    }
}

static void shadows_message_box(const char* msg) {
    shadows_show_error("Star Wars Shadows of the Empire — Error", msg);
}

// console seam ported from snowkidspc (2026-07-31 batch)
static std::unique_ptr<ultramodern::renderer::RendererContext>
shadows_create_render_context(uint8_t* rdram, ultramodern::renderer::WindowHandle window_handle, bool developer_mode) {
#ifdef RDPC_CAPTURE_CHAIN
    // Console mode (RDPC_LLE_CONSOLE=1): the preservation-core console replaces RT64 entirely.
    if (preservation_core::lleconsole::active()) {
        // Game-agnostic submit seam (organ Move 1): register before the first send_dl.
        extern void shadows_lle_console_submit();
        preservation_core::lleconsole::set_submit_callback(&shadows_lle_console_submit);
        return preservation_core::lleconsole::create_console_context(rdram);
    }
#endif
#ifdef RDPC_CONSOLE_ONLY
    // PLAN V3 amendment A: no RT64 in this binary. Console mode is the only renderer.
    shadows_show_error("Renderer", "Console-only build: set RDPC_LLE_CONSOLE=1.");
    std::exit(1);
#else
    return shadows::renderer::create_render_context(rdram, window_handle, developer_mode);
#endif
}

#if defined(_WIN32)
static LONG WINAPI shadows_unhandled_exception(EXCEPTION_POINTERS* ep) {
    fflush(stderr);
    DWORD  code = ep->ExceptionRecord->ExceptionCode;
    void*  addr = ep->ExceptionRecord->ExceptionAddress;
    ULONG_PTR* info = ep->ExceptionRecord->ExceptionInformation;
    HMODULE hmod = nullptr;
    GetModuleHandleExA(
        GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
        GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
        (LPCSTR)addr, &hmod);
    ULONG_PTR rva = hmod ? (ULONG_PTR)addr - (ULONG_PTR)hmod : 0;
    char detail[64] = "";
    if (code == EXCEPTION_ACCESS_VIOLATION && ep->ExceptionRecord->NumberParameters >= 2) {
        snprintf(detail, sizeof(detail), "\nAccess: %s 0x%llX",
            info[0] == 0 ? "READ" : "WRITE", (unsigned long long)info[1]);
    }
    char msg[1024];
    snprintf(msg, sizeof(msg),
        "UNHANDLED EXCEPTION\n\nCode:        0x%08X\nAddress:     0x%p\n"
        "RVA (map):   0x%08llX%s\n\nThis offset matches a line in shadowspc.map.\n"
        "Compare Address against the exe base BEFORE map lookups.\n\nThread: %u",
        code, addr, (unsigned long long)rva, detail, GetCurrentThreadId());
    fprintf(stderr, "%s\n", msg);
    fflush(stderr);
    __try {
        HMODULE exe = GetModuleHandleA(nullptr);
        CONTEXT* ctx = ep->ContextRecord;
        if (exe != nullptr && ctx != nullptr) {
            const uintptr_t* sp = (const uintptr_t*)ctx->Rsp;
            fprintf(stderr, "[crashstack] Rsp=0x%p — call sites in shadowspc.exe (base=0x%p), nearest first:\n",
                    (void*)ctx->Rsp, (void*)exe);
            int found = 0;
            for (int i = 0; i < 128 && found < 16; i++) {
                uintptr_t ret = sp[i];
                HMODULE m = nullptr;
                if (GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                                       GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                                       (LPCSTR)ret, &m) && m == exe) {
                    fprintf(stderr, "[crashstack]   stack+0x%03X  RVA=0x%08llX\n",
                            (unsigned)(i * 8), (unsigned long long)(ret - (uintptr_t)exe));
                    found++;
                }
            }
            fprintf(stderr, "[crashstack] (%d call sites found)\n", found);
            fflush(stderr);
        }
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        fprintf(stderr, "[crashstack] (stack scan faulted — Rsp corrupt)\n"); fflush(stderr);
    }
    MessageBoxA(nullptr, msg, "Star Wars Shadows of the Empire — Crash", MB_ICONERROR | MB_OK);
    return EXCEPTION_CONTINUE_SEARCH;
}
#endif // _WIN32 (crash handler)

static void shadows_vi_callback() {}
static void shadows_gfx_init_callback() {}

static std::string shadows_get_thread_name(const OSThread* t) {
    return "shadows_" + std::to_string(t->id);
}

static void prompt_for_rom(const char* rom_hint) {
    std::filesystem::path rom_path;

#if defined(_WIN32)
    if (rom_hint && *rom_hint) {
        rom_path = rom_hint;
    } else {
        OPENFILENAMEA ofn   = {};
        char          path[MAX_PATH] = {};
        ofn.lStructSize = sizeof(ofn);
        ofn.lpstrFilter = "N64 ROM Files\0*.z64;*.n64;*.v64\0All Files\0*.*\0";
        ofn.lpstrFile   = path;
        ofn.nMaxFile    = MAX_PATH;
        ofn.lpstrTitle  = "Select Star Wars Shadows of the Empire ROM";
        ofn.Flags       = OFN_FILEMUSTEXIST | OFN_PATHMUSTEXIST;
        if (!GetOpenFileNameA(&ofn)) {
            shadows_show_error("ROM Required",
                "A Star Wars Shadows of the Empire ROM is required.\n"
                "Please supply your own legally obtained copy.");
            std::exit(0);
        }
        rom_path = path;
    }
#else
    // No native file dialog wired off Windows: take the ROM path from argv[1] or the
    // SHADOWS_ROM env var (e.g. an SBC/console that already has the ROM at a known path).
    if (!rom_hint || !*rom_hint) rom_hint = std::getenv("SHADOWS_ROM");
    if (!rom_hint || !*rom_hint) {
        shadows_show_error("ROM Required",
            "Pass the Star Wars Shadows of the Empire ROM path as the first argument,\n"
            "or set the SHADOWS_ROM environment variable.");
        std::exit(0);
    }
    rom_path = rom_hint;
#endif

    std::u8string out_id = u8"shadows_us";
    auto err = recomp::select_rom(rom_path, out_id);
    switch (err) {
    case recomp::RomValidationError::Good:
        return;
    case recomp::RomValidationError::IncorrectRom:
    case recomp::RomValidationError::IncorrectVersion:
        shadows_show_error("Wrong ROM",
            "The selected ROM does not match Star Wars Shadows of the Empire.\n"
            "Expected SHA1: 271c285f6e5069133ab27a2a8324d4651591e35d");
        std::exit(1);
    case recomp::RomValidationError::NotARom:
        shadows_show_error("Not an N64 ROM", "The selected file does not appear to be an N64 ROM.");
        std::exit(1);
    default:
        shadows_show_error("ROM Error", "Failed to read the selected ROM file.");
        std::exit(1);
    }
}

static int shadows_app_main(int argc, char** argv)
{
    const char* rom_hint = (argc > 1) ? argv[1] : nullptr;

#if defined(_WIN32)
    SetUnhandledExceptionFilter(shadows_unhandled_exception);
#endif
    SDL_SetMainReady();

#if defined(_WIN32)
    const char* appdata = std::getenv("APPDATA");
    if (!appdata) appdata = ".";
    std::filesystem::path config_path = std::filesystem::path(appdata) / "shadowspc";
#else
    const char* xdg  = std::getenv("XDG_CONFIG_HOME");
    const char* home = std::getenv("HOME");
    std::filesystem::path config_base =
        (xdg && *xdg) ? std::filesystem::path(xdg)
                      : (home ? std::filesystem::path(home) / ".config"
                              : std::filesystem::path("."));
    std::filesystem::path config_path = config_base / "shadowspc";
#endif
    std::filesystem::create_directories(config_path);

    {
        std::filesystem::path log_path = config_path / "shadowspc_diag.log";
        FILE* f = nullptr;
#if defined(_WIN32)
        freopen_s(&f, log_path.string().c_str(), "w", stderr);
#else
        f = freopen(log_path.string().c_str(), "w", stderr);
#endif
        if (f) { setvbuf(f, nullptr, _IONBF, 0); fprintf(stderr, "[shadowspc] diagnostic log started\n"); }
        recomp::diag_log_cap(log_path.string());   // console seam ported from snowkidspc (2026-07-31 batch)
        std::filesystem::path stdout_path = config_path / "shadowspc_stdout.log";
        FILE* fout = nullptr;
#if defined(_WIN32)
        freopen_s(&fout, stdout_path.string().c_str(), "w", stdout);
#else
        fout = freopen(stdout_path.string().c_str(), "w", stdout);
#endif
        if (fout) { setvbuf(fout, nullptr, _IONBF, 0); fprintf(stdout, "[shadowspc] stdout log started\n"); }
    }

    recomp::register_config_path(config_path);

    recomp::GameEntry entry{};
    entry.rom_hash           = SHADOWS_ROM_HASH;
    entry.internal_name      = "Star Wars Shadows of the Empire";
    entry.game_id            = u8"shadows_us";
    entry.mod_game_id        = "";
    entry.save_type          = recomp::SaveType::Eep4k;
    entry.is_enabled         = true;
    entry.entrypoint_address = SHADOWS_ENTRYPOINT_VRAM;
    entry.entrypoint         = recomp_entrypoint;
    recomp::register_game(entry);

    recomp::overlays::register_overlays(
        recomp::overlays::overlay_section_table_data_t{
            .code_sections      = section_table,
            .num_code_sections  = sizeof(section_table) / sizeof(section_table[0]),
            .total_num_sections = num_sections,
        },
        recomp::overlays::overlays_by_index_t{
            .table = overlay_sections_by_index,
            .len   = sizeof(overlay_sections_by_index) / sizeof(overlay_sections_by_index[0]),
        });

    recomp::check_all_stored_roms();
    std::u8string game_id = u8"shadows_us";
    if (!recomp::is_rom_valid(game_id)) {
        prompt_for_rom(rom_hint);
        recomp::check_all_stored_roms();
        if (!recomp::is_rom_valid(game_id)) {
            shadows_show_error("Error", "ROM validation failed after selection.");
            return 1;
        }
    }

    SDL_Init(SDL_INIT_AUDIO);
    shadows_audio_init();
    shadows_input_init();

    recomp::start_game(game_id);

    recomp::Configuration cfg{};
    cfg.project_version      = { 0, 1, 0, "" };
    cfg.rsp_callbacks        = get_rsp_callbacks();
    cfg.renderer_callbacks   = { .create_render_context = shadows_create_render_context };   // console seam ported from snowkidspc (2026-07-31 batch)
    cfg.audio_callbacks      = get_audio_callbacks();
    cfg.input_callbacks      = get_input_callbacks();
    cfg.gfx_callbacks        = {
        .create_gfx    = create_gfx,
        .create_window = create_window,
        .update_gfx    = update_gfx,
    };
    cfg.events_callbacks     = {
        .vi_callback       = shadows_vi_callback,
        .gfx_init_callback = shadows_gfx_init_callback,
    };
    cfg.error_handling_callbacks = { .message_box = shadows_message_box };
    cfg.threads_callbacks    = { .get_game_thread_name = shadows_get_thread_name };
    cfg.message_queue_control = {
        .requeue_timer = true,
        .requeue_sp    = true,
        .requeue_si    = true,
        .requeue_ai    = false,
        .requeue_vi    = false,
        .requeue_pi    = false,
        .requeue_dp    = true,
    };

    // [hverify-direct 2026-08-26] Hand the engine SOTE's kernel ISR post routine
    // (static_6_800C3D08, declared via recomp_overlays.inl -> funcs.h). When the phase-2 unpack
    // stomps the handler's code but leaves its service table (0x80193690) intact, the engine's
    // hold path delivers held interrupts by calling this poster directly (a0 = code*8) — the
    // exact call the stomped dispatch case would have made. Registration is inert unless
    // RECOMP_HANDLER_VERIFY=1 + RECOMP_HVERIFY_DIRECT=1 arm the lane.
    register_ram_shadow_pins();   // phase-2 funcs -> pinned (win inside RECOMP_JIT_RANGE)
    recomp_baremetal_set_svc_poster(static_6_800C3D08, 0x80193690u);

    recomp::start(cfg);

    SDL_Quit();
    return 0;
}

// ── Entry point: GUI WinMain on Windows, standard main() on Linux/macOS ────────
#if defined(_WIN32)
int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int) {
    return shadows_app_main(__argc, __argv);   // CRT-provided argc/argv
}
#else
int main(int argc, char** argv) {
    return shadows_app_main(argc, argv);
}
#endif
