/**
 * main.cpp — LODPC entry point (Castlevania: Legacy of Darkness, USA).
 *
 * SESSION 44: the MINIMAL game profile — deliberately none of cv64pc's
 * game-specific patches (no mapOverlay HLE, no pinned functions, no NI catalog
 * reload, no watchpoints). What remains is exactly what any game needs:
 * ROM identity/validation, recompiled-section registration, renderer/audio/
 * input wiring, the entrypoint, a crash handler, and diagnostic logging.
 * Everything LoD-specific below was derived by recon (ROM header, XXH3 of the
 * ROM, entrypoint from the header) — no CV64 addresses copied.
 *
 * Lifecycle (librecomp): register_config_path / register_game /
 * register_overlays → validate ROM → start_game(id) → start(cfg) [blocks].
 */

#include <Windows.h>
#include <commdlg.h>   // OPENFILENAMEA / GetOpenFileNameA
#include <string>
#include <filesystem>
#include <cstdlib>
#include <cstdio>
#include <atomic>

// Prevent SDL from #define-ing main→SDL_main (funcs.h declares the game's main).
#define SDL_MAIN_HANDLED
#include "SDL.h"
#include "SDL_syswm.h"

#include "recomp.h"
#include "librecomp/game.hpp"
#include "librecomp/overlays.hpp"
#include "librecomp/sections.h"
#include "ultramodern/ultramodern.hpp"
#include "ultramodern/renderer_context.hpp"
#include "ultramodern/error_handling.hpp"

#include "rt64_renderer.hpp"

// ── Callback providers ────────────────────────────────────────────────────────
ultramodern::audio_callbacks_t    get_audio_callbacks();
ultramodern::input::callbacks_t   get_input_callbacks();
recomp::rsp::callbacks_t          get_rsp_callbacks();
void lod_audio_init();
void lod_input_init();

// ── LoD game identity (recon: ROM header + hashes, SESSION 44) ───────────────
// XXH3_64bits of Castlevania: Legacy of Darkness (USA) baserom.z64
// SHA1: 879ead98f197fd05edda867655da5b1ce25aa5b8 · internal name CASTLEVANIA2 · ND4E
static constexpr uint64_t LOD_ROM_HASH        = 0x0BF827D4AC27A631ULL;
static constexpr uint32_t LOD_ENTRYPOINT_VRAM = 0x80000400;

// The game's entry point, generated by N64Recomp.
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);

// ── Recompiled section table — generated by N64Recomp ────────────────────────
#include "recomp_overlays.inl"

// ── SDL2 state ────────────────────────────────────────────────────────────────
static SDL_Window* sdl_window = nullptr;

// Presented-FPS published by the runtime (ultramodern events.cpp) once/sec.
// (Engine-side global; the cv64_ prefix is its engine name, not a CV64 dependency.)
extern std::atomic<double> g_cv64_present_fps;

// ── GFX callbacks ─────────────────────────────────────────────────────────────
static ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
    if (SDL_InitSubSystem(SDL_INIT_VIDEO) != 0) {
        MessageBoxA(nullptr, SDL_GetError(), "SDL_InitSubSystem Error", MB_ICONERROR);
    }
    return nullptr;
}

static ultramodern::renderer::WindowHandle
create_window(ultramodern::gfx_callbacks_t::gfx_data_t /*gfx_data*/)
{
    sdl_window = SDL_CreateWindow(
        "Castlevania: Legacy of Darkness PC",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        1920, 1080,
        SDL_WINDOW_RESIZABLE);

    if (!sdl_window) {
        MessageBoxA(nullptr, SDL_GetError(), "Window Creation Error", MB_ICONERROR);
        std::exit(1);
    }

    SDL_SysWMinfo wm_info;
    SDL_VERSION(&wm_info.version);
    SDL_GetWindowWMInfo(sdl_window, &wm_info);

    return ultramodern::renderer::WindowHandle{
        wm_info.info.win.window,
        GetCurrentThreadId()
    };
}

static void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t /*gfx_data*/) {
    // Pump the SDL/Windows message queue every tick. CRITICAL: this runs on the
    // main thread (which owns the HWND); RT64's D3D12 Present() blocks if the
    // owning thread's message queue is not drained.
    SDL_Event evt;
    while (SDL_PollEvent(&evt)) {
        if (evt.type == SDL_QUIT) {
            ultramodern::quit();
        }
    }

    // Window-title FPS readout (engine-published once/sec).
    {
        static double last_fps = -1.0;
        double fps = g_cv64_present_fps.load(std::memory_order_relaxed);
        if (sdl_window != nullptr && fps != last_fps) {
            last_fps = fps;
            char title[80];
            snprintf(title, sizeof(title), "Castlevania: Legacy of Darkness PC  -  %.1f FPS", fps);
            SDL_SetWindowTitle(sdl_window, title);
        }
    }
}

// ── Error handling ────────────────────────────────────────────────────────────
static void lod_message_box(const char* msg) {
    MessageBoxA(nullptr, msg, "LODPC Error", MB_ICONERROR | MB_OK);
}

// Unhandled exception filter — crash address + RVA (lodpc.map lookup) + the
// [crashstack] return-address scan (cv64pc cont.30 tool, game-agnostic).
static LONG WINAPI lod_unhandled_exception(EXCEPTION_POINTERS* ep) {
    fflush(stderr);

    DWORD  code = ep->ExceptionRecord->ExceptionCode;
    void*  addr = ep->ExceptionRecord->ExceptionAddress;
    ULONG_PTR* info = ep->ExceptionRecord->ExceptionInformation;

    HMODULE hmod = nullptr;
    GetModuleHandleExA(
        GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
        GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
        (LPCSTR)addr, &hmod);
    ULONG_PTR rva = hmod ? (ULONG_PTR)addr - (ULONG_PTR)hmod : 0;

    char detail[64] = "";
    if (code == EXCEPTION_ACCESS_VIOLATION && ep->ExceptionRecord->NumberParameters >= 2) {
        snprintf(detail, sizeof(detail),
            "\nAccess: %s 0x%llX",
            info[0] == 0 ? "READ" : "WRITE",
            (unsigned long long)info[1]);
    }

    char msg[1024];
    snprintf(msg, sizeof(msg),
        "UNHANDLED EXCEPTION\n\n"
        "Code:        0x%08X\n"
        "Address:     0x%p\n"
        "RVA (map):   0x%08llX%s\n\n"
        "This offset matches a line in lodpc.map.\n"
        "Compare Address against the exe base BEFORE map lookups.\n\n"
        "Thread: %u",
        code, addr, (unsigned long long)rva, detail,
        GetCurrentThreadId());

    fprintf(stderr, "%s\n", msg);
    fflush(stderr);

    __try {
        HMODULE exe = GetModuleHandleA(nullptr);
        CONTEXT* ctx = ep->ContextRecord;
        if (exe != nullptr && ctx != nullptr) {
            const uintptr_t* sp = (const uintptr_t*)ctx->Rsp;
            fprintf(stderr, "[crashstack] Rsp=0x%p — call sites in lodpc.exe (base=0x%p), nearest first:\n",
                    (void*)ctx->Rsp, (void*)exe);
            int found = 0;
            for (int i = 0; i < 128 && found < 16; i++) {
                uintptr_t ret = sp[i];
                HMODULE m = nullptr;
                if (GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                                       GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                                       (LPCSTR)ret, &m) && m == exe) {
                    fprintf(stderr, "[crashstack]   stack+0x%03X  RVA=0x%08llX\n",
                            (unsigned)(i * 8), (unsigned long long)(ret - (uintptr_t)exe));
                    found++;
                }
            }
            fprintf(stderr, "[crashstack] (%d call sites found)\n", found);
            fflush(stderr);
        }
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        fprintf(stderr, "[crashstack] (stack scan faulted — Rsp corrupt)\n"); fflush(stderr);
    }

    MessageBoxA(nullptr, msg, "LODPC — Crash", MB_ICONERROR | MB_OK);

    return EXCEPTION_CONTINUE_SEARCH;
}

// ── Events ────────────────────────────────────────────────────────────────────
static void lod_vi_callback() {}
static void lod_gfx_init_callback() {}

// ── Thread naming ─────────────────────────────────────────────────────────────
static std::string lod_get_thread_name(const OSThread* t) {
    return "lod_" + std::to_string(t->id);
}

// ── ROM picker (first run) ────────────────────────────────────────────────────
static void prompt_for_rom() {
    OPENFILENAMEA ofn   = {};
    char          path[MAX_PATH] = {};
    ofn.lStructSize = sizeof(ofn);
    ofn.lpstrFilter = "N64 ROM Files\0*.z64;*.n64;*.v64\0All Files\0*.*\0";
    ofn.lpstrFile   = path;
    ofn.nMaxFile    = MAX_PATH;
    ofn.lpstrTitle  = "Select Castlevania: Legacy of Darkness ROM (USA)";
    ofn.Flags       = OFN_FILEMUSTEXIST | OFN_PATHMUSTEXIST;

    if (!GetOpenFileNameA(&ofn)) {
        MessageBoxA(nullptr,
            "A Castlevania: Legacy of Darkness ROM is required.\n"
            "Please supply your own legally obtained copy.",
            "ROM Required", MB_ICONINFORMATION);
        std::exit(0);
    }

    std::u8string out_id = u8"lod_us";
    auto err = recomp::select_rom(std::filesystem::path(path), out_id);
    switch (err) {
    case recomp::RomValidationError::Good:
        return;
    case recomp::RomValidationError::IncorrectRom:
    case recomp::RomValidationError::IncorrectVersion:
        MessageBoxA(nullptr,
            "The selected ROM does not match Castlevania: Legacy of Darkness (USA).\n"
            "Expected SHA1: 879ead98f197fd05edda867655da5b1ce25aa5b8",
            "Wrong ROM", MB_ICONERROR);
        std::exit(1);
    case recomp::RomValidationError::NotARom:
        MessageBoxA(nullptr,
            "The selected file does not appear to be an N64 ROM.",
            "Not an N64 ROM", MB_ICONERROR);
        std::exit(1);
    default:
        MessageBoxA(nullptr,
            "Failed to read the selected ROM file.",
            "ROM Error", MB_ICONERROR);
        std::exit(1);
    }
}

// ── WinMain ───────────────────────────────────────────────────────────────────
int WINAPI WinMain(HINSTANCE /*hInstance*/, HINSTANCE /*hPrev*/,
                   LPSTR /*lpCmdLine*/, int /*nCmdShow*/)
{
    SetUnhandledExceptionFilter(lod_unhandled_exception);

    SDL_SetMainReady();

    // ── Config path: %APPDATA%\lodpc ──────────────────────────────────────────
    const char* appdata = std::getenv("APPDATA");
    if (!appdata) appdata = ".";
    std::filesystem::path config_path =
        std::filesystem::path(appdata) / "lodpc";
    std::filesystem::create_directories(config_path);

    // ── Diagnostic logs (GUI app: stderr/stdout otherwise vanish) ─────────────
    // NOTE: freopen_s opens exclusive; do not read the log while the game runs.
    {
        std::filesystem::path log_path = config_path / "lodpc_diag.log";
        FILE* f = nullptr;
        freopen_s(&f, log_path.string().c_str(), "w", stderr);
        if (f) {
            setvbuf(f, nullptr, _IONBF, 0);
            fprintf(stderr, "[lodpc] diagnostic log started\n");
        }
        std::filesystem::path stdout_path = config_path / "lodpc_stdout.log";
        FILE* fout = nullptr;
        freopen_s(&fout, stdout_path.string().c_str(), "w", stdout);
        if (fout) {
            setvbuf(fout, nullptr, _IONBF, 0);
            fprintf(stdout, "[lodpc] stdout log started\n");
        }
    }

    recomp::register_config_path(config_path);

    // ── Register the game ─────────────────────────────────────────────────────
    recomp::GameEntry entry{};
    entry.rom_hash           = LOD_ROM_HASH;
    entry.internal_name      = "CASTLEVANIA2";
    entry.game_id            = u8"lod_us";
    entry.mod_game_id        = "";
    entry.save_type          = recomp::SaveType::Eep4k;
    entry.is_enabled         = true;
    entry.entrypoint_address = LOD_ENTRYPOINT_VRAM;
    entry.entrypoint         = recomp_entrypoint;
    recomp::register_game(entry);

    // ── Register recompiled sections ──────────────────────────────────────────
    recomp::overlays::register_overlays(
        recomp::overlays::overlay_section_table_data_t{
            .code_sections      = section_table,
            .num_code_sections  = sizeof(section_table) / sizeof(section_table[0]),
            .total_num_sections = num_sections,
        },
        recomp::overlays::overlays_by_index_t{
            .table = overlay_sections_by_index,
            .len   = sizeof(overlay_sections_by_index) / sizeof(overlay_sections_by_index[0]),
        });

    // ── Validate stored ROM; prompt on first run ──────────────────────────────
    recomp::check_all_stored_roms();
    std::u8string game_id = u8"lod_us";
    if (!recomp::is_rom_valid(game_id)) {
        prompt_for_rom();
        recomp::check_all_stored_roms();
        if (!recomp::is_rom_valid(game_id)) {
            MessageBoxA(nullptr, "ROM validation failed after selection.", "Error", MB_ICONERROR);
            return 1;
        }
    }

    // ── Audio + input before the SDL window opens ─────────────────────────────
    SDL_Init(SDL_INIT_AUDIO);
    lod_audio_init();
    lod_input_init();

    recomp::start_game(game_id);

    recomp::Configuration cfg{};
    cfg.project_version      = { 0, 1, 0, "" };
    cfg.rsp_callbacks        = get_rsp_callbacks();
    cfg.renderer_callbacks   = { .create_render_context = lod::renderer::create_render_context };
    cfg.audio_callbacks      = get_audio_callbacks();
    cfg.input_callbacks      = get_input_callbacks();
    cfg.gfx_callbacks        = {
        .create_gfx    = create_gfx,
        .create_window = create_window,
        .update_gfx    = update_gfx,
    };
    cfg.events_callbacks     = {
        .vi_callback       = lod_vi_callback,
        .gfx_init_callback = lod_gfx_init_callback,
    };
    cfg.error_handling_callbacks = {
        .message_box = lod_message_box,
    };
    cfg.threads_callbacks    = {
        .get_game_thread_name = lod_get_thread_name,
    };
    cfg.message_queue_control = {
        .requeue_timer = true,
        .requeue_sp    = true,
        .requeue_si    = true,
        .requeue_ai    = false,
        .requeue_vi    = false,
        .requeue_pi    = false,
        .requeue_dp    = true,
    };

    // Blocks until the game exits.
    recomp::start(cfg);

    SDL_Quit();
    return 0;
}
