[input]
entrypoint                = 0x80200400
elf_path                  = "../maddenfootball64/build/maddenfootball64.elf"
rom_file_path             = "../maddenfootball64/baserom.z64"
output_func_path          = "../maddenfootball64pc/RecompiledFuncs"
relocatable_sections_path = "maddenfootball64_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80200400", size = 16 },
  { name = "osAiSetNextBuffer", size = 176 },
  { name = "func_802004B4", size = 40 },
  { name = "func_802004DC", size = 256 },
  { name = "func_802005DC", size = 4 },
  { name = "osInvalICache", size = 128 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "func_80200A9C", size = 16 },
  { name = "func_80201658", size = 16 },
  { name = "func_80203EE8", size = 64 },
  { name = "func_802043A4", size = 16 },
  { name = "func_8020507C", size = 32 },
  { name = "func_80205598", size = 48 },
  { name = "func_80209538", size = 16 },
  { name = "func_80212118", size = 64 },
  { name = "func_80214940", size = 16 },
  { name = "func_80214B10", size = 16 },
  { name = "func_80215984", size = 48 },
  { name = "func_802184D0", size = 16 },
  { name = "func_8021920C", size = 16 },
  { name = "func_80219AB8", size = 288 },
  { name = "func_8021AB60", size = 16 },
  { name = "func_8021B28C", size = 16 },
  { name = "func_8021D964", size = 16 },
  { name = "func_8021EDD8", size = 32 },
  { name = "func_80220608", size = 32 },
  { name = "func_802237C4", size = 16 },
  { name = "func_8022584C", size = 16 },
  { name = "func_80229FB0", size = 32 },
  { name = "func_8022CC0C", size = 48 },
  { name = "func_8022FDAC", size = 140 },
  { name = "func_8022FE38", size = 36 },
  { name = "func_8023069C", size = 16 },
  { name = "func_80232204", size = 16 },
  { name = "func_80235A44", size = 16 },
  { name = "func_8023AC1C", size = 16 },
  { name = "func_8023FCBC", size = 16 },
  { name = "func_8023FEA0", size = 16 },
  { name = "func_80240944", size = 16 },
  { name = "func_80240A6C", size = 16 },
  { name = "func_80241FAC", size = 32 },
  { name = "func_80242A80", size = 64 },
  { name = "func_8024313C", size = 32 },
  { name = "func_802435C4", size = 20 },
  { name = "func_80243774", size = 192 },
  { name = "func_80243C88", size = 16 },
  { name = "func_802447FC", size = 16 },
  { name = "func_80244FC8", size = 40 },
  { name = "func_802461E8", size = 32 },
  { name = "func_80246AB4", size = 16 },
  { name = "func_8024D0A8", size = 12 },
  { name = "func_8024E8D0", size = 64 },
  { name = "func_802519E8", size = 16 },
  { name = "func_802561E8", size = 128 },
  { name = "func_8025874C", size = 32 },
  { name = "func_80258D7C", size = 16 },
  { name = "func_8025AF0C", size = 32 },
  { name = "func_8025E3B0", size = 16 },
  { name = "func_8025E5C4", size = 16 },
  { name = "func_8025F2F4", size = 20 },
  { name = "func_802625E0", size = 48 },
  { name = "func_80263798", size = 48 },
  { name = "func_80263B70", size = 16 },
  { name = "func_80264AF4", size = 64 },
  { name = "func_802675B4", size = 48 },
  { name = "func_8026B508", size = 16 },
  { name = "func_8026BBFC", size = 12 },
  { name = "func_8026DDB8", size = 144 },
  { name = "func_802702B4", size = 48 },
  { name = "func_80271C14", size = 16 },
  { name = "func_802731F0", size = 16 },
  { name = "func_80274074", size = 16 },
  { name = "func_8027478C", size = 128 },
  { name = "func_80275E80", size = 16 },
  { name = "func_802791FC", size = 16 },
  { name = "func_80279E38", size = 32 },
  { name = "func_8027C2A0", size = 32 },
  { name = "func_802838C4", size = 16 },
  { name = "func_80284268", size = 208 },
  { name = "func_8028757C", size = 112 },
  { name = "func_80287B3C", size = 44 },
  { name = "func_80287D9C", size = 16 },
  { name = "func_802897C8", size = 48 },
  { name = "func_8028A07C", size = 20 },
  { name = "func_8028ABEC", size = 16 },
  { name = "func_8028D0F0", size = 32 },
  { name = "func_8028E088", size = 16 },
  { name = "func_8028FC24", size = 16 },
  { name = "func_80291380", size = 112 },
  { name = "func_80291BEC", size = 24 },
  { name = "func_80292314", size = 224 },
  { name = "func_80294C48", size = 16 },
  { name = "func_802953A0", size = 96 },
  { name = "func_80297300", size = 16 },
  { name = "func_802991A0", size = 80 },
  { name = "func_80299D5C", size = 16 },
  { name = "func_80299EC0", size = 128 },
  { name = "func_8029C0A8", size = 48 },
  { name = "func_8029CE74", size = 336 },
  { name = "func_8029D380", size = 144 },
  { name = "func_8029E970", size = 160 },
  { name = "func_8029F3AC", size = 16 },
  { name = "func_802A00A4", size = 16 },
  { name = "func_802A1E34", size = 32 },
  { name = "func_802A553C", size = 96 },
  { name = "func_802A5D8C", size = 16 },
  { name = "func_802A6414", size = 160 },
  { name = "func_802ABB00", size = 64 },
  { name = "func_802B3BC4", size = 160 },
  { name = "func_802B6404", size = 16 },
  { name = "func_802B7AF8", size = 48 },
  { name = "func_802B864C", size = 16 },
  { name = "func_802B9430", size = 32 },
  { name = "func_802BA8C0", size = 48 },
  { name = "func_802BFD38", size = 32 },
  { name = "func_802C089C", size = 16 },
  { name = "func_802C3D04", size = 16 },
  { name = "func_802C621C", size = 16 },
  { name = "func_802C7EEC", size = 16 },
  { name = "func_802CBBA8", size = 16 },
  { name = "func_802CEA80", size = 16 },
  { name = "func_802D0534", size = 16 },
  { name = "func_802D3094", size = 16 },
  { name = "func_802D5D3C", size = 112 },
  { name = "func_802D7568", size = 16 },
  { name = "func_802D765C", size = 16 },
  { name = "func_802D946C", size = 16 },
  { name = "func_802DB738", size = 16 },
  { name = "func_802DC2FC", size = 16 },
  { name = "func_802DCF94", size = 96 },
  { name = "func_802E1DF8", size = 16 },
  { name = "func_802E2844", size = 16 },
  { name = "func_802E4488", size = 16 },
  { name = "func_802EAF58", size = 32 },
  { name = "func_802EB7FC", size = 288 },
  { name = "func_802EEB2C", size = 16 },
  { name = "func_802F0450", size = 16 },
  { name = "func_802F1CDC", size = 16 },
  { name = "func_802F3EF4", size = 232 },
  { name = "func_802F5894", size = 48 },
  { name = "func_802F6710", size = 16 },
  { name = "func_802F775C", size = 32 },
  { name = "func_802F8DA8", size = 16 },
  { name = "func_802F9038", size = 16 },
  { name = "func_802FC67C", size = 20 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
