[input]
entrypoint                = 0x80000400
elf_path                  = "../worldcup98/build/worldcup98.elf"
rom_file_path             = "../worldcup98/baserom.z64"
output_func_path          = "../worldcup98pc/RecompiledFuncs"
relocatable_sections_path = "worldcup98_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80000400", size = 56 },
  { name = "func_80000438", size = 64 },
  { name = "func_80000478", size = 24 },
  { name = "func_80000490", size = 24 },
  { name = "func_800004A8", size = 24 },
  { name = "func_800004C0", size = 252 },
  { name = "func_800005BC", size = 28 },
  { name = "func_800005D8", size = 216 },
  { name = "func_800006B0", size = 148 },
  { name = "func_80000744", size = 1928 },
  { name = "func_80000ECC", size = 4 },
  { name = "func_80000ED0", size = 132 },
  { name = "func_80000F54", size = 44 },
  { name = "func_80000F80", size = 196 },
  { name = "func_80001044", size = 168 },
  { name = "func_800010EC", size = 244 },
  { name = "func_800011E0", size = 504 },
  { name = "func_800013D8", size = 208 },
  { name = "func_800014A8", size = 248 },
  { name = "func_800015A0", size = 368 },
  { name = "func_80001710", size = 48 },
  { name = "func_80001740", size = 336 },
  { name = "func_80001890", size = 256 },
  { name = "func_80001990", size = 176 },
  { name = "func_80001A40", size = 48 },
  { name = "func_80001A70", size = 16 },
  { name = "func_80001FB4", size = 232 },
  { name = "func_8000209C", size = 256 },
  { name = "func_8000219C", size = 72 },
  { name = "func_800021E4", size = 16 },
  { name = "func_800021F4", size = 380 },
  { name = "func_80002380", size = 16 },
  { name = "func_80002390", size = 32 },
  { name = "func_800023B0", size = 32 },
  { name = "func_800023D0", size = 144 },
  { name = "func_80002460", size = 656 },
  { name = "_bzero", size = 160 },
  { name = "func_80002790", size = 16 },
  { name = "func_800027A0", size = 32 },
  { name = "func_800027C0", size = 32 },
  { name = "func_800027E0", size = 176 },
  { name = "func_80002890", size = 128 },
  { name = "func_80002910", size = 256 },
  { name = "func_80002A10", size = 1700 },
  { name = "func_800030B4", size = 232 },
  { name = "func_8000319C", size = 244 },
  { name = "func_80003290", size = 560 },
  { name = "func_800034C0", size = 44 },
  { name = "__ull_rem", size = 60 },
  { name = "__ull_div", size = 60 },
  { name = "func_80003564", size = 44 },
  { name = "func_80003590", size = 60 },
  { name = "__ll_div", size = 92 },
  { name = "__ll_mul", size = 48 },
  { name = "func_80003658", size = 96 },
  { name = "func_800036B8", size = 156 },
  { name = "func_80003754", size = 44 },
  { name = "func_80003780", size = 696 },
  { name = "func_80003A38", size = 120 },
  { name = "func_80003AB0", size = 1088 },
  { name = "func_80003EF0", size = 128 },
  { name = "func_80003F70", size = 96 },
  { name = "func_80003FD0", size = 360 },
  { name = "func_80004138", size = 364 },
  { name = "func_800042A4", size = 380 },
  { name = "func_80004420", size = 464 },
  { name = "func_800045F0", size = 540 },
  { name = "func_8000480C", size = 372 },
  { name = "func_80004980", size = 516 },
  { name = "func_80004B84", size = 380 },
  { name = "func_80004D00", size = 176 },
  { name = "func_80004DB0", size = 208 },
  { name = "func_80004E80", size = 160 },
  { name = "func_80004F20", size = 368 },
  { name = "func_80005090", size = 96 },
  { name = "func_800050F0", size = 96 },
  { name = "func_80005150", size = 256 },
  { name = "func_80005250", size = 136 },
  { name = "func_800052D8", size = 48 },
  { name = "func_80005308", size = 184 },
  { name = "func_800053C0", size = 340 },
  { name = "func_80005514", size = 204 },
  { name = "func_800055E0", size = 560 },
  { name = "func_80005810", size = 96 },
  { name = "func_80005870", size = 1156 },
  { name = "func_80005CF4", size = 612 },
  { name = "func_80005F58", size = 200 },
  { name = "func_80006020", size = 92 },
  { name = "func_8000607C", size = 104 },
  { name = "func_800060E4", size = 1048 },
  { name = "func_800064FC", size = 408 },
  { name = "func_80006694", size = 604 },
  { name = "func_800068F0", size = 252 },
  { name = "func_800069EC", size = 800 },
  { name = "func_80006D0C", size = 116 },
  { name = "func_80006D80", size = 1732 },
  { name = "func_80007444", size = 436 },
  { name = "func_800075F8", size = 488 },
  { name = "func_800077E0", size = 736 },
  { name = "func_80007AC0", size = 568 },
  { name = "func_80007CF8", size = 248 },
  { name = "func_80007DF0", size = 752 },
  { name = "func_800080E0", size = 336 },
  { name = "func_80008230", size = 272 },
  { name = "func_80008340", size = 624 },
  { name = "func_800085B0", size = 416 },
  { name = "func_80008750", size = 252 },
  { name = "func_8000884C", size = 212 },
  { name = "func_80008920", size = 336 },
  { name = "func_80008A70", size = 252 },
  { name = "func_80008B6C", size = 1028 },
  { name = "func_80008F70", size = 608 },
  { name = "func_800091D0", size = 448 },
  { name = "func_80009390", size = 272 },
  { name = "func_800094A0", size = 336 },
  { name = "func_800095F0", size = 48 },
  { name = "func_80009620", size = 16 },
  { name = "func_80009630", size = 400 },
  { name = "func_800097C0", size = 240 },
  { name = "func_800098B0", size = 1168 },
  { name = "func_80009D40", size = 80 },
  { name = "func_80009D90", size = 80 },
  { name = "func_80009DE0", size = 80 },
  { name = "func_80009E30", size = 68 },
  { name = "func_80009E74", size = 44 },
  { name = "func_80009EA0", size = 224 },
  { name = "func_80009F80", size = 96 },
  { name = "func_80009FE0", size = 64 },
  { name = "func_8000A020", size = 320 },
  { name = "func_8000A160", size = 12 },
  { name = "func_8000A16C", size = 84 },
  { name = "func_8000A1C0", size = 404 },
  { name = "func_8000A354", size = 92 },
  { name = "func_8000A3B0", size = 144 },
  { name = "func_8000A440", size = 332 },
  { name = "func_8000A58C", size = 84 },
  { name = "func_8000A5E0", size = 84 },
  { name = "func_8000A634", size = 76 },
  { name = "func_8000A680", size = 336 },
  { name = "func_8000A7D0", size = 112 },
  { name = "func_8000A840", size = 16 },
  { name = "func_8000A850", size = 80 },
  { name = "func_8000A8A0", size = 160 },
  { name = "func_8000A940", size = 16 },
  { name = "func_8000A950", size = 224 },
  { name = "func_8000AA30", size = 224 },
  { name = "func_8000AB10", size = 80 },
  { name = "func_8000AB60", size = 68 },
  { name = "func_8000ABA4", size = 44 },
  { name = "func_8000ABD0", size = 448 },
  { name = "func_8000AD90", size = 176 },
  { name = "func_8000AE40", size = 48 },
  { name = "func_8000AE70", size = 80 },
  { name = "func_8000AEC0", size = 80 },
  { name = "func_8000AF10", size = 48 },
  { name = "func_8000AF40", size = 36 },
  { name = "func_8000AF64", size = 56 },
  { name = "func_8000AF9C", size = 52 },
  { name = "func_8000AFD0", size = 36 },
  { name = "func_8000AFF4", size = 92 },
  { name = "_VirtualToPhysicalTask", size = 284 },
  { name = "func_8000B16C", size = 400 },
  { name = "func_8000B2FC", size = 68 },
  { name = "_bcopy", size = 784 },
  { name = "func_8000B650", size = 48 },
  { name = "func_8000B680", size = 144 },
  { name = "func_8000B710", size = 64 },
  { name = "func_8000B750", size = 16 },
  { name = "func_8000B760", size = 32 },
  { name = "func_8000B780", size = 128 },
  { name = "func_8000B800", size = 16 },
  { name = "func_8000B810", size = 16 },
  { name = "func_8000B820", size = 336 },
  { name = "func_8000B970", size = 192 },
  { name = "func_8000BA30", size = 240 },
  { name = "func_8000BB20", size = 16 },
  { name = "func_8000BB30", size = 44 },
  { name = "func_8000BB5C", size = 40 },
  { name = "func_8000BB84", size = 76 },
  { name = "func_8000BBD0", size = 16 },
  { name = "func_8000BBE0", size = 8 },
  { name = "func_8000BBE8", size = 88 },
  { name = "func_8000BC40", size = 56 },
  { name = "func_8000BC78", size = 96 },
  { name = "func_8000BCD8", size = 24 },
  { name = "func_8000BCF0", size = 48 },
  { name = "func_8000BD20", size = 8 },
  { name = "func_8000BD28", size = 664 },
  { name = "func_8000BFC0", size = 768 },
  { name = "func_8000C2C0", size = 48 },
  { name = "func_8000C2F0", size = 224 },
  { name = "func_8000C3D0", size = 68 },
  { name = "func_8000C414", size = 84 },
  { name = "func_8000C468", size = 84 },
  { name = "func_8000C4BC", size = 136 },
  { name = "func_8000C544", size = 168 },
  { name = "func_8000C5EC", size = 164 },
  { name = "func_8000C690", size = 160 },
  { name = "func_8000C730", size = 1088 },
  { name = "func_8000CB70", size = 40 },
  { name = "func_8000CB98", size = 236 },
  { name = "func_8000CC84", size = 224 },
  { name = "func_8000CD64", size = 464 },
  { name = "func_8000CF34", size = 664 },
  { name = "func_8000D1CC", size = 176 },
  { name = "func_8000D27C", size = 1364 },
  { name = "func_8000D7D0", size = 32 },
  { name = "func_8000D7F0", size = 96 },
  { name = "func_8000D850", size = 468 },
  { name = "func_8000DA24", size = 940 },
  { name = "func_8000DDD0", size = 300 },
  { name = "func_8000DEFC", size = 1188 },
  { name = "func_8000E3A0", size = 128 },
  { name = "func_8000E420", size = 48 },
  { name = "func_8000E450", size = 288 },
  { name = "func_8000E570", size = 236 },
  { name = "func_8000E65C", size = 532 },
  { name = "func_8000E870", size = 168 },
  { name = "func_8000E918", size = 184 },
  { name = "func_8000E9D0", size = 392 },
  { name = "func_8000EB58", size = 396 },
  { name = "func_8000ECE4", size = 548 },
  { name = "func_8000EF08", size = 604 },
  { name = "func_8000F164", size = 24 },
  { name = "func_8000F17C", size = 836 },
  { name = "func_8000F4C0", size = 52 },
  { name = "func_8000F4F4", size = 140 },
  { name = "func_8000F580", size = 160 },
  { name = "func_8000F620", size = 64 },
  { name = "func_8000F660", size = 140 },
  { name = "func_8000F6EC", size = 376 },
  { name = "func_8000F864", size = 116 },
  { name = "func_8000F8D8", size = 392 },
  { name = "func_8000FA60", size = 72 },
  { name = "func_8000FAA8", size = 88 },
  { name = "func_8000FB00", size = 112 },
  { name = "func_8000FB70", size = 320 },
  { name = "func_8000FCB0", size = 64 },
  { name = "func_8000FCF0", size = 64 },
  { name = "func_8000FD30", size = 392 },
  { name = "func_8000FEB8", size = 472 },
  { name = "func_80010090", size = 16 },
  { name = "func_800100A0", size = 128 },
  { name = "func_80010120", size = 192 },
  { name = "func_800101E0", size = 112 },
  { name = "func_80010250", size = 112 },
  { name = "func_800102C0", size = 448 },
  { name = "func_80010480", size = 80 },
  { name = "func_800104D0", size = 864 },
  { name = "func_80010830", size = 128 },
  { name = "func_800108B0", size = 48 },
  { name = "func_800108E0", size = 1648 },
  { name = "func_80010F50", size = 1616 },
  { name = "func_800115A0", size = 1392 },
  { name = "func_80011B10", size = 796 },
  { name = "func_80011E2C", size = 564 },
  { name = "func_80012060", size = 256 },
  { name = "func_80012160", size = 144 },
  { name = "func_800121F0", size = 672 },
  { name = "func_80012490", size = 80 },
  { name = "func_800124E0", size = 64 },
  { name = "func_80012520", size = 488 },
  { name = "func_80012708", size = 148 },
  { name = "func_80012880", size = 1596 },
  { name = "func_80012EBC", size = 4 },
  { name = "func_80012EC0", size = 16 },
  { name = "func_80012ED0", size = 352 },
  { name = "func_80013030", size = 176 },
  { name = "func_800130E0", size = 48 },
  { name = "func_80013110", size = 64 },
  { name = "func_80013150", size = 80 },
  { name = "func_800131A0", size = 232 },
  { name = "func_80013288", size = 328 },
  { name = "func_800133D0", size = 176 },
  { name = "func_80013480", size = 160 },
  { name = "func_80013520", size = 160 },
  { name = "func_800135C0", size = 144 },
  { name = "func_80013650", size = 144 },
  { name = "func_800136E0", size = 160 },
  { name = "func_80013780", size = 144 },
  { name = "func_80013810", size = 128 },
  { name = "func_800219B4", size = 32 },
  { name = "func_8003F56C", size = 32 },
  { name = "func_80049750", size = 16 },
  { name = "func_8004F1D0", size = 48 },
  { name = "func_80054310", size = 32 },
  { name = "func_8005CB78", size = 160 },
  { name = "func_800714EC", size = 32 },
  { name = "func_80092A04", size = 48 },
  { name = "func_800CEBE4", size = 16 },
  { name = "func_800D157C", size = 16 },
  { name = "func_800D1F18", size = 48 },
  { name = "func_800D3C00", size = 16 },
  { name = "func_800F853C", size = 32 },
  { name = "func_800FEC74", size = 32 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
