[input]
entrypoint                = 0x80000400
elf_path                  = "../forsaken/build/forsaken.elf"
rom_file_path             = "../forsaken/baserom.z64"
output_func_path          = "../forsakenpc/RecompiledFuncs"
relocatable_sections_path = "forsaken_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80000400", size = 96 },
  { name = "func_80001BC0", size = 316 },
  { name = "func_80001CFC", size = 312 },
  { name = "func_80001E34", size = 572 },
  { name = "func_80002064", size = 1916 },
  { name = "func_800027E0", size = 268 },
  { name = "func_800028EC", size = 56 },
  { name = "func_80002924", size = 56 },
  { name = "func_8000295C", size = 824 },
  { name = "func_80002C8C", size = 316 },
  { name = "func_80002DC8", size = 136 },
  { name = "func_80002E50", size = 24 },
  { name = "func_80002E68", size = 20 },
  { name = "func_80002E7C", size = 4 },
  { name = "func_80002E80", size = 136 },
  { name = "func_80002F08", size = 28 },
  { name = "func_80002F24", size = 24 },
  { name = "func_80003828", size = 32 },
  { name = "func_80006250", size = 144 },
  { name = "func_800062DC", size = 244 },
  { name = "func_800063D0", size = 172 },
  { name = "func_8000647C", size = 348 },
  { name = "func_800065D8", size = 1060 },
  { name = "func_800069F4", size = 304 },
  { name = "func_80006B24", size = 156 },
  { name = "func_80006BC0", size = 1296 },
  { name = "func_800070D0", size = 776 },
  { name = "func_800073D8", size = 24 },
  { name = "func_800073F0", size = 104 },
  { name = "func_80007458", size = 60 },
  { name = "func_80007494", size = 692 },
  { name = "func_80007748", size = 44 },
  { name = "func_80007774", size = 24 },
  { name = "func_8000778C", size = 12 },
  { name = "func_80007798", size = 292 },
  { name = "func_800078BC", size = 664 },
  { name = "func_80007B54", size = 1104 },
  { name = "func_80007FA4", size = 480 },
  { name = "func_80008184", size = 64 },
  { name = "func_800081BC", size = 260 },
  { name = "func_800082C0", size = 84 },
  { name = "func_80008314", size = 64 },
  { name = "func_80008354", size = 20 },
  { name = "func_80008368", size = 340 },
  { name = "func_800084BC", size = 208 },
  { name = "func_8000858C", size = 24 },
  { name = "func_800085B0", size = 264 },
  { name = "func_800086B8", size = 252 },
  { name = "func_800087B4", size = 76 },
  { name = "func_80008800", size = 180 },
  { name = "func_800088B4", size = 124 },
  { name = "func_80008930", size = 164 },
  { name = "func_800089D4", size = 256 },
  { name = "func_80008AD4", size = 132 },
  { name = "func_80008B58", size = 244 },
  { name = "func_80008C4C", size = 2228 },
  { name = "func_80009500", size = 184 },
  { name = "func_800095B8", size = 260 },
  { name = "func_800096BC", size = 136 },
  { name = "func_80009744", size = 140 },
  { name = "func_800097D0", size = 204 },
  { name = "func_800098A0", size = 192 },
  { name = "func_80009960", size = 204 },
  { name = "func_80009A20", size = 100 },
  { name = "func_80009A84", size = 84 },
  { name = "func_80009AD8", size = 680 },
  { name = "func_80009D80", size = 120 },
  { name = "func_80009DF8", size = 276 },
  { name = "func_80009F0C", size = 212 },
  { name = "func_80009FE0", size = 212 },
  { name = "func_8000A0B4", size = 48 },
  { name = "func_8000A0E4", size = 176 },
  { name = "func_8000A194", size = 12 },
  { name = "func_8000A1A0", size = 100 },
  { name = "func_8000A204", size = 476 },
  { name = "func_8000A3E0", size = 216 },
  { name = "func_8000A4B8", size = 52 },
  { name = "func_8000A4EC", size = 60 },
  { name = "func_8000A528", size = 36 },
  { name = "func_8000A54C", size = 384 },
  { name = "func_8000A6CC", size = 36 },
  { name = "func_8000A6F0", size = 168 },
  { name = "func_8000A79C", size = 1524 },
  { name = "func_8000AD90", size = 800 },
  { name = "func_8000B0B0", size = 196 },
  { name = "func_8000B174", size = 80 },
  { name = "func_8000B1C4", size = 180 },
  { name = "func_8000B278", size = 124 },
  { name = "func_8000B2F4", size = 164 },
  { name = "func_8000B398", size = 196 },
  { name = "func_8000B45C", size = 124 },
  { name = "func_8000B4D8", size = 96 },
  { name = "func_8000B538", size = 8 },
  { name = "func_8000B540", size = 112 },
  { name = "osSpTaskYield", size = 32 },
  { name = "func_8000B5D0", size = 200 },
  { name = "func_8000B698", size = 1368 },
  { name = "func_8000BBE8", size = 416 },
  { name = "func_8000BD88", size = 92 },
  { name = "func_8000BDE4", size = 260 },
  { name = "func_8000BEE8", size = 8 },
  { name = "func_8000BEF0", size = 80 },
  { name = "func_8000BF40", size = 92 },
  { name = "func_8000BF9C", size = 732 },
  { name = "func_8000C280", size = 336 },
  { name = "func_8000C3D0", size = 896 },
  { name = "func_8000C750", size = 912 },
  { name = "func_8000CAE0", size = 16 },
  { name = "func_8000CAF0", size = 152 },
  { name = "func_8000CB88", size = 168 },
  { name = "func_8000CC30", size = 80 },
  { name = "func_8000CC80", size = 240 },
  { name = "func_8000CD70", size = 220 },
  { name = "func_8000CE4C", size = 180 },
  { name = "func_8000CF00", size = 432 },
  { name = "func_8000D0B0", size = 464 },
  { name = "func_8000D280", size = 392 },
  { name = "func_8000D408", size = 408 },
  { name = "func_8000D5A0", size = 96 },
  { name = "func_8000D600", size = 128 },
  { name = "func_8000D680", size = 416 },
  { name = "func_8000D820", size = 84 },
  { name = "func_8000D874", size = 124 },
  { name = "func_8000D8F0", size = 48 },
  { name = "func_8000D920", size = 176 },
  { name = "func_8000D9D0", size = 224 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "osCreateThread", size = 208 },
  { name = "func_8000DBE0", size = 16 },
  { name = "func_8000E154", size = 240 },
  { name = "func_8000E244", size = 264 },
  { name = "func_8000E34C", size = 72 },
  { name = "func_8000E394", size = 396 },
  { name = "__osDisableInt", size = 32 },
  { name = "__osRestoreInt", size = 32 },
  { name = "osSetIntMask", size = 160 },
  { name = "osDestroyThread", size = 208 },
  { name = "osGetTime", size = 144 },
  { name = "osGetCount", size = 16 },
  { name = "osInitialize", size = 528 },
  { name = "func_8000E990", size = 16 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_8000E9B0", size = 16 },
  { name = "func_8000E9C0", size = 128 },
  { name = "func_8000EA40", size = 96 },
  { name = "osRecvMesg", size = 304 },
  { name = "osSendMesg", size = 304 },
  { name = "osSetEventMesg", size = 96 },
  { name = "osSetThreadPri", size = 208 },
  { name = "osStartThread", size = 288 },
  { name = "osStopThread", size = 192 },
  { name = "func_8000F010", size = 64 },
  { name = "func_8000F050", size = 84 },
  { name = "func_8000F0A4", size = 316 },
  { name = "func_8000F1E0", size = 96 },
  { name = "func_8000F240", size = 272 },
  { name = "func_8000F350", size = 16 },
  { name = "osVirtualToPhysical", size = 96 },
  { name = "func_8000F3C0", size = 192 },
  { name = "func_8000F480", size = 16 },
  { name = "func_8000F490", size = 64 },
  { name = "func_8000F4D0", size = 148 },
  { name = "func_8000F564", size = 172 },
  { name = "func_8000F610", size = 148 },
  { name = "func_8000F6A4", size = 88 },
  { name = "func_8000F6FC", size = 100 },
  { name = "func_8000F760", size = 44 },
  { name = "func_8000F78C", size = 48 },
  { name = "func_8000F7BC", size = 32 },
  { name = "func_8000F7DC", size = 52 },
  { name = "func_8000F810", size = 64 },
  { name = "func_8000F850", size = 80 },
  { name = "func_8000F8A0", size = 268 },
  { name = "func_8000F9AC", size = 244 },
  { name = "func_8000FAA0", size = 128 },
  { name = "func_8000FB20", size = 624 },
  { name = "func_8000FD90", size = 124 },
  { name = "func_8000FE0C", size = 160 },
  { name = "func_8000FEAC", size = 8 },
  { name = "func_8000FEB4", size = 664 },
  { name = "func_8001014C", size = 116 },
  { name = "func_800101C0", size = 116 },
  { name = "func_80010234", size = 184 },
  { name = "func_800102EC", size = 116 },
  { name = "func_80010360", size = 16 },
  { name = "func_80010370", size = 48 },
  { name = "func_800103A0", size = 124 },
  { name = "func_8001041C", size = 152 },
  { name = "func_800104B4", size = 268 },
  { name = "func_800105C0", size = 120 },
  { name = "func_80010638", size = 184 },
  { name = "func_800106F0", size = 64 },
  { name = "func_80010730", size = 48 },
  { name = "func_80010760", size = 64 },
  { name = "func_800107A0", size = 48 },
  { name = "func_800107D0", size = 48 },
  { name = "func_80010800", size = 48 },
  { name = "func_80010830", size = 368 },
  { name = "func_800109A0", size = 1344 },
  { name = "func_80010ED4", size = 116 },
  { name = "func_80010F48", size = 300 },
  { name = "func_80011074", size = 2180 },
  { name = "func_800118F8", size = 400 },
  { name = "func_80011A88", size = 144 },
  { name = "func_80011B18", size = 56 },
  { name = "func_80011B50", size = 16 },
  { name = "func_80011B60", size = 388 },
  { name = "func_80011CE4", size = 1344 },
  { name = "func_80012224", size = 208 },
  { name = "func_800122F4", size = 388 },
  { name = "func_80012478", size = 2172 },
  { name = "func_80012CF4", size = 108 },
  { name = "func_80012D60", size = 80 },
  { name = "func_80012DB0", size = 100 },
  { name = "func_80012E14", size = 84 },
  { name = "func_80012E68", size = 304 },
  { name = "func_80012F98", size = 112 },
  { name = "func_80013008", size = 28 },
  { name = "func_80013024", size = 68 },
  { name = "func_80013068", size = 292 },
  { name = "func_8001318C", size = 176 },
  { name = "func_8001323C", size = 172 },
  { name = "func_800132E8", size = 84 },
  { name = "func_8001333C", size = 128 },
  { name = "func_800133BC", size = 180 },
  { name = "func_80013470", size = 240 },
  { name = "func_80013560", size = 64 },
  { name = "func_800135A0", size = 232 },
  { name = "func_80013688", size = 360 },
  { name = "func_800137F0", size = 104 },
  { name = "func_80013858", size = 104 },
  { name = "func_800138C0", size = 144 },
  { name = "func_80013950", size = 276 },
  { name = "func_80013A64", size = 8 },
  { name = "func_80013A6C", size = 28 },
  { name = "func_80013A88", size = 28 },
  { name = "func_80013AA4", size = 20 },
  { name = "func_80013AB8", size = 48 },
  { name = "func_80013AE8", size = 80 },
  { name = "func_80013B38", size = 88 },
  { name = "func_80013B90", size = 296 },
  { name = "func_80013CB8", size = 140 },
  { name = "func_80013D3C", size = 1112 },
  { name = "func_80014194", size = 168 },
  { name = "func_8001423C", size = 164 },
  { name = "func_800142E0", size = 192 },
  { name = "func_800143A0", size = 80 },
  { name = "func_800143F0", size = 16 },
  { name = "func_80014400", size = 96 },
  { name = "func_80014460", size = 80 },
  { name = "func_800144B0", size = 32 },
  { name = "func_800144D0", size = 80 },
  { name = "func_80014520", size = 80 },
  { name = "func_80014570", size = 80 },
  { name = "func_800145C0", size = 80 },
  { name = "func_80014610", size = 716 },
  { name = "func_800148DC", size = 432 },
  { name = "func_80014A8C", size = 44 },
  { name = "func_80014AB8", size = 24 },
  { name = "func_80014AD0", size = 84 },
  { name = "func_80014B24", size = 64 },
  { name = "func_80014B64", size = 72 },
  { name = "func_80014BAC", size = 76 },
  { name = "func_80014BF8", size = 168 },
  { name = "func_80014CA0", size = 164 },
  { name = "func_80014D44", size = 1176 },
  { name = "func_800151DC", size = 184 },
  { name = "func_80015294", size = 176 },
  { name = "func_80015344", size = 140 },
  { name = "func_800153D0", size = 92 },
  { name = "func_8001542C", size = 92 },
  { name = "func_80015488", size = 72 },
  { name = "func_800154D0", size = 1092 },
  { name = "func_80015914", size = 936 },
  { name = "func_80015CB0", size = 428 },
  { name = "func_80015E5C", size = 388 },
  { name = "func_80015FE0", size = 224 },
  { name = "func_800160BC", size = 52 },
  { name = "func_800160F0", size = 1356 },
  { name = "func_8001663C", size = 212 },
  { name = "func_80016710", size = 768 },
  { name = "func_80016A10", size = 224 },
  { name = "func_80016AF0", size = 36 },
  { name = "func_80016B14", size = 640 },
  { name = "func_80016D94", size = 140 },
  { name = "func_80016E20", size = 32 },
  { name = "func_80016E40", size = 332 },
  { name = "func_80016F80", size = 48 },
  { name = "func_80016FB0", size = 496 },
  { name = "func_8001719C", size = 196 },
  { name = "func_80017260", size = 956 },
  { name = "func_80017610", size = 20 },
  { name = "func_80017624", size = 508 },
  { name = "func_80017814", size = 536 },
  { name = "func_80017A2C", size = 368 },
  { name = "func_80017B9C", size = 368 },
  { name = "func_80017D0C", size = 156 },
  { name = "func_80017DA8", size = 152 },
  { name = "func_80017E40", size = 260 },
  { name = "func_80017F40", size = 48 },
  { name = "func_80017F70", size = 16 },
  { name = "func_80017F80", size = 80 },
  { name = "func_80017FD0", size = 160 },
  { name = "func_80018070", size = 296 },
  { name = "func_80018198", size = 184 },
  { name = "func_80018250", size = 128 },
  { name = "func_800182D0", size = 160 },
  { name = "func_80018370", size = 256 },
  { name = "func_80018470", size = 144 },
  { name = "func_80018500", size = 192 },
  { name = "func_800185C0", size = 144 },
  { name = "func_80018650", size = 144 },
  { name = "func_800186E0", size = 16 },
  { name = "func_800186F0", size = 160 },
  { name = "func_80018790", size = 96 },
  { name = "osAiSetFrequency", size = 304 },
  { name = "osAiSetNextBuffer", size = 160 },
  { name = "func_800189C0", size = 32 },
  { name = "osSpTaskLoad", size = 524 },
  { name = "osSpTaskStartGo", size = 52 },
  { name = "func_80018C20", size = 32 },
  { name = "func_80018C40", size = 16 },
  { name = "__osSpSetPc", size = 48 },
  { name = "func_80018C80", size = 256 },
  { name = "func_80018D80", size = 32 },
  { name = "osSpTaskYielded", size = 80 },
  { name = "func_80018DF0", size = 16 },
  { name = "func_80018E00", size = 16 },
  { name = "func_80018E10", size = 64 },
  { name = "func_80018E50", size = 272 },
  { name = "osCreateViManager", size = 408 },
  { name = "func_800190F8", size = 360 },
  { name = "osGetThreadPri", size = 32 },
  { name = "func_800192B0", size = 16 },
  { name = "osViSetEvent", size = 96 },
  { name = "osViSetMode", size = 80 },
  { name = "osViSetSpecialFeatures", size = 368 },
  { name = "osViSetYScale", size = 80 },
  { name = "osViSwapBuffer", size = 80 },
  { name = "func_80019580", size = 752 },
  { name = "osViBlack", size = 96 },
  { name = "func_800198D0", size = 144 },
  { name = "func_80019960", size = 32 },
  { name = "func_80019980", size = 112 },
  { name = "osContStartQuery", size = 128 },
  { name = "osContGetQuery", size = 32 },
  { name = "func_80019A90", size = 192 },
  { name = "func_80019B50", size = 84 },
  { name = "func_80019BA4", size = 108 },
  { name = "func_80019C10", size = 48 },
  { name = "osContStartReadData", size = 136 },
  { name = "osContGetReadData", size = 156 },
  { name = "func_80019D64", size = 188 },
  { name = "osContInit", size = 412 },
  { name = "func_80019FBC", size = 180 },
  { name = "func_8001A070", size = 192 },
  { name = "osSetTimer", size = 160 },
  { name = "osPfsAllocateFile", size = 912 },
  { name = "func_8001A560", size = 460 },
  { name = "func_8001A72C", size = 148 },
  { name = "func_8001A7C0", size = 544 },
  { name = "func_8001A9E0", size = 416 },
  { name = "func_8001AB80", size = 72 },
  { name = "func_8001ABC8", size = 104 },
  { name = "func_8001AC30", size = 56 },
  { name = "func_8001AC68", size = 68 },
  { name = "func_8001ACAC", size = 736 },
  { name = "func_8001AF8C", size = 356 },
  { name = "func_8001B0F0", size = 480 },
  { name = "func_8001B2D0", size = 196 },
  { name = "func_8001B394", size = 728 },
  { name = "func_8001B66C", size = 84 },
  { name = "func_8001B6C0", size = 564 },
  { name = "func_8001B8F4", size = 412 },
  { name = "osPfsDeleteFile", size = 556 },
  { name = "func_8001BCBC", size = 416 },
  { name = "func_8001BE5C", size = 212 },
  { name = "osPfsReadWriteFile", size = 1072 },
  { name = "osPfsFileState", size = 576 },
  { name = "osPfsFindFile", size = 400 },
  { name = "osPfsIsPlug", size = 380 },
  { name = "func_8001C8AC", size = 164 },
  { name = "func_8001C950", size = 192 },
  { name = "osPfsFreeBlocks", size = 272 },
  { name = "osPfsInitPak", size = 464 },
  { name = "func_8001CCF0", size = 1100 },
  { name = "func_8001D13C", size = 344 },
  { name = "func_8001D294", size = 364 },
  { name = "func_8001D400", size = 448 },
  { name = "func_8001D5C0", size = 224 },
  { name = "func_8001D6A0", size = 144 },
  { name = "func_8001D730", size = 128 },
  { name = "osMotorStop", size = 448 },
  { name = "osMotorStart", size = 448 },
  { name = "osMotorInit", size = 1232 },
  { name = "func_8001E000", size = 160 },
  { name = "osCreatePiManager", size = 400 },
  { name = "func_8001E230", size = 208 },
  { name = "osEPiRawStartDma", size = 464 },
  { name = "osCartRomInit", size = 224 },
  { name = "func_8001E5B0", size = 256 },
  { name = "func_8001E6B0", size = 1292 },
  { name = "func_8001EBBC", size = 208 },
  { name = "func_8001EC8C", size = 180 },
  { name = "func_8001ED40", size = 960 },
  { name = "func_8001F100", size = 80 },
  { name = "func_8001F150", size = 64 },
  { name = "func_8001F190", size = 80 },
  { name = "func_8001F1E0", size = 400 },
  { name = "func_8001F370", size = 336 },
  { name = "func_8001F4C0", size = 84 },
  { name = "func_8001F514", size = 108 },
  { name = "func_8001F580", size = 48 },
  { name = "osPiReadIo", size = 80 },
  { name = "osPiStartDma", size = 176 },
  { name = "osJamMesg", size = 320 },
  { name = "func_8001F7F0", size = 32 },
  { name = "func_8001F810", size = 800 },
  { name = "func_8001FB30", size = 160 },
  { name = "func_8001FBD0", size = 56 },
  { name = "func_8001FC08", size = 36 },
  { name = "func_8001FC2C", size = 52 },
  { name = "func_8001FC60", size = 88 },
  { name = "func_8001FCB8", size = 56 },
  { name = "func_8001FCF0", size = 1392 },
  { name = "func_80020260", size = 1216 },
  { name = "func_80020720", size = 592 },
  { name = "func_80020970", size = 132 },
  { name = "func_800209F4", size = 316 },
  { name = "func_80020B30", size = 1088 },
  { name = "func_80020F70", size = 152 },
  { name = "func_80021008", size = 1448 },
  { name = "func_800215B0", size = 64 },
  { name = "func_800215F0", size = 152 },
  { name = "func_80021690", size = 488 },
  { name = "func_80021878", size = 8 },
  { name = "func_80021920", size = 188 },
  { name = "func_800219DC", size = 4 },
  { name = "func_800219E0", size = 32 },
  { name = "func_80021A00", size = 1600 },
  { name = "func_80022040", size = 60 },
  { name = "func_80023580", size = 124 },
  { name = "func_800235FC", size = 140 },
  { name = "func_80028B40", size = 16 },
  { name = "func_80046530", size = 56 },
  { name = "func_80059EAC", size = 16 },
  { name = "func_800810F8", size = 16 },
  { name = "func_800823D8", size = 48 },
  { name = "func_80088D2C", size = 48 },
  { name = "func_800D39E8", size = 16 },
]

exact_size_funcs = [

]

[patches]
stubs = [
  "func_80002F24",
  "func_800219DC",
  "func_800810F8",
  "func_800823D8",
]
