[input]
entrypoint                = 0x80300000
elf_path                  = "../jeremymcgrathsuper/build/jeremymcgrathsuper.elf"
rom_file_path             = "../jeremymcgrathsuper/baserom.z64"
output_func_path          = "../jeremymcgrathsuperpc/RecompiledFuncs"
relocatable_sections_path = "jeremymcgrathsuper_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80300000", size = 136 },
  { name = "func_80300088", size = 120 },
  { name = "func_80300100", size = 8 },
  { name = "func_803001B8", size = 120 },
  { name = "func_80300360", size = 24 },
  { name = "func_80300378", size = 52 },
  { name = "func_803003AC", size = 64 },
  { name = "func_803003EC", size = 48 },
  { name = "func_8030041C", size = 80 },
  { name = "func_8030046C", size = 4 },
  { name = "func_80300470", size = 208 },
  { name = "func_80300540", size = 428 },
  { name = "func_803006EC", size = 216 },
  { name = "func_803007C4", size = 52 },
  { name = "func_803007F8", size = 60 },
  { name = "func_80300834", size = 36 },
  { name = "func_80300858", size = 384 },
  { name = "func_803009D8", size = 136 },
  { name = "osAiSetFrequency", size = 152 },
  { name = "osAiSetNextBuffer", size = 152 },
  { name = "osInitialize", size = 528 },
  { name = "func_80300DA0", size = 160 },
  { name = "func_80300E40", size = 16 },
  { name = "func_80300EEC", size = 1224 },
  { name = "func_803013B4", size = 240 },
  { name = "func_803014A4", size = 264 },
  { name = "func_803015AC", size = 72 },
  { name = "func_803015F4", size = 396 },
  { name = "osDestroyThread", size = 208 },
  { name = "func_80301860", size = 16 },
  { name = "__osDisableInt", size = 32 },
  { name = "__osRestoreInt", size = 32 },
  { name = "func_803018B0", size = 128 },
  { name = "func_80301930", size = 1292 },
  { name = "func_80301E3C", size = 208 },
  { name = "func_80301F0C", size = 180 },
  { name = "osEPiRawStartDma", size = 464 },
  { name = "func_80302190", size = 256 },
  { name = "osCreatePiManager", size = 400 },
  { name = "osCartRomInit", size = 224 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "osCreateThread", size = 208 },
  { name = "func_80302600", size = 960 },
  { name = "func_803029C0", size = 400 },
  { name = "func_80302B50", size = 16 },
  { name = "func_80302B60", size = 336 },
  { name = "osGetThreadPri", size = 32 },
  { name = "func_80302CD0", size = 84 },
  { name = "func_80302D24", size = 108 },
  { name = "func_80302D90", size = 48 },
  { name = "func_80302DC0", size = 208 },
  { name = "func_80302E90", size = 160 },
  { name = "osRecvMesg", size = 256 },
  { name = "func_80303030", size = 48 },
  { name = "func_80303060", size = 80 },
  { name = "osSendMesg", size = 304 },
  { name = "osSetEventMesg", size = 96 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_80303250", size = 64 },
  { name = "osSetIntMask", size = 160 },
  { name = "func_80303330", size = 16 },
  { name = "osSetThreadPri", size = 208 },
  { name = "func_80303410", size = 144 },
  { name = "func_803034A0", size = 32 },
  { name = "func_803034C0", size = 112 },
  { name = "osStartThread", size = 288 },
  { name = "func_80303650", size = 64 },
  { name = "osVirtualToPhysical", size = 96 },
  { name = "func_803036F0", size = 192 },
  { name = "func_803037B0", size = 128 },
  { name = "func_80303830", size = 80 },
  { name = "func_80303880", size = 1412 },
  { name = "func_80306EA8", size = 512 },
  { name = "func_803070A8", size = 5224 },
  { name = "func_80308510", size = 5228 },
  { name = "func_8030997C", size = 440 },
  { name = "func_80309B34", size = 168 },
  { name = "func_80309BDC", size = 3388 },
  { name = "func_80313278", size = 176 },
  { name = "func_803233C8", size = 48 },
  { name = "func_80372A8C", size = 16 },
  { name = "func_80389430", size = 32 },
]

exact_size_funcs = [

]

[patches]
stubs = [
  "func_803001B8",
]
