[input]
entrypoint                = 0x80061600
elf_path                  = "../kengriffeyjrsslugf/build/kengriffeyjrsslugf.elf"
rom_file_path             = "../kengriffeyjrsslugf/baserom.z64"
output_func_path          = "../kengriffeyjrsslugfpc/RecompiledFuncs"
relocatable_sections_path = "kengriffeyjrsslugf_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80061600", size = 96 },
  { name = "func_80061660", size = 560 },
  { name = "func_80061890", size = 128 },
  { name = "func_80061910", size = 16 },
  { name = "func_80061920", size = 12 },
  { name = "func_8006192C", size = 12 },
  { name = "func_80061938", size = 8 },
  { name = "func_80061940", size = 160 },
  { name = "osInvalDCache", size = 176 },
  { name = "osSetIntMask", size = 160 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "osInitialize", size = 656 },
  { name = "func_80061DF0", size = 80 },
  { name = "func_80061E40", size = 80 },
  { name = "func_80061E90", size = 16 },
  { name = "func_80061EA0", size = 96 },
  { name = "osPiReadIo", size = 64 },
  { name = "func_80061F40", size = 224 },
  { name = "func_80062020", size = 80 },
  { name = "func_80062070", size = 64 },
  { name = "_bzero", size = 160 },
  { name = "func_80062150", size = 44 },
  { name = "__ull_rem", size = 60 },
  { name = "__ull_div", size = 60 },
  { name = "func_800621F4", size = 44 },
  { name = "func_80062220", size = 60 },
  { name = "__ll_div", size = 92 },
  { name = "__ll_mul", size = 48 },
  { name = "func_800622E8", size = 96 },
  { name = "func_80062348", size = 156 },
  { name = "func_800623E4", size = 44 },
  { name = "func_80062410", size = 16 },
  { name = "func_80062954", size = 232 },
  { name = "func_80062A3C", size = 256 },
  { name = "func_80062B3C", size = 72 },
  { name = "func_80062B84", size = 396 },
  { name = "func_80062D20", size = 16 },
  { name = "osInvalICache", size = 224 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_80062E20", size = 16 },
  { name = "osWritebackDCache", size = 128 },
  { name = "func_80062EB0", size = 96 },
  { name = "osDestroyThread", size = 272 },
  { name = "osSetEventMesg", size = 112 },
  { name = "func_80063090", size = 64 },
  { name = "osVirtualToPhysical", size = 128 },
  { name = "func_80063150", size = 48 },
  { name = "func_80063180", size = 1700 },
  { name = "func_80063824", size = 232 },
  { name = "func_8006390C", size = 244 },
  { name = "func_80063A00", size = 16 },
  { name = "func_80063A10", size = 16 },
  { name = "__osDisableInt", size = 32 },
  { name = "__osRestoreInt", size = 32 },
  { name = "func_80063A60", size = 192 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "osRecvMesg", size = 320 },
  { name = "osStartThread", size = 336 },
  { name = "osEPiRawStartDma", size = 560 },
  { name = "func_80064010", size = 256 },
  { name = "func_80064110", size = 1648 },
  { name = "func_80064780", size = 1616 },
  { name = "osCreateThread", size = 336 },
  { name = "func_80064F20", size = 16 },
  { name = "osStopThread", size = 192 },
  { name = "func_80064FF0", size = 80 },
  { name = "func_80065040", size = 80 },
  { name = "osCreatePiManager", size = 400 },
  { name = "osCartRomInit", size = 256 },
  { name = "func_80065320", size = 1168 },
  { name = "func_800657B0", size = 80 },
  { name = "func_80065800", size = 68 },
  { name = "func_80065844", size = 44 },
  { name = "func_80065870", size = 44 },
  { name = "func_8006589C", size = 40 },
  { name = "func_800658C4", size = 76 },
  { name = "func_80065910", size = 672 },
  { name = "func_80065BB0", size = 1392 },
  { name = "func_80066120", size = 1360 },
  { name = "osGetThreadPri", size = 32 },
  { name = "func_80066690", size = 96 },
  { name = "osSendMesg", size = 336 },
  { name = "func_80066840", size = 80 },
  { name = "osSetThreadPri", size = 224 },
  { name = "func_80066970", size = 80 },
  { name = "func_800669C0", size = 48 },
  { name = "func_800669F0", size = 416 },
  { name = "func_80066B90", size = 400 },
  { name = "func_80066D20", size = 256 },
  { name = "func_80066E20", size = 144 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
