[input]
entrypoint                = 0x80000400
elf_path                  = "../fifa99/build/fifa99.elf"
rom_file_path             = "../fifa99/baserom.z64"
output_func_path          = "../fifa99pc/RecompiledFuncs"
relocatable_sections_path = "fifa99_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80000400", size = 64 },
  { name = "func_80000438", size = 64 },
  { name = "func_80000478", size = 24 },
  { name = "func_80000490", size = 24 },
  { name = "func_800004A8", size = 24 },
  { name = "func_800004C0", size = 252 },
  { name = "func_800005BC", size = 28 },
  { name = "func_800005D8", size = 204 },
  { name = "func_800006A4", size = 4 },
  { name = "func_800006A8", size = 148 },
  { name = "func_8000073C", size = 1928 },
  { name = "func_80000EC4", size = 4 },
  { name = "osContStartQuery", size = 128 },
  { name = "osContGetQuery", size = 32 },
  { name = "osContStartReadData", size = 136 },
  { name = "osContGetReadData", size = 156 },
  { name = "func_8000108C", size = 188 },
  { name = "osContInit", size = 412 },
  { name = "func_800012E4", size = 180 },
  { name = "func_80001398", size = 192 },
  { name = "func_80001458", size = 336 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "osCreateThread", size = 208 },
  { name = "osDestroyThread", size = 208 },
  { name = "osDpSetNextBuffer", size = 160 },
  { name = "func_80001818", size = 32 },
  { name = "func_80001838", size = 16 },
  { name = "func_80001DAC", size = 240 },
  { name = "func_80001E9C", size = 264 },
  { name = "func_80001FA4", size = 72 },
  { name = "func_80001FEC", size = 16 },
  { name = "func_80001FFC", size = 380 },
  { name = "osGetThreadId", size = 36 },
  { name = "func_800021A8", size = 32 },
  { name = "osGetTime", size = 144 },
  { name = "osGetCount", size = 16 },
  { name = "osInitialize", size = 528 },
  { name = "func_80002478", size = 160 },
  { name = "func_80002518", size = 16 },
  { name = "__osDisableInt", size = 32 },
  { name = "__osRestoreInt", size = 32 },
  { name = "func_80002568", size = 176 },
  { name = "func_80002618", size = 128 },
  { name = "func_80002698", size = 1292 },
  { name = "func_80002BA4", size = 208 },
  { name = "func_80002C74", size = 180 },
  { name = "osEPiRawStartDma", size = 464 },
  { name = "func_80002EF8", size = 256 },
  { name = "func_80002FF8", size = 896 },
  { name = "func_80003378", size = 912 },
  { name = "func_80003708", size = 96 },
  { name = "func_80003768", size = 116 },
  { name = "func_800037DC", size = 140 },
  { name = "func_80003868", size = 220 },
  { name = "func_80003944", size = 180 },
  { name = "func_800039F8", size = 152 },
  { name = "func_80003A90", size = 168 },
  { name = "func_80003B38", size = 80 },
  { name = "func_80003B88", size = 336 },
  { name = "func_80003CD8", size = 432 },
  { name = "func_80003E88", size = 464 },
  { name = "osPiStartDma", size = 176 },
  { name = "osJamMesg", size = 320 },
  { name = "func_80004248", size = 32 },
  { name = "func_80004268", size = 16 },
  { name = "osCreatePiManager", size = 400 },
  { name = "osCartRomInit", size = 224 },
  { name = "func_800044E8", size = 960 },
  { name = "func_800048A8", size = 400 },
  { name = "func_80004A38", size = 16 },
  { name = "func_80004A48", size = 336 },
  { name = "func_80004B98", size = 84 },
  { name = "func_80004BEC", size = 108 },
  { name = "func_80004C58", size = 48 },
  { name = "func_80004C88", size = 208 },
  { name = "func_80004D58", size = 160 },
  { name = "osPiReadIo", size = 80 },
  { name = "osRecvMesg", size = 304 },
  { name = "func_80004F78", size = 80 },
  { name = "func_80004FC8", size = 392 },
  { name = "func_80005150", size = 408 },
  { name = "func_800052E8", size = 96 },
  { name = "func_80005348", size = 128 },
  { name = "osSendMesg", size = 304 },
  { name = "osSetEventMesg", size = 96 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_80005568", size = 64 },
  { name = "osSetIntMask", size = 160 },
  { name = "func_80005648", size = 16 },
  { name = "osSetThreadPri", size = 208 },
  { name = "osSetTimer", size = 160 },
  { name = "func_800057C8", size = 84 },
  { name = "func_8000581C", size = 108 },
  { name = "func_80005888", size = 48 },
  { name = "func_800058B8", size = 416 },
  { name = "func_80005A58", size = 192 },
  { name = "func_80005B18", size = 32 },
  { name = "func_80005B38", size = 144 },
  { name = "func_80005BC8", size = 112 },
  { name = "func_80005C38", size = 88 },
  { name = "func_80005C90", size = 56 },
  { name = "osSpTaskLoad", size = 524 },
  { name = "osSpTaskStartGo", size = 52 },
  { name = "func_80005F08", size = 800 },
  { name = "func_80006228", size = 32 },
  { name = "func_80006248", size = 256 },
  { name = "__osSpSetPc", size = 48 },
  { name = "func_80006378", size = 16 },
  { name = "osSpTaskYield", size = 32 },
  { name = "osSpTaskYielded", size = 80 },
  { name = "func_800063F8", size = 16 },
  { name = "func_80006408", size = 16 },
  { name = "osStartThread", size = 288 },
  { name = "osStopThread", size = 192 },
  { name = "osStopTimer", size = 192 },
  { name = "func_800066B8", size = 16 },
  { name = "func_800066C8", size = 56 },
  { name = "func_80006700", size = 36 },
  { name = "func_80006724", size = 52 },
  { name = "func_80006758", size = 64 },
  { name = "func_80006798", size = 84 },
  { name = "func_800067EC", size = 316 },
  { name = "func_80006928", size = 96 },
  { name = "func_80006988", size = 272 },
  { name = "func_80006A98", size = 84 },
  { name = "func_80006AEC", size = 124 },
  { name = "osViBlack", size = 96 },
  { name = "func_80006BC8", size = 272 },
  { name = "osViGetCurrentFramebuffer", size = 64 },
  { name = "osViGetNextFramebuffer", size = 64 },
  { name = "osCreateViManager", size = 408 },
  { name = "func_80006EF0", size = 408 },
  { name = "func_80007088", size = 16 },
  { name = "osVirtualToPhysical", size = 96 },
  { name = "func_800070F8", size = 192 },
  { name = "osViSetEvent", size = 96 },
  { name = "osViSetMode", size = 80 },
  { name = "osViSetSpecialFeatures", size = 368 },
  { name = "osViSwapBuffer", size = 80 },
  { name = "func_80007428", size = 752 },
  { name = "func_80007718", size = 128 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "func_800077C8", size = 1392 },
  { name = "func_80007D38", size = 1216 },
  { name = "func_800081F8", size = 1088 },
  { name = "func_80008638", size = 152 },
  { name = "func_800086D0", size = 1448 },
  { name = "func_80008C78", size = 132 },
  { name = "func_80008CFC", size = 316 },
  { name = "func_80008E38", size = 592 },
  { name = "func_80009088", size = 80 },
  { name = "func_800090D8", size = 152 },
  { name = "func_80009170", size = 32 },
  { name = "func_80009190", size = 1596 },
  { name = "func_800097CC", size = 4 },
  { name = "func_800097D0", size = 44 },
  { name = "func_800097FC", size = 4 },
  { name = "func_80009800", size = 1400 },
  { name = "func_80009D78", size = 120 },
  { name = "osMotorStop", size = 448 },
  { name = "osMotorStart", size = 448 },
  { name = "osMotorInit", size = 1232 },
  { name = "func_8000A640", size = 564 },
  { name = "func_8000A874", size = 412 },
  { name = "func_8000AA10", size = 544 },
  { name = "func_8000AC30", size = 416 },
  { name = "func_8000ADD0", size = 72 },
  { name = "func_8000AE18", size = 104 },
  { name = "func_8000AE80", size = 176 },
  { name = "osPfsAllocateFile", size = 912 },
  { name = "func_8000B2C0", size = 460 },
  { name = "func_8000B48C", size = 148 },
  { name = "func_8000B520", size = 56 },
  { name = "func_8000B558", size = 68 },
  { name = "func_8000B59C", size = 736 },
  { name = "func_8000B87C", size = 356 },
  { name = "func_8000B9E0", size = 480 },
  { name = "func_8000BBC0", size = 196 },
  { name = "func_8000BC84", size = 728 },
  { name = "func_8000BF5C", size = 84 },
  { name = "func_8000BFB0", size = 1100 },
  { name = "func_8000C3FC", size = 344 },
  { name = "func_8000C554", size = 364 },
  { name = "osPfsDeleteFile", size = 556 },
  { name = "func_8000C8EC", size = 416 },
  { name = "func_8000CA8C", size = 212 },
  { name = "osPfsFileState", size = 576 },
  { name = "osPfsFreeBlocks", size = 272 },
  { name = "func_8000CEB0", size = 224 },
  { name = "func_8000CF90", size = 144 },
  { name = "func_8000D020", size = 128 },
  { name = "osPfsInitPak", size = 464 },
  { name = "osPfsIsPlug", size = 380 },
  { name = "func_8000D3EC", size = 164 },
  { name = "func_8000D490", size = 192 },
  { name = "func_8000D550", size = 256 },
  { name = "osPfsReadWriteFile", size = 1072 },
  { name = "func_8000DA80", size = 448 },
  { name = "osPfsFindFile", size = 400 },
  { name = "func_8000DDD0", size = 16 },
  { name = "osAiSetFrequency", size = 304 },
  { name = "osAiSetNextBuffer", size = 160 },
  { name = "func_8000DFB0", size = 32 },
  { name = "func_8000DFD0", size = 80 },
  { name = "func_8000E020", size = 64 },
  { name = "func_8000E060", size = 44 },
  { name = "func_8000E08C", size = 48 },
  { name = "func_8000E0BC", size = 32 },
  { name = "func_8000E0DC", size = 52 },
  { name = "func_8000E110", size = 80 },
  { name = "func_8000E160", size = 296 },
  { name = "func_8000E288", size = 184 },
  { name = "func_8000E340", size = 16 },
  { name = "func_8000E350", size = 160 },
  { name = "func_8000E3F0", size = 160 },
  { name = "func_8000E490", size = 144 },
  { name = "func_8000E520", size = 144 },
  { name = "func_8000E5B0", size = 144 },
  { name = "func_8000E640", size = 192 },
  { name = "func_8000E700", size = 160 },
  { name = "func_8000E7A0", size = 128 },
  { name = "func_8000E820", size = 716 },
  { name = "func_8000EAEC", size = 432 },
  { name = "func_8000EC9C", size = 44 },
  { name = "func_8000ECC8", size = 24 },
  { name = "func_8000ECE0", size = 84 },
  { name = "func_8000ED34", size = 64 },
  { name = "func_8000ED74", size = 72 },
  { name = "func_8000EDBC", size = 76 },
  { name = "func_8000EE08", size = 168 },
  { name = "func_8000EEB0", size = 220 },
  { name = "func_8000EF8C", size = 52 },
  { name = "func_8000EFC0", size = 164 },
  { name = "func_8000F064", size = 1176 },
  { name = "func_8000F4FC", size = 184 },
  { name = "func_8000F5B4", size = 176 },
  { name = "func_8000F664", size = 140 },
  { name = "func_8000F6F0", size = 92 },
  { name = "func_8000F74C", size = 92 },
  { name = "func_8000F7A8", size = 72 },
  { name = "func_8000F7F0", size = 1356 },
  { name = "func_8000FD3C", size = 212 },
  { name = "func_8000FE10", size = 768 },
  { name = "func_80010110", size = 224 },
  { name = "func_800101F0", size = 36 },
  { name = "func_80010214", size = 640 },
  { name = "func_80010494", size = 140 },
  { name = "func_80010520", size = 32 },
  { name = "func_80010540", size = 1092 },
  { name = "func_80010984", size = 924 },
  { name = "func_80010D20", size = 428 },
  { name = "func_80010ECC", size = 388 },
  { name = "func_80011050", size = 64 },
  { name = "func_80011090", size = 320 },
  { name = "func_800111D0", size = 48 },
  { name = "func_80011200", size = 492 },
  { name = "func_800113EC", size = 196 },
  { name = "func_800114B0", size = 944 },
  { name = "func_80011860", size = 20 },
  { name = "func_80011874", size = 496 },
  { name = "func_80011A64", size = 536 },
  { name = "func_80011C7C", size = 368 },
  { name = "func_80011DEC", size = 368 },
  { name = "func_80011F5C", size = 156 },
  { name = "func_80011FF8", size = 152 },
  { name = "func_80012090", size = 256 },
  { name = "func_80012190", size = 48 },
  { name = "func_800121C0", size = 160 },
  { name = "func_80012260", size = 304 },
  { name = "func_80012390", size = 336 },
  { name = "func_800124E0", size = 348 },
  { name = "func_8001263C", size = 388 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
