[input]
entrypoint                = 0x80000400
elf_path                  = "../sfrush/build/sfrush.elf"
rom_file_path             = "../sfrush/baserom.z64"
output_func_path          = "../sfrushpc/RecompiledFuncs"
relocatable_sections_path = "sfrush_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80000400", size = 80 },
  { name = "func_80000510", size = 200 },
  { name = "func_800005D8", size = 404 },
  { name = "func_8000076C", size = 132 },
  { name = "func_800007F0", size = 380 },
  { name = "func_8000096C", size = 104 },
  { name = "func_800009D4", size = 8 },
  { name = "func_800009DC", size = 16 },
  { name = "func_800009EC", size = 648 },
  { name = "func_80000C74", size = 444 },
  { name = "func_80000E30", size = 404 },
  { name = "func_80000FC4", size = 216 },
  { name = "func_8000109C", size = 180 },
  { name = "func_80001150", size = 284 },
  { name = "func_8000126C", size = 184 },
  { name = "func_80001324", size = 384 },
  { name = "func_800014A4", size = 96 },
  { name = "func_80001504", size = 876 },
  { name = "func_80001870", size = 112 },
  { name = "func_800018E0", size = 112 },
  { name = "func_80001950", size = 3948 },
  { name = "func_800028BC", size = 2616 },
  { name = "func_800032F4", size = 516 },
  { name = "func_800034F8", size = 280 },
  { name = "func_80003610", size = 80 },
  { name = "func_80003660", size = 96 },
  { name = "func_800036C0", size = 452 },
  { name = "func_80003884", size = 396 },
  { name = "func_80003A10", size = 32 },
  { name = "func_80003A30", size = 232 },
  { name = "func_80003B18", size = 776 },
  { name = "osInitialize", size = 656 },
  { name = "func_800040B0", size = 96 },
  { name = "osCreateThread", size = 336 },
  { name = "osStartThread", size = 336 },
  { name = "osCreatePiManager", size = 400 },
  { name = "osSetThreadPri", size = 224 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "osInvalICache", size = 128 },
  { name = "osInvalDCache", size = 176 },
  { name = "_bzero", size = 160 },
  { name = "osPiStartDma", size = 272 },
  { name = "osRecvMesg", size = 320 },
  { name = "osCreateViManager", size = 392 },
  { name = "func_80004BF8", size = 472 },
  { name = "osViSetMode", size = 112 },
  { name = "osViBlack", size = 112 },
  { name = "osSetEventMesg", size = 112 },
  { name = "osViSetEvent", size = 112 },
  { name = "osSetIntMask", size = 160 },
  { name = "osGetTime", size = 144 },
  { name = "osJamMesg", size = 336 },
  { name = "osViSwapBuffer", size = 80 },
  { name = "osSendMesg", size = 336 },
  { name = "osSpTaskYielded", size = 128 },
  { name = "osViGetNextFramebuffer", size = 64 },
  { name = "osViGetCurrentFramebuffer", size = 64 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "_VirtualToPhysicalTask", size = 284 },
  { name = "osSpTaskLoad", size = 400 },
  { name = "osSpTaskStartGo", size = 68 },
  { name = "osDpSetNextBuffer", size = 176 },
  { name = "osSpTaskYield", size = 32 },
  { name = "func_800058A0", size = 44 },
  { name = "func_800058CC", size = 40 },
  { name = "func_800058F4", size = 76 },
  { name = "func_80005940", size = 28 },
  { name = "func_8000595C", size = 36 },
  { name = "func_80005980", size = 448 },
  { name = "func_80005B40", size = 368 },
  { name = "func_80005CB0", size = 340 },
  { name = "func_80005E04", size = 108 },
  { name = "func_80005E70", size = 560 },
  { name = "func_800060A0", size = 96 },
  { name = "func_80006100", size = 696 },
  { name = "func_800063B8", size = 120 },
  { name = "func_80006430", size = 256 },
  { name = "func_80006530", size = 136 },
  { name = "func_800065B8", size = 48 },
  { name = "func_800065E8", size = 184 },
  { name = "osContInit", size = 504 },
  { name = "func_80006898", size = 208 },
  { name = "func_80006968", size = 248 },
  { name = "osContStartQuery", size = 132 },
  { name = "osContGetQuery", size = 44 },
  { name = "osContStartReadData", size = 196 },
  { name = "osContGetReadData", size = 168 },
  { name = "func_80006C7C", size = 244 },
  { name = "func_80006D70", size = 80 },
  { name = "osViSetSpecialFeatures", size = 448 },
  { name = "func_80006F80", size = 28 },
  { name = "func_80006F9C", size = 28 },
  { name = "func_80006FB8", size = 160 },
  { name = "func_80007058", size = 156 },
  { name = "func_800070F4", size = 24 },
  { name = "func_8000710C", size = 24 },
  { name = "__ull_to_d", size = 52 },
  { name = "__ull_to_f", size = 56 },
  { name = "func_80007190", size = 32 },
  { name = "func_800071B0", size = 80 },
  { name = "func_80007200", size = 32 },
  { name = "func_80007220", size = 80 },
  { name = "func_80007270", size = 160 },
  { name = "func_80007310", size = 96 },
  { name = "func_80007370", size = 96 },
  { name = "func_800073D0", size = 96 },
  { name = "func_80007430", size = 96 },
  { name = "func_80007490", size = 112 },
  { name = "func_80007500", size = 16 },
  { name = "func_80007510", size = 48 },
  { name = "func_80007540", size = 64 },
  { name = "func_80007580", size = 28 },
  { name = "func_8000759C", size = 28 },
  { name = "func_800075B8", size = 8 },
  { name = "func_800075C0", size = 8 },
  { name = "func_800075C8", size = 76 },
  { name = "func_80007614", size = 388 },
  { name = "func_80007798", size = 288 },
  { name = "func_800078B8", size = 228 },
  { name = "func_8000799C", size = 84 },
  { name = "func_800079F0", size = 88 },
  { name = "func_80007A48", size = 80 },
  { name = "func_80007A98", size = 48 },
  { name = "func_80007AC8", size = 216 },
  { name = "func_80007BA0", size = 64 },
  { name = "func_80007BE0", size = 64 },
  { name = "func_80007C20", size = 48 },
  { name = "func_80007C50", size = 96 },
  { name = "func_80007CB0", size = 64 },
  { name = "func_80007CF0", size = 16 },
  { name = "func_80007D00", size = 244 },
  { name = "func_80007DF4", size = 260 },
  { name = "func_80007EF8", size = 72 },
  { name = "osAiSetFrequency", size = 352 },
  { name = "func_800080A0", size = 48 },
  { name = "func_800080D0", size = 36 },
  { name = "func_800080F4", size = 56 },
  { name = "func_8000812C", size = 52 },
  { name = "func_80008160", size = 84 },
  { name = "func_800081B4", size = 128 },
  { name = "func_80008234", size = 180 },
  { name = "func_800082E8", size = 8 },
  { name = "func_800082F0", size = 36 },
  { name = "func_80008314", size = 136 },
  { name = "func_8000839C", size = 300 },
  { name = "func_800084C8", size = 168 },
  { name = "func_80008570", size = 112 },
  { name = "func_800085E0", size = 220 },
  { name = "func_800086BC", size = 120 },
  { name = "func_80008734", size = 72 },
  { name = "func_8000877C", size = 116 },
  { name = "func_800087F0", size = 112 },
  { name = "func_80008860", size = 252 },
  { name = "func_8000895C", size = 2080 },
  { name = "func_8000917C", size = 1572 },
  { name = "func_800097A0", size = 260 },
  { name = "func_800098A4", size = 112 },
  { name = "func_80009914", size = 396 },
  { name = "func_80009AA0", size = 64 },
  { name = "func_80009AE0", size = 140 },
  { name = "func_80009B6C", size = 1352 },
  { name = "func_8000A0B4", size = 316 },
  { name = "osAiSetNextBuffer", size = 176 },
  { name = "func_8000A2A0", size = 16 },
  { name = "func_8000A2B0", size = 8 },
  { name = "func_8000A2B8", size = 88 },
  { name = "func_8000A310", size = 56 },
  { name = "func_8000A348", size = 96 },
  { name = "func_8000A3A8", size = 24 },
  { name = "func_8000A3C0", size = 48 },
  { name = "func_8000A3F0", size = 8 },
  { name = "func_8000A3F8", size = 664 },
  { name = "func_8000A690", size = 768 },
  { name = "func_8000A990", size = 16 },
  { name = "osPfsInitPak", size = 624 },
  { name = "func_8000AC10", size = 360 },
  { name = "func_8000AD78", size = 364 },
  { name = "func_8000AEE4", size = 380 },
  { name = "osMotorInit", size = 464 },
  { name = "func_8000B230", size = 608 },
  { name = "osPfsFindFile", size = 448 },
  { name = "osPfsFileState", size = 752 },
  { name = "osPfsDeleteFile", size = 736 },
  { name = "func_8000BC20", size = 568 },
  { name = "func_8000BE58", size = 248 },
  { name = "osPfsAllocateFile", size = 1156 },
  { name = "func_8000C3D4", size = 612 },
  { name = "func_8000C638", size = 200 },
  { name = "func_8000C700", size = 252 },
  { name = "func_8000C7FC", size = 1028 },
  { name = "osPfsFreeBlocks", size = 336 },
  { name = "func_8000CD50", size = 1732 },
  { name = "func_8000D414", size = 436 },
  { name = "func_8000D5C8", size = 488 },
  { name = "osStopThread", size = 192 },
  { name = "func_8000D870", size = 16 },
  { name = "func_8000D880", size = 16 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_8000D8A0", size = 80 },
  { name = "func_8000D8F0", size = 80 },
  { name = "func_8000D940", size = 16 },
  { name = "func_8000DE84", size = 232 },
  { name = "func_8000DF6C", size = 256 },
  { name = "func_8000E06C", size = 72 },
  { name = "func_8000E0B4", size = 16 },
  { name = "func_8000E0C4", size = 380 },
  { name = "osWritebackDCache", size = 128 },
  { name = "func_8000E2D0", size = 96 },
  { name = "func_8000E330", size = 44 },
  { name = "__ull_rem", size = 60 },
  { name = "__ull_div", size = 60 },
  { name = "func_8000E3D4", size = 44 },
  { name = "func_8000E400", size = 60 },
  { name = "__ll_div", size = 92 },
  { name = "__ll_mul", size = 48 },
  { name = "func_8000E4C8", size = 96 },
  { name = "func_8000E528", size = 156 },
  { name = "func_8000E5C4", size = 44 },
  { name = "__osDisableInt", size = 32 },
  { name = "__osRestoreInt", size = 32 },
  { name = "func_8000E630", size = 64 },
  { name = "func_8000E670", size = 240 },
  { name = "func_8000E760", size = 256 },
  { name = "func_8000E860", size = 80 },
  { name = "func_8000E8B0", size = 68 },
  { name = "func_8000E8F4", size = 44 },
  { name = "osGetThreadPri", size = 32 },
  { name = "func_8000E940", size = 224 },
  { name = "osEPiRawStartDma", size = 560 },
  { name = "func_8000EC50", size = 1168 },
  { name = "func_8000F0E0", size = 48 },
  { name = "func_8000F110", size = 140 },
  { name = "func_8000F19C", size = 376 },
  { name = "func_8000F314", size = 116 },
  { name = "func_8000F388", size = 392 },
  { name = "func_8000F510", size = 320 },
  { name = "func_8000F650", size = 16 },
  { name = "func_8000F660", size = 864 },
  { name = "osGetCount", size = 16 },
  { name = "func_8000F9D0", size = 16 },
  { name = "_bcopy", size = 784 },
  { name = "osVirtualToPhysical", size = 128 },
  { name = "func_8000FD70", size = 16 },
  { name = "__osSpSetPc", size = 64 },
  { name = "func_8000FDC0", size = 144 },
  { name = "func_8000FE50", size = 48 },
  { name = "func_8000FE80", size = 48 },
  { name = "func_8000FEB0", size = 16 },
  { name = "osSetTimer", size = 224 },
  { name = "func_8000FFA0", size = 176 },
  { name = "func_80010050", size = 80 },
  { name = "func_800100A0", size = 68 },
  { name = "func_800100E4", size = 44 },
  { name = "func_80010110", size = 172 },
  { name = "func_800101BC", size = 112 },
  { name = "func_8001022C", size = 292 },
  { name = "func_80010350", size = 140 },
  { name = "func_800103DC", size = 116 },
  { name = "func_80010450", size = 16 },
  { name = "func_80010460", size = 80 },
  { name = "func_800104B0", size = 128 },
  { name = "func_80010530", size = 176 },
  { name = "func_800105E0", size = 160 },
  { name = "func_80010680", size = 144 },
  { name = "func_80010710", size = 232 },
  { name = "func_800107F8", size = 328 },
  { name = "func_80010940", size = 80 },
  { name = "func_80010990", size = 240 },
  { name = "func_80010A80", size = 144 },
  { name = "func_80010B10", size = 160 },
  { name = "func_80010BB0", size = 16 },
  { name = "func_80010BC0", size = 144 },
  { name = "func_80010C50", size = 48 },
  { name = "func_80010C80", size = 68 },
  { name = "func_80010CC4", size = 84 },
  { name = "func_80010D18", size = 84 },
  { name = "func_80010D6C", size = 136 },
  { name = "func_80010DF4", size = 168 },
  { name = "func_80010E9C", size = 164 },
  { name = "func_80010F40", size = 160 },
  { name = "func_80010FE0", size = 1088 },
  { name = "func_80011420", size = 160 },
  { name = "func_800114C0", size = 48 },
  { name = "func_800114F0", size = 288 },
  { name = "func_80011610", size = 468 },
  { name = "func_800117E4", size = 940 },
  { name = "func_80011B90", size = 300 },
  { name = "func_80011CBC", size = 1188 },
  { name = "func_80012160", size = 236 },
  { name = "func_8001224C", size = 532 },
  { name = "func_80012460", size = 40 },
  { name = "func_80012488", size = 236 },
  { name = "func_80012574", size = 224 },
  { name = "func_80012654", size = 464 },
  { name = "func_80012824", size = 664 },
  { name = "func_80012ABC", size = 176 },
  { name = "func_80012B6C", size = 1364 },
  { name = "func_800130C0", size = 48 },
  { name = "func_800130F0", size = 224 },
  { name = "func_800131D0", size = 52 },
  { name = "func_80013204", size = 140 },
  { name = "func_80013290", size = 272 },
  { name = "func_800133A0", size = 92 },
  { name = "func_800133FC", size = 104 },
  { name = "func_80013464", size = 1048 },
  { name = "func_8001387C", size = 408 },
  { name = "func_80013A14", size = 604 },
  { name = "func_80013C70", size = 252 },
  { name = "func_80013D6C", size = 800 },
  { name = "func_8001408C", size = 116 },
  { name = "func_80014100", size = 540 },
  { name = "func_8001431C", size = 372 },
  { name = "osPfsIsPlug", size = 416 },
  { name = "func_80014630", size = 252 },
  { name = "func_8001472C", size = 212 },
  { name = "func_80014800", size = 176 },
  { name = "func_800148B0", size = 208 },
  { name = "func_80014980", size = 516 },
  { name = "func_80014B84", size = 380 },
  { name = "func_80014D00", size = 48 },
  { name = "func_80014D30", size = 1700 },
  { name = "func_800153D4", size = 232 },
  { name = "func_800154BC", size = 244 },
  { name = "osDestroyThread", size = 256 },
  { name = "func_800156B0", size = 96 },
  { name = "func_80015710", size = 80 },
  { name = "func_80015760", size = 80 },
  { name = "func_800157B0", size = 80 },
  { name = "func_80015800", size = 80 },
  { name = "func_80015850", size = 16 },
  { name = "func_80015860", size = 192 },
  { name = "func_80015920", size = 128 },
  { name = "func_800159A0", size = 32 },
  { name = "func_800159C0", size = 168 },
  { name = "func_80015A68", size = 184 },
  { name = "func_80015B20", size = 392 },
  { name = "func_80015CA8", size = 396 },
  { name = "func_80015E34", size = 548 },
  { name = "func_80016058", size = 604 },
  { name = "func_800162B4", size = 24 },
  { name = "func_800162CC", size = 836 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
