[input]
entrypoint                = 0x80200400
elf_path                  = "../maddennfl2002/build/maddennfl2002.elf"
rom_file_path             = "../maddennfl2002/baserom.z64"
output_func_path          = "../maddennfl2002pc/RecompiledFuncs"
relocatable_sections_path = "maddennfl2002_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80200400", size = 16 },
  { name = "func_80200410", size = 236 },
  { name = "osAiSetFrequency", size = 132 },
  { name = "func_80200574", size = 420 },
  { name = "func_80200718", size = 512 },
  { name = "func_80200918", size = 324 },
  { name = "func_80200A5C", size = 1008 },
  { name = "func_80200E4C", size = 4 },
  { name = "func_80200E50", size = 128 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "func_8020AFF4", size = 16 },
  { name = "func_8020B39C", size = 16 },
  { name = "func_8020E1E8", size = 80 },
  { name = "func_8020E424", size = 16 },
  { name = "func_80211AE8", size = 16 },
  { name = "func_8021265C", size = 64 },
  { name = "func_80213280", size = 16 },
  { name = "func_80215FF8", size = 16 },
  { name = "func_80219548", size = 72 },
  { name = "func_80219C48", size = 8 },
  { name = "func_8021B044", size = 64 },
  { name = "func_80220400", size = 16 },
  { name = "func_80221940", size = 112 },
  { name = "func_80222B90", size = 16 },
  { name = "func_80227C64", size = 160 },
  { name = "func_8022B50C", size = 16 },
  { name = "func_802380BC", size = 240 },
  { name = "func_80238C2C", size = 32 },
  { name = "func_80238CF4", size = 176 },
  { name = "func_8023AAC0", size = 16 },
  { name = "func_8025405C", size = 160 },
  { name = "func_80255478", size = 60 },
  { name = "func_802554B4", size = 60 },
  { name = "func_802554F0", size = 60 },
  { name = "func_8025552C", size = 60 },
  { name = "func_80255568", size = 60 },
  { name = "func_802555A4", size = 60 },
  { name = "func_802555E0", size = 60 },
  { name = "func_8025561C", size = 60 },
  { name = "func_80255658", size = 60 },
  { name = "func_80255694", size = 60 },
  { name = "func_802556D0", size = 60 },
  { name = "func_8025570C", size = 60 },
  { name = "func_80255748", size = 60 },
  { name = "func_80255784", size = 60 },
  { name = "func_802557C0", size = 60 },
  { name = "func_802557FC", size = 60 },
  { name = "func_80255838", size = 60 },
  { name = "func_80255874", size = 60 },
  { name = "func_802558B0", size = 60 },
  { name = "func_802558EC", size = 60 },
  { name = "func_80255928", size = 60 },
  { name = "func_80255964", size = 60 },
  { name = "func_802559A0", size = 60 },
  { name = "func_802559DC", size = 60 },
  { name = "func_80255A18", size = 60 },
  { name = "func_80255A54", size = 60 },
  { name = "func_80255A90", size = 60 },
  { name = "func_80255ACC", size = 60 },
  { name = "func_80255B08", size = 72 },
  { name = "func_80255B80", size = 92 },
  { name = "func_80255BDC", size = 60 },
  { name = "func_80255C18", size = 72 },
  { name = "func_80258F60", size = 16 },
  { name = "func_80263054", size = 16 },
  { name = "func_80267E5C", size = 16 },
  { name = "func_8026AD14", size = 16 },
  { name = "func_8026B810", size = 96 },
  { name = "func_8026C1F4", size = 16 },
  { name = "func_802726B4", size = 32 },
  { name = "func_8027781C", size = 48 },
  { name = "func_8027D5AC", size = 32 },
  { name = "func_8027DC1C", size = 16 },
  { name = "func_80292608", size = 24 },
  { name = "func_80292620", size = 8 },
  { name = "func_80296C28", size = 32 },
  { name = "func_8029F800", size = 64 },
  { name = "func_802A3034", size = 96 },
  { name = "func_802A5320", size = 16 },
  { name = "func_802AA68C", size = 64 },
  { name = "func_802AE704", size = 48 },
  { name = "func_802AEB08", size = 32 },
  { name = "func_802B5080", size = 112 },
  { name = "func_802B54F4", size = 48 },
  { name = "func_802B68F0", size = 16 },
  { name = "func_802B9EA4", size = 48 },
  { name = "func_802C5FF4", size = 32 },
  { name = "func_802C82C8", size = 16 },
  { name = "func_802C9960", size = 16 },
  { name = "func_802D2214", size = 16 },
  { name = "func_802D2B44", size = 160 },
  { name = "func_802D5F40", size = 32 },
  { name = "func_802DB274", size = 16 },
  { name = "func_802DB880", size = 32 },
  { name = "func_802E8BF4", size = 16 },
  { name = "func_802EF274", size = 16 },
  { name = "func_802F3F1C", size = 112 },
  { name = "func_802F80F8", size = 144 },
  { name = "func_802FD2B8", size = 160 },
  { name = "func_802FEF2C", size = 32 },
]

exact_size_funcs = [

]

[patches]
stubs = [
  "func_802380BC",
]
