[input]
entrypoint                = 0x8004B400
elf_path                  = "../extremegxg2/build/extremegxg2.elf"
rom_file_path             = "../extremegxg2/baserom.z64"
output_func_path          = "../extremegxg2pc/RecompiledFuncs"
relocatable_sections_path = "extremegxg2_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_8004B400", size = 100 },
  { name = "func_8004B464", size = 48 },
  { name = "func_8004B498", size = 436 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
