[input]
entrypoint                = 0x80000400
elf_path                  = "../kigold/build/kigold.elf"
rom_file_path             = "../kigold/baserom.z64"
output_func_path          = "../kigoldpc/RecompiledFuncs"
relocatable_sections_path = "kigold_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80000400", size = 80 },
  { name = "func_80000458", size = 84 },
  { name = "func_800004AC", size = 116 },
  { name = "func_80000520", size = 204 },
  { name = "func_800005EC", size = 196 },
  { name = "func_800006B0", size = 76 },
  { name = "func_800006FC", size = 68 },
  { name = "func_80000740", size = 116 },
  { name = "func_800007B4", size = 332 },
  { name = "func_80000900", size = 96 },
  { name = "func_80000960", size = 1600 },
  { name = "func_80000FA0", size = 1136 },
  { name = "func_80001410", size = 340 },
  { name = "func_80001564", size = 360 },
  { name = "func_800016CC", size = 1316 },
  { name = "func_80001BF0", size = 288 },
  { name = "func_80001D10", size = 224 },
  { name = "func_80001DF0", size = 260 },
  { name = "func_80001EF4", size = 56 },
  { name = "func_80001F2C", size = 916 },
  { name = "func_800022C0", size = 352 },
  { name = "func_80002420", size = 368 },
  { name = "osInitialize", size = 560 },
  { name = "osCreateThread", size = 336 },
  { name = "osStartThread", size = 336 },
  { name = "osSetThreadPri", size = 296 },
  { name = "func_80002B80", size = 160 },
  { name = "osInvalICache", size = 128 },
  { name = "osInvalDCache", size = 176 },
  { name = "osCreatePiManager", size = 384 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "osPiStartDma", size = 272 },
  { name = "osRecvMesg", size = 320 },
  { name = "func_80003150", size = 44 },
  { name = "func_8000317C", size = 40 },
  { name = "func_800031A4", size = 76 },
  { name = "osCreateViManager", size = 400 },
  { name = "func_80003374", size = 476 },
  { name = "osSetEventMesg", size = 112 },
  { name = "osViSetEvent", size = 112 },
  { name = "osSpTaskYield", size = 36 },
  { name = "func_80003650", size = 284 },
  { name = "osSpTaskLoad", size = 352 },
  { name = "osSpTaskStartGo", size = 68 },
  { name = "osSendMesg", size = 336 },
  { name = "osSpTaskYielded", size = 128 },
  { name = "osViSwapBuffer", size = 80 },
  { name = "osViGetNextFramebuffer", size = 64 },
  { name = "osViGetCurrentFramebuffer", size = 64 },
  { name = "osDpSetNextBuffer", size = 176 },
  { name = "osViSetMode", size = 112 },
  { name = "func_80003CD0", size = 16 },
  { name = "func_80003CE0", size = 16 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_80003D00", size = 80 },
  { name = "func_80003D50", size = 80 },
  { name = "func_80003DA0", size = 16 },
  { name = "func_800042F8", size = 232 },
  { name = "func_800043E0", size = 144 },
  { name = "func_80004470", size = 72 },
  { name = "func_800044B8", size = 16 },
  { name = "func_800044C8", size = 320 },
  { name = "osWritebackDCache", size = 136 },
  { name = "func_80004690", size = 96 },
  { name = "func_800046F0", size = 96 },
  { name = "func_80004750", size = 44 },
  { name = "__ull_rem", size = 60 },
  { name = "__ull_div", size = 72 },
  { name = "func_800047F4", size = 44 },
  { name = "func_80004820", size = 60 },
  { name = "__ll_div", size = 72 },
  { name = "__ll_mul", size = 60 },
  { name = "func_800048E8", size = 96 },
  { name = "func_80004948", size = 156 },
  { name = "func_800049E4", size = 44 },
  { name = "__osDisableInt", size = 32 },
  { name = "__osRestoreInt", size = 40 },
  { name = "func_80004A50", size = 64 },
  { name = "func_80004A90", size = 80 },
  { name = "func_80004AE0", size = 68 },
  { name = "func_80004B24", size = 44 },
  { name = "osGetThreadPri", size = 32 },
  { name = "func_80004B70", size = 224 },
  { name = "func_80004C50", size = 384 },
  { name = "osJamMesg", size = 336 },
  { name = "func_80004F20", size = 48 },
  { name = "func_80004F50", size = 140 },
  { name = "func_80004FDC", size = 376 },
  { name = "func_80005154", size = 116 },
  { name = "func_800051C8", size = 392 },
  { name = "func_80005350", size = 304 },
  { name = "func_80005480", size = 16 },
  { name = "func_80005490", size = 864 },
  { name = "osGetCount", size = 16 },
  { name = "func_80005800", size = 16 },
  { name = "func_80005810", size = 784 },
  { name = "osVirtualToPhysical", size = 128 },
  { name = "__osSpSetPc", size = 64 },
  { name = "func_80005BE0", size = 144 },
  { name = "func_80005C70", size = 48 },
  { name = "func_80005CA0", size = 16 },
  { name = "func_80005CB0", size = 48 },
  { name = "func_80005CE0", size = 48 },
  { name = "func_80005D10", size = 48 },
  { name = "func_80005D40", size = 88 },
  { name = "func_80005D98", size = 192 },
  { name = "func_80005E58", size = 216 },
  { name = "func_80005F30", size = 76 },
  { name = "func_80005F7C", size = 44 },
  { name = "func_80005FA8", size = 488 },
  { name = "func_80006190", size = 304 },
  { name = "osSetIntMask", size = 96 },
  { name = "osDestroyThread", size = 256 },
  { name = "func_80006420", size = 16 },
  { name = "func_80006430", size = 192 },
  { name = "func_800064F0", size = 16 },
  { name = "func_80006500", size = 96 },
  { name = "func_80012428", size = 80 },
  { name = "func_80044CA0", size = 16 },
  { name = "func_800846F4", size = 16 },
  { name = "func_800B818C", size = 144 },
  { name = "func_800D9E7C", size = 16 },
  { name = "func_800DBBF0", size = 32 },
  { name = "func_800DBC8C", size = 64 },
  { name = "func_800DBE64", size = 176 },
  { name = "func_800F96EC", size = 16 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
