//
// plume
//
// Copyright (c) 2024 renderbag and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file for details.
//

#include <filesystem>
#include <fstream>
#include <cstdio>
#include <vector>

std::vector<char> read_file(const char* path) {
    std::ifstream input_file{path, std::ios::binary};
    std::vector<char> ret{};

    if (!input_file.good()) {
        return ret;
    }

    // Get the length of the file
    input_file.seekg(0, std::ios::end);
    ret.resize(input_file.tellg());

    // Read the file contents into the vector
    input_file.seekg(0, std::ios::beg);
    input_file.read(ret.data(), ret.size());

    return ret;
}

void create_parent_if_needed(const char* path) {
    std::filesystem::path parent_path = std::filesystem::path{path}.parent_path();
    if (!parent_path.empty()) {
        std::filesystem::create_directories(parent_path);
    }
}

int main(int argc, const char** argv) {
    if (argc < 5 || argc > 6) {
        printf("Usage: %s [input file] [array name] [output C file] [output C header] [--text]\n", argv[0]);
        printf("  --text: Use 'char' instead of 'unsigned char' for text data compatibility\n");
        return EXIT_SUCCESS;
    }

    const char* input_path = argv[1];
    const char* array_name = argv[2];
    const char* output_c_path = argv[3];
    const char* output_h_path = argv[4];
    bool use_char = (argc == 6 && std::string(argv[5]) == "--text");

    // Read the input file's contents
    std::vector<char> contents = read_file(input_path);

    if (contents.empty()) {
        fprintf(stderr, "Failed to open file %s! (Or it's empty)\n", input_path);
        return EXIT_FAILURE;
    }

    // Create the output directories if they don't exist
    create_parent_if_needed(output_c_path);
    create_parent_if_needed(output_h_path);

    const char* type_name = use_char ? "char" : "unsigned char";

    // Write the C file with the array and size
    {
        std::ofstream output_c_file{output_c_path};
        output_c_file << "// Auto-generated by plume file_to_c - do not edit\n\n";
        output_c_file << "#include <stddef.h>\n\n";
        output_c_file << "const " << type_name << " " << array_name << "[" << contents.size() << "] = {";

        for (size_t i = 0; i < contents.size(); ++i) {
            if (i % 16 == 0) {
                output_c_file << "\n    ";
            }
            output_c_file << (int)(unsigned char)contents[i] << ",";
            if (i % 16 != 15 && i != contents.size() - 1) {
                output_c_file << " ";
            }
        }

        output_c_file << "\n};\n\n";
        output_c_file << "const size_t " << array_name << "_size = " << contents.size() << ";\n";
    }

    // Write the header file with the extern declarations
    {
        std::ofstream output_h_file{output_h_path};
        output_h_file << "// Auto-generated by plume file_to_c - do not edit\n\n";
        output_h_file << "#pragma once\n\n";
        output_h_file << "#include <stddef.h>\n\n";
        output_h_file <<
            "#ifdef __cplusplus\n"
            "extern \"C\" {\n"
            "#endif\n\n"
            "extern const " << type_name << " " << array_name << "[" << contents.size() << "];\n"
            "extern const size_t " << array_name << "_size;\n\n"
            "#ifdef __cplusplus\n"
            "}\n"
            "#endif\n";
    }

    return EXIT_SUCCESS;
}
