[input]
entrypoint                = 0x80300000
elf_path                  = "../mariotennis/build/mariotennis.elf"
rom_file_path             = "../mariotennis/baserom.z64"
output_func_path          = "../mariotennispc/RecompiledFuncs"
relocatable_sections_path = "mariotennis_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80300000", size = 80 },
  { name = "func_80300080", size = 544 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "func_803002D0", size = 128 },
  { name = "func_80303018", size = 16 },
  { name = "func_80311514", size = 6160 },
  { name = "func_80312D24", size = 5912 },
  { name = "func_8031B0A4", size = 16 },
  { name = "func_8031D548", size = 128 },
  { name = "func_8032D800", size = 80 },
  { name = "func_8032E9C8", size = 16 },
  { name = "func_803302A0", size = 16 },
  { name = "func_80332270", size = 32 },
  { name = "func_80335FF4", size = 16 },
  { name = "func_80339AA4", size = 64 },
  { name = "func_80339EB4", size = 16 },
  { name = "func_8033A0B8", size = 96 },
  { name = "func_8033A6E8", size = 16 },
  { name = "func_80340828", size = 8 },
  { name = "func_803414A8", size = 16 },
  { name = "func_80341B98", size = 32 },
  { name = "func_80342448", size = 48 },
  { name = "func_80342948", size = 8 },
  { name = "func_80344928", size = 8 },
  { name = "func_80344930", size = 8 },
  { name = "func_80347D08", size = 8 },
  { name = "func_80351748", size = 16 },
  { name = "func_80351AD8", size = 32 },
  { name = "func_80354290", size = 4 },
  { name = "func_80354294", size = 1404 },
  { name = "func_803593AC", size = 48 },
  { name = "func_8036E718", size = 32 },
  { name = "func_80375B64", size = 304 },
  { name = "func_80384100", size = 16 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
