/**
 * main.cpp — Nightmare Creatures PC port entry point. Generated by recompilator/scaffold_app.py.
 *
 * The MINIMAL game profile (the sm64pc/lodpc pattern): ROM identity/validation,
 * recompiled-section registration, renderer/audio/input wiring, the entrypoint, a
 * crash handler, and diagnostic logging. Every game-specific value below comes from
 * recon (ROM header, XXH3, entrypoint) — there are NO addresses from any other game.
 *
 * Engine: ../engine (the single agnostic engine: rt64 + runtime). Cross-platform by
 * construction — Windows / Linux / macOS / Linux-ARM. Pick a target with the
 * CMakePresets in this directory (e.g. `cmake --preset linux-arm64`). Keep this file free
 * of throwaway debug probes; put those behind an env var in the engine, or a local edit.
 */

#if defined(_WIN32)
#include <Windows.h>
#include <commdlg.h>   // OPENFILENAMEA / GetOpenFileNameA
#endif
#include <string>
#include <filesystem>
#include <cstdlib>
#include <cstdio>
#include <atomic>

#define SDL_MAIN_HANDLED
#include "SDL.h"
#include "SDL_syswm.h"

#include "recomp.h"
#include "librecomp/game.hpp"
#include "librecomp/overlays.hpp"
#include "librecomp/diag_cap.h"   // console seam ported from snowkidspc (2026-07-31 batch)
#include "librecomp/sections.h"
#include "ultramodern/ultramodern.hpp"
#include "ultramodern/renderer_context.hpp"
#include "ultramodern/error_handling.hpp"

#ifndef RDPC_CONSOLE_ONLY
#include "rt64_renderer.hpp"
#endif

ultramodern::audio_callbacks_t    get_audio_callbacks();
ultramodern::input::callbacks_t   get_input_callbacks();
recomp::rsp::callbacks_t          get_rsp_callbacks();
void nightmare_audio_init();
void nightmare_input_init();

// ── Nightmare Creatures game identity (recon: ROM header + XXH3) ───────────────────────
// SHA1: bea6c21b3ef5950bdf8cdb255955da6c4746eea8 · internal name "Nightmare Creatures"
static constexpr uint64_t NIGHTMARE_ROM_HASH        = 0x260851F60FE541D8ULL;
static constexpr uint32_t NIGHTMARE_ENTRYPOINT_VRAM = 0x80000400;

extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);

// NC bare-metal dispatcher: a clean no-op pinned at the `jr $s2` RETURN addresses of func_80080D7C's
// call sites (0x80080B5C / 0x80080C04). func_80080D7C's `jr $s2` is a plain function return (it saved
// $ra into $s2 on entry); rendered as LOOKUP_FUNC(ctx->r18) it would otherwise miss and interpret —
// double-running the dispatcher tail and creating the eret-mid-interp run-queue tear. See the pin site
// in nightmare_app_main for the full rationale.
static void nc_dispatch_return_noop(uint8_t* /*rdram*/, recomp_context* /*ctx*/) {}

// Cross-platform putenv for the NC bare-metal env pins below: _putenv is MSVC-CRT-only.
// POSIX putenv keeps the pointer — all call sites pass string literals (static storage).
// console seam ported from snowkidspc (2026-07-31 batch)
static void nc_putenv(const char* kv) {
#if defined(_WIN32)
    _putenv(kv);
#else
    putenv(const_cast<char*>(kv));
#endif
}

#include "recomp_overlays.inl"

// console seam ported from snowkidspc (2026-07-31 batch)
#ifdef RDPC_CAPTURE_CHAIN
#include "lle_console.h"   // preservation-core console renderer (RDPC_LLE_CONSOLE=1) + blit_tick
#include "console_input.h" // the evdev input organ -- lets console mode run with no SDL video at all
#endif

static SDL_Window* sdl_window = nullptr;
extern std::atomic<double> g_cv64_present_fps;   // present-FPS counter (engine global)

// Cross-platform error dialog: native MessageBox on Windows, SDL elsewhere.
static void nightmare_show_error(const char* title, const char* msg) {
#if defined(_WIN32)
    MessageBoxA(nullptr, msg, title, MB_ICONERROR | MB_OK);
#else
    SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, title, msg, nullptr);
#endif
}

static ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
// console seam ported from snowkidspc (2026-07-31 batch)
#ifdef RDPC_CONSOLE_ONLY
    // THE CONSOLE CONTRACT (2026-07-25). SDL video was kept alive here for exactly one
    // reason: SDL's keyboard and gamepad state ride the video backend, so skipping it
    // starved input (the 07-24 lesson). The cost was DRM master -- which the presentation
    // organ needs to own the mode and the scanout. preservation_core::input reads
    // controllers straight from the kernel, so that dependency is gone: when the organ
    // comes up, SDL video is never initialised and DRM master is free to take.
    if (preservation_core::input::init()) {
        // GPU-present tier (repc 4K: GPU upscale via SDL_Renderer) still needs SDL video even
        // though the evdev organ owns input -- only the organ-scanout path frees DRM master.
        const char* gp = std::getenv("RDPC_LLE_GPU_PRESENT");
        if (gp == nullptr || gp[0] != (char)49) {
            return nullptr;
        }
    }
    fprintf(stderr, "[console] input organ opened no devices -- keeping SDL video so input still works\n");
#endif
    if (SDL_InitSubSystem(SDL_INIT_VIDEO) != 0) {
        nightmare_show_error("SDL_InitSubSystem Error", SDL_GetError());
    }
    return nullptr;
}

static ultramodern::renderer::WindowHandle
create_window(ultramodern::gfx_callbacks_t::gfx_data_t /*gfx_data*/)
{
// console seam ported from snowkidspc (2026-07-31 batch)
#ifdef RDPC_CONSOLE_ONLY
    // Organ up => no SDL video => no window to create. The presentation organ scans out
    // directly. Window consumers are already null-safe (blit_tick early-returns; the FPS
    // title is guarded on a non-null window).
    if (preservation_core::input::active()) {
        const char* gp = std::getenv("RDPC_LLE_GPU_PRESENT");   // GPU tier keeps its window
        if (gp == nullptr || gp[0] != (char)49) {
            return nullptr;
        }
    }
#endif
    Uint32 win_flags = SDL_WINDOW_RESIZABLE;
#if !defined(_WIN32)
    win_flags |= SDL_WINDOW_VULKAN;   // Linux + macOS (MoltenVK) render via Vulkan
#endif
#ifdef RDPC_CAPTURE_CHAIN
    if (preservation_core::lleconsole::active()) {
        // Console mode (RDPC_LLE_CONSOLE=1): no Vulkan window; GL only for the accelerated
        // upscale presenter (RDPC_LLE_GPU_PRESENT=1). Ported verbatim from starfox64pc (game #6).
        win_flags = SDL_WINDOW_RESIZABLE;
        if (const char* fs = std::getenv("RDPC_LLE_FULLSCREEN"); fs && fs[0] == '1')
            win_flags |= SDL_WINDOW_FULLSCREEN_DESKTOP;
        if (const char* gp = std::getenv("RDPC_LLE_GPU_PRESENT"); gp && gp[0] == '1')
            win_flags |= SDL_WINDOW_OPENGL;
    }
#endif
    sdl_window = SDL_CreateWindow(
        "Nightmare Creatures PC",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        1920, 1080,
        win_flags);
    if (!sdl_window) {
        nightmare_show_error("Window Creation Error", SDL_GetError());
        std::exit(1);
    }

#if defined(_WIN32)
    SDL_SysWMinfo wm_info;
    SDL_VERSION(&wm_info.version);
    SDL_GetWindowWMInfo(sdl_window, &wm_info);
    return ultramodern::renderer::WindowHandle{
        wm_info.info.win.window,
        GetCurrentThreadId()
    };
#elif defined(__APPLE__)
    SDL_SysWMinfo wm_info;
    SDL_VERSION(&wm_info.version);
    SDL_GetWindowWMInfo(sdl_window, &wm_info);
    SDL_MetalView mv = SDL_Metal_CreateView(sdl_window);   // CAMetalLayer-backed view for MoltenVK
    return ultramodern::renderer::WindowHandle{ wm_info.info.cocoa.window, SDL_Metal_GetLayer(mv) };
#else
    return sdl_window;   // ultramodern::renderer::WindowHandle == SDL_Window* on Linux/Android
#endif
}

static void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t /*gfx_data*/) {
    SDL_Event evt;
    while (SDL_PollEvent(&evt)) {
        if (evt.type == SDL_QUIT) {
            ultramodern::quit();
        }
    }
// console seam ported from snowkidspc (2026-07-31 batch)
#ifdef RDPC_CAPTURE_CHAIN
    // Console mode: present the latest VI frame from the preservation core (owner thread).
    preservation_core::lleconsole::blit_tick(sdl_window);
#endif
    {
        static double last_fps = -1.0;
        double fps = g_cv64_present_fps.load(std::memory_order_relaxed);
        if (sdl_window != nullptr && fps != last_fps) {
            last_fps = fps;
            char title[80];
            snprintf(title, sizeof(title), "Nightmare Creatures PC  -  %.1f FPS", fps);
            SDL_SetWindowTitle(sdl_window, title);
        }
    }
}

static void nightmare_message_box(const char* msg) {
    nightmare_show_error("Nightmare Creatures — Error", msg);
}

// console seam ported from snowkidspc (2026-07-31 batch)
static std::unique_ptr<ultramodern::renderer::RendererContext>
nightmare_create_render_context(uint8_t* rdram, ultramodern::renderer::WindowHandle window_handle, bool developer_mode) {
#ifdef RDPC_CAPTURE_CHAIN
    // Console mode (RDPC_LLE_CONSOLE=1): the preservation-core console replaces RT64 entirely.
    if (preservation_core::lleconsole::active()) {
        // Game-agnostic submit seam (organ Move 1): register before the first send_dl.
        extern void nightmare_lle_console_submit();
        preservation_core::lleconsole::set_submit_callback(&nightmare_lle_console_submit);
        return preservation_core::lleconsole::create_console_context(rdram);
    }
#endif
#ifdef RDPC_CONSOLE_ONLY
    // PLAN V3 amendment A: no RT64 in this binary. Console mode is the only renderer.
    nightmare_show_error("Renderer", "Console-only build: set RDPC_LLE_CONSOLE=1.");
    std::exit(1);
#else
    return nightmare::renderer::create_render_context(rdram, window_handle, developer_mode);
#endif
}

#if defined(_WIN32)
static LONG WINAPI nightmare_unhandled_exception(EXCEPTION_POINTERS* ep) {
    fflush(stderr);
    DWORD  code = ep->ExceptionRecord->ExceptionCode;
    void*  addr = ep->ExceptionRecord->ExceptionAddress;
    ULONG_PTR* info = ep->ExceptionRecord->ExceptionInformation;
    HMODULE hmod = nullptr;
    GetModuleHandleExA(
        GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
        GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
        (LPCSTR)addr, &hmod);
    ULONG_PTR rva = hmod ? (ULONG_PTR)addr - (ULONG_PTR)hmod : 0;
    char detail[64] = "";
    if (code == EXCEPTION_ACCESS_VIOLATION && ep->ExceptionRecord->NumberParameters >= 2) {
        snprintf(detail, sizeof(detail), "\nAccess: %s 0x%llX",
            info[0] == 0 ? "READ" : "WRITE", (unsigned long long)info[1]);
    }
    char msg[1024];
    snprintf(msg, sizeof(msg),
        "UNHANDLED EXCEPTION\n\nCode:        0x%08X\nAddress:     0x%p\n"
        "RVA (map):   0x%08llX%s\n\nThis offset matches a line in nightmarepc.map.\n"
        "Compare Address against the exe base BEFORE map lookups.\n\nThread: %u",
        code, addr, (unsigned long long)rva, detail, GetCurrentThreadId());
    fprintf(stderr, "%s\n", msg);
    fflush(stderr);
    __try {
        HMODULE exe = GetModuleHandleA(nullptr);
        CONTEXT* ctx = ep->ContextRecord;
        if (exe != nullptr && ctx != nullptr) {
            const uintptr_t* sp = (const uintptr_t*)ctx->Rsp;
            fprintf(stderr, "[crashstack] Rsp=0x%p — call sites in nightmarepc.exe (base=0x%p), nearest first:\n",
                    (void*)ctx->Rsp, (void*)exe);
            int found = 0;
            for (int i = 0; i < 128 && found < 16; i++) {
                uintptr_t ret = sp[i];
                HMODULE m = nullptr;
                if (GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                                       GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                                       (LPCSTR)ret, &m) && m == exe) {
                    fprintf(stderr, "[crashstack]   stack+0x%03X  RVA=0x%08llX\n",
                            (unsigned)(i * 8), (unsigned long long)(ret - (uintptr_t)exe));
                    found++;
                }
            }
            fprintf(stderr, "[crashstack] (%d call sites found)\n", found);
            fflush(stderr);
        }
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        fprintf(stderr, "[crashstack] (stack scan faulted — Rsp corrupt)\n"); fflush(stderr);
    }
    MessageBoxA(nullptr, msg, "Nightmare Creatures — Crash", MB_ICONERROR | MB_OK);
    return EXCEPTION_CONTINUE_SEARCH;
}
#endif // _WIN32 (crash handler)

static void nightmare_vi_callback() {}
static void nightmare_gfx_init_callback() {}

static std::string nightmare_get_thread_name(const OSThread* t) {
    return "nightmare_" + std::to_string(t->id);
}

static void prompt_for_rom(const char* rom_hint) {
    std::filesystem::path rom_path;

#if defined(_WIN32)
    if (rom_hint && *rom_hint) {
        rom_path = rom_hint;
    } else {
        OPENFILENAMEA ofn   = {};
        char          path[MAX_PATH] = {};
        ofn.lStructSize = sizeof(ofn);
        ofn.lpstrFilter = "N64 ROM Files\0*.z64;*.n64;*.v64\0All Files\0*.*\0";
        ofn.lpstrFile   = path;
        ofn.nMaxFile    = MAX_PATH;
        ofn.lpstrTitle  = "Select Nightmare Creatures ROM";
        ofn.Flags       = OFN_FILEMUSTEXIST | OFN_PATHMUSTEXIST;
        if (!GetOpenFileNameA(&ofn)) {
            nightmare_show_error("ROM Required",
                "A Nightmare Creatures ROM is required.\n"
                "Please supply your own legally obtained copy.");
            std::exit(0);
        }
        rom_path = path;
    }
#else
    // No native file dialog wired off Windows: take the ROM path from argv[1] or the
    // NIGHTMARE_ROM env var (e.g. an SBC/console that already has the ROM at a known path).
    if (!rom_hint || !*rom_hint) rom_hint = std::getenv("NIGHTMARE_ROM");
    if (!rom_hint || !*rom_hint) {
        nightmare_show_error("ROM Required",
            "Pass the Nightmare Creatures ROM path as the first argument,\n"
            "or set the NIGHTMARE_ROM environment variable.");
        std::exit(0);
    }
    rom_path = rom_hint;
#endif

    std::u8string out_id = u8"nightmare_us";
    auto err = recomp::select_rom(rom_path, out_id);
    switch (err) {
    case recomp::RomValidationError::Good:
        return;
    case recomp::RomValidationError::IncorrectRom:
    case recomp::RomValidationError::IncorrectVersion:
        nightmare_show_error("Wrong ROM",
            "The selected ROM does not match Nightmare Creatures.\n"
            "Expected SHA1: bea6c21b3ef5950bdf8cdb255955da6c4746eea8");
        std::exit(1);
    case recomp::RomValidationError::NotARom:
        nightmare_show_error("Not an N64 ROM", "The selected file does not appear to be an N64 ROM.");
        std::exit(1);
    default:
        nightmare_show_error("ROM Error", "Failed to read the selected ROM file.");
        std::exit(1);
    }
}

static int nightmare_app_main(int argc, char** argv)
{
    const char* rom_hint = (argc > 1) ? argv[1] : nullptr;

#if defined(_WIN32)
    SetUnhandledExceptionFilter(nightmare_unhandled_exception);
#endif
    SDL_SetMainReady();

#if defined(_WIN32)
    const char* appdata = std::getenv("APPDATA");
    if (!appdata) appdata = ".";
    std::filesystem::path config_path = std::filesystem::path(appdata) / "nightmarepc";
#else
    const char* xdg  = std::getenv("XDG_CONFIG_HOME");
    const char* home = std::getenv("HOME");
    std::filesystem::path config_base =
        (xdg && *xdg) ? std::filesystem::path(xdg)
                      : (home ? std::filesystem::path(home) / ".config"
                              : std::filesystem::path("."));
    std::filesystem::path config_path = config_base / "nightmarepc";
#endif
    std::filesystem::create_directories(config_path);

    {
        std::filesystem::path log_path = config_path / "nightmarepc_diag.log";
        FILE* f = nullptr;
#if defined(_WIN32)
        freopen_s(&f, log_path.string().c_str(), "w", stderr);
#else
        f = freopen(log_path.string().c_str(), "w", stderr);
#endif
        if (f) { setvbuf(f, nullptr, _IONBF, 0); fprintf(stderr, "[nightmarepc] diagnostic log started\n"); }
        recomp::diag_log_cap(log_path.string());   // console seam ported from snowkidspc (2026-07-31 batch)
        std::filesystem::path stdout_path = config_path / "nightmarepc_stdout.log";
        FILE* fout = nullptr;
#if defined(_WIN32)
        freopen_s(&fout, stdout_path.string().c_str(), "w", stdout);
#else
        fout = freopen(stdout_path.string().c_str(), "w", stdout);
#endif
        if (fout) { setvbuf(fout, nullptr, _IONBF, 0); fprintf(stdout, "[nightmarepc] stdout log started\n"); }
    }

    recomp::register_config_path(config_path);

    recomp::GameEntry entry{};
    entry.rom_hash           = NIGHTMARE_ROM_HASH;
    entry.internal_name      = "Nightmare Creatures";
    entry.game_id            = u8"nightmare_us";
    entry.mod_game_id        = "";
    entry.save_type          = recomp::SaveType::None;
    entry.is_enabled         = true;
    entry.entrypoint_address = NIGHTMARE_ENTRYPOINT_VRAM;
    entry.entrypoint         = recomp_entrypoint;
    recomp::register_game(entry);

    recomp::overlays::register_overlays(
        recomp::overlays::overlay_section_table_data_t{
            .code_sections      = section_table,
            .num_code_sections  = sizeof(section_table) / sizeof(section_table[0]),
            .total_num_sections = num_sections,
        },
        recomp::overlays::overlays_by_index_t{
            .table = overlay_sections_by_index,
            .len   = sizeof(overlay_sections_by_index) / sizeof(overlay_sections_by_index[0]),
        });

    recomp::check_all_stored_roms();
    std::u8string game_id = u8"nightmare_us";
    if (!recomp::is_rom_valid(game_id)) {
        prompt_for_rom(rom_hint);
        recomp::check_all_stored_roms();
        if (!recomp::is_rom_valid(game_id)) {
            nightmare_show_error("Error", "ROM validation failed after selection.");
            return 1;
        }
    }

    SDL_Init(SDL_INIT_AUDIO);
    nightmare_audio_init();
    nightmare_input_init();

    recomp::start_game(game_id);

    recomp::Configuration cfg{};
    cfg.project_version      = { 0, 1, 0, "" };
    cfg.rsp_callbacks        = get_rsp_callbacks();
    cfg.renderer_callbacks   = { .create_render_context = nightmare_create_render_context };   // console seam ported from snowkidspc (2026-07-31 batch)
    cfg.audio_callbacks      = get_audio_callbacks();
    cfg.input_callbacks      = get_input_callbacks();
    cfg.gfx_callbacks        = {
        .create_gfx    = create_gfx,
        .create_window = create_window,
        .update_gfx    = update_gfx,
    };
    cfg.events_callbacks     = {
        .vi_callback       = nightmare_vi_callback,
        .gfx_init_callback = nightmare_gfx_init_callback,
    };
    cfg.error_handling_callbacks = { .message_box = nightmare_message_box };
    cfg.threads_callbacks    = { .get_game_thread_name = nightmare_get_thread_name };
    cfg.message_queue_control = {
        .requeue_timer = true,
        .requeue_sp    = true,
        .requeue_si    = true,
        .requeue_ai    = false,
        .requeue_vi    = false,
        .requeue_pi    = false,
        .requeue_dp    = true,
    };

    // Bare-metal interrupt delivery: Nightmare Creatures has no libultra VI manager — it runs its own exception
    // handler and spins waiting for it to post the VI event. Wire the engine's raw RCP-interrupt delivery
    // (recomp_deliver_rcp_interrupt, gated on NC_IRQ) to NC's exception dispatcher at 0x80080454 (the entry the
    // retail 0x80000180 vector jumps to). Cause stays the engine default 0x400 (IP2/RCP). The dispatcher runs
    // via the in-section interpreter (its $k0/$k1/ERET exception code does not yet recompile correctly native).
    nc_putenv("NC_IRQ=0x80080454");

    // Bare-metal cooperative scheduler (project_nightmare_baremetal RUN 22): NC context-switches its tasks
    // via guest `eret`. The recompiler emits eret as a fiber switch (recomp_eret); point it at NC's
    // "current task" pointer (D_800A36B0) so it keys each task's fiber. The game-thread idle drains NC's
    // __osException natively (yield-drain). General mechanism (librecomp/baremetal_sched.cpp); per-game datum.
    nc_putenv("RECOMP_BAREMETAL_TASKPTR=0x800A36B0");

    // Frame pacing (RUN 34): NC is a 30fps title whose logic rate is EMERGENT from gfx-task completion
    // latency — on hardware the RDP takes most of a frame so the OSSched fb-swap gate paces it to 30;
    // our instant RT64 completion let it free-run at 60 = 2x cutscene/menu speed (observed).
    // Flat 30fps grid via the ultramodern frame governor (value = fps => no DK64 mode read, no dip).
    if (getenv("RECOMP_FRAME_GOVERNOR") == nullptr) {
        nc_putenv("RECOMP_FRAME_GOVERNOR=30");
    }

    // ── Bare-metal exception handler: PIN it native ──────────────────────────────
    // NC's __osException handler (section_18_main_80080280, vram 0x80080280) runs
    // the cooperative scheduler's eret. recomp_baremetal_idle() resolves it via
    // recomp_lookup_native(0x80080454); a func_map miss falls to recomp_interpret(),
    // and the interpreter cannot execute the guest `eret` at 0x80081144 inside
    // func_80080FEC ("[interp] abort ... derail contained") so the handler never
    // posts the SP/DP-done event and ORIGIN stays stuck at 0x280. Pinning these
    // emitted func-start vrams forces recomp_lookup_native (and get_function) to
    // return native for the WHOLE handler chain, so it runs as compiled C: the
    // jr/jtbl interior labels (0x80080B84, 0x80080C7C inside func_80080A88) and the
    // eret at 0x80081144 (inside func_80080FEC) execute as native control flow /
    // the native recomp_eret. pinned_funcs survives func_map.clear() in
    // init_overlays(), so this is robust regardless of the init/DMA registration
    // order. These symbols are declared extern "C" in funcs.h (pulled in via the
    // #include "recomp_overlays.inl" above), so they're visible here.
    // Pin ONLY the handler entry. The idle drain does recomp_lookup_native(0x80080454);
    // pinning it makes that resolve to the native func_80080454 (instead of the
    // interp). func_80080454 then C-calls func_80080808 — which is itself a
    // live-gap STUB (the static recompiler could not codegen its $k0/$k1 exception
    // prologue; the LiveGenerator also bails, good=0), so the body runs in the
    // interpreter regardless. Do NOT pin the carved sub-funcs (A88/D7C/F74/FBC/FCC/
    // FEC): once the handler PROLOGUE has run under the interpreter, the guest
    // register/COP0 state is interpreter-resident, and having the interp's do_call
    // jump into a pinned NATIVE sub-func mid-handler runs that compiled C with
    // derailed regs -> a wild absolute-address read (verified crash 0xC0000005 at
    // RVA func_80080F74, called from recomp_interpret<-recomp_live_gap_trampoline).
    // The interpreter-only handler path is self-consistent (it posts 11 valid erets
    // with non-zero EPCs before the derail) and its derail-containment catches the
    // jr/jtbl dead-ends instead of hard-crashing. So pin the entry only.
    recomp::overlays::register_pinned_function(0x80080454, func_80080454); // handler entry (idle's lookup target)

    // ── Bare-metal dispatcher: kill the `jr $s2` RETURN-as-LOOKUP interp/double-run ──────────────
    // func_80080D7C (NC's wake routine: posts the event + priority-inserts the woken TCB into the run
    // queue via func_80080F74) saves $ra into $s2 on entry (`addu $s2,$ra,$zero`) and returns with
    // `jr $s2` — i.e. $s2 IS the return address, so `jr $s2` is a plain function RETURN. But the
    // recompiler renders `jr $s2` as `LOOKUP_FUNC(ctx->r18)(rdram,ctx)` (a tail-dispatch to the
    // RETURN address). func_80080D7C is jal'd from INSIDE native func_80080808 at interior return
    // sites (…+8 of each jal): the two that actually fire are 0x80080B5C and 0x80080C04. Those are
    // NOT registered func entries, so LOOKUP_FUNC misses -> the engine INTERPRETS the dispatcher tail
    // from 0x80080B5C/0x80080C04 — which (a) DOUBLE-RUNs that tail (native func_80080808 also
    // continues there structurally after the call returns) and (b) is the TEAR vector: an `eret`
    // firing inside that interp session ends it mid-flight, leaving the run-queue head torn to
    // 0xFFFFFFFF -> orphaned threads -> the cooperative scheduler FREEZES (audio keeps playing, no
    // gfx). Registering these two RETURN addresses as no-ops makes func_80080D7C's `jr $s2` resolve
    // to a clean return to its native caller (func_80080808), which then continues the dispatcher tail
    // exactly once, natively. NC-only DATA; the mechanism (a pinned no-op) is general. We pin (not
    // func_map-register) so the entries SURVIVE init_overlays()'s func_map.clear() — get_function and
    // recomp_lookup_native both fall back to pinned_funcs on a func_map miss.
    recomp::overlays::register_pinned_function(0x80080B5C, nc_dispatch_return_noop); // ret of `jal func_80080D7C` @0x80080B54
    recomp::overlays::register_pinned_function(0x80080C04, nc_dispatch_return_noop); // ret of `jal func_80080D7C` @0x80080BFC

    recomp::start(cfg);

    SDL_Quit();
    return 0;
}

// ── Entry point: GUI WinMain on Windows, standard main() on Linux/macOS ────────
#if defined(_WIN32)
int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int) {
    return nightmare_app_main(__argc, __argv);   // CRT-provided argc/argv
}
#else
int main(int argc, char** argv) {
    return nightmare_app_main(argc, argv);
}
#endif
