[input]
entrypoint                = 0x80000400
elf_path                  = "../ecwhcr/build/ecwhcr.elf"
rom_file_path             = "../ecwhcr/baserom.z64"
output_func_path          = "../ecwhcrpc/RecompiledFuncs"
relocatable_sections_path = "ecwhcr_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80000400", size = 240 },
  { name = "func_800004F0", size = 112 },
  { name = "func_80000560", size = 112 },
  { name = "func_800005D0", size = 428 },
  { name = "func_8000077C", size = 180 },
  { name = "func_80000830", size = 52 },
  { name = "func_80000864", size = 60 },
  { name = "func_800008A0", size = 36 },
  { name = "func_800008C4", size = 360 },
  { name = "func_80000A2C", size = 36 },
  { name = "func_8000B27C", size = 68 },
  { name = "func_8000B2C0", size = 20 },
  { name = "func_8000B2D4", size = 20 },
  { name = "func_8000B2E8", size = 20 },
  { name = "func_8000B2FC", size = 48 },
  { name = "func_8000B32C", size = 16 },
  { name = "func_8000B33C", size = 16 },
  { name = "func_8000B34C", size = 16 },
  { name = "func_8000B35C", size = 400 },
  { name = "func_8000B4EC", size = 16 },
  { name = "func_8000B4FC", size = 16 },
  { name = "func_8000B50C", size = 16 },
  { name = "func_8000B51C", size = 16 },
  { name = "func_8000B52C", size = 12 },
  { name = "func_8000B538", size = 20 },
  { name = "func_8000B54C", size = 16 },
  { name = "func_8000B55C", size = 4 },
  { name = "func_8000B560", size = 20 },
  { name = "func_8000B574", size = 572 },
  { name = "func_8000B7B0", size = 8 },
  { name = "func_8000B7B8", size = 12 },
  { name = "func_8000B7C4", size = 4 },
  { name = "func_8000B7C8", size = 16 },
  { name = "func_8000B7D8", size = 16 },
  { name = "func_8000B7E8", size = 16 },
  { name = "func_8000BA28", size = 20 },
  { name = "func_8000BA3C", size = 20 },
  { name = "func_8000BA50", size = 20 },
  { name = "func_8000BA64", size = 16 },
  { name = "func_8000BA74", size = 16 },
  { name = "func_8000BA84", size = 16 },
  { name = "func_8000BA94", size = 524 },
  { name = "func_8000BCA0", size = 4 },
  { name = "func_8000BCA4", size = 16 },
  { name = "func_8000BCB4", size = 16 },
  { name = "func_8000BCC4", size = 4 },
  { name = "func_8000BCC8", size = 12 },
  { name = "func_8000BCD4", size = 8 },
  { name = "func_8000BCDC", size = 572 },
  { name = "func_8000BF18", size = 16 },
  { name = "func_8000BF28", size = 4 },
  { name = "func_8000BF2C", size = 12 },
  { name = "func_8000BF38", size = 8 },
  { name = "func_8000BF40", size = 8 },
  { name = "func_8000BF48", size = 12 },
  { name = "func_8000BF54", size = 564 },
  { name = "func_8000C188", size = 20 },
  { name = "func_8000C19C", size = 20 },
  { name = "func_8000C1B0", size = 16 },
  { name = "func_8000C1C0", size = 4 },
  { name = "func_8000C1C4", size = 12 },
  { name = "func_8000C1D0", size = 16 },
  { name = "func_8000C1E0", size = 628 },
  { name = "func_8000C454", size = 16 },
  { name = "func_8000C464", size = 16 },
  { name = "func_8000C474", size = 16 },
  { name = "func_8000C484", size = 580 },
  { name = "func_8000C6C8", size = 16 },
  { name = "func_8000C6D8", size = 16 },
  { name = "func_8000C6E8", size = 16 },
  { name = "func_8000C6F8", size = 464 },
  { name = "func_8000C8C8", size = 216 },
  { name = "func_8000C9A0", size = 24 },
  { name = "func_800273D4", size = 16 },
  { name = "func_800400E0", size = 32 },
  { name = "func_8005C63C", size = 112 },
]

exact_size_funcs = [

]

[patches]
stubs = [
  "func_8000B52C",
  "func_8000B574",
  "func_8000B7D8",
  "func_8000BA3C",
  "func_8000BA94",
]
