[input]
entrypoint                = 0x80000400
elf_path                  = "../spiderman/build/spiderman.elf"
rom_file_path             = "../spiderman/baserom.z64"
output_func_path          = "../spidermanpc/RecompiledFuncs"
relocatable_sections_path = "spiderman_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80000400", size = 112 },
  { name = "func_800004CC", size = 4 },
  { name = "func_80000870", size = 580 },
  { name = "func_80000AB4", size = 104 },
  { name = "func_80000B1C", size = 160 },
  { name = "func_80000BBC", size = 40 },
  { name = "func_80000BE4", size = 40 },
  { name = "func_80000C0C", size = 32 },
  { name = "func_80000C2C", size = 24 },
  { name = "func_80000C44", size = 12 },
  { name = "func_80000C50", size = 168 },
  { name = "func_80000CFC", size = 84 },
  { name = "func_80000D4C", size = 1524 },
  { name = "func_80001340", size = 200 },
  { name = "func_80001408", size = 436 },
  { name = "func_800015BC", size = 216 },
  { name = "func_80001694", size = 52 },
  { name = "func_800016C8", size = 60 },
  { name = "func_80001704", size = 36 },
  { name = "func_80001728", size = 384 },
  { name = "func_800018A8", size = 40 },
  { name = "func_800018D0", size = 368 },
  { name = "func_80001A40", size = 256 },
  { name = "func_80001B40", size = 136 },
  { name = "func_80001BC8", size = 48 },
  { name = "func_80001BF8", size = 184 },
  { name = "func_80001CB0", size = 448 },
  { name = "osInvalDCache", size = 176 },
  { name = "osInvalICache", size = 224 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "osInitialize", size = 656 },
  { name = "func_800022F0", size = 16 },
  { name = "func_80002834", size = 232 },
  { name = "func_8000291C", size = 256 },
  { name = "func_80002A1C", size = 72 },
  { name = "func_80002A64", size = 396 },
  { name = "func_80002C00", size = 16 },
  { name = "osSetIntMask", size = 160 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_80002CC0", size = 16 },
  { name = "func_80002CD0", size = 96 },
  { name = "osWritebackDCache", size = 128 },
  { name = "osDestroyThread", size = 256 },
  { name = "__osDisableInt", size = 32 },
  { name = "__osRestoreInt", size = 32 },
  { name = "osSetEventMesg", size = 112 },
  { name = "func_80002F60", size = 64 },
  { name = "osAiSetFrequency", size = 352 },
  { name = "osViBlack", size = 112 },
  { name = "func_80003170", size = 320 },
  { name = "func_800032B0", size = 864 },
  { name = "osVirtualToPhysical", size = 128 },
  { name = "func_80003690", size = 192 },
  { name = "func_80003750", size = 80 },
  { name = "func_800037A0", size = 48 },
  { name = "func_800037D0", size = 80 },
  { name = "func_80003820", size = 1796 },
  { name = "func_80003F24", size = 232 },
  { name = "func_8000400C", size = 244 },
  { name = "osEPiRawStartDma", size = 560 },
  { name = "osCreatePiManager", size = 400 },
  { name = "osCreateThread", size = 336 },
  { name = "osGetThreadId", size = 32 },
  { name = "osSetThreadPri", size = 224 },
  { name = "osStartThread", size = 336 },
  { name = "func_80004DCC", size = 500 },
  { name = "osRecvMesg", size = 320 },
  { name = "func_80005100", size = 96 },
  { name = "osSendMesg", size = 336 },
  { name = "func_800052B0", size = 80 },
  { name = "func_80005300", size = 80 },
  { name = "func_80005350", size = 80 },
  { name = "func_800053A0", size = 80 },
  { name = "func_800053F0", size = 192 },
  { name = "_bzero", size = 204 },
  { name = "__ull_rem", size = 60 },
  { name = "__ull_div", size = 164 },
  { name = "__ll_div", size = 92 },
  { name = "__ll_mul", size = 344 },
  { name = "func_80005810", size = 44 },
  { name = "func_8000583C", size = 40 },
  { name = "func_80005864", size = 76 },
  { name = "func_80005930", size = 1648 },
  { name = "func_80005FA0", size = 1616 },
  { name = "func_800065F0", size = 672 },
  { name = "func_80006890", size = 256 },
  { name = "func_80006990", size = 144 },
  { name = "func_80006A20", size = 1392 },
  { name = "func_80006F90", size = 1360 },
  { name = "func_800074E0", size = 16 },
  { name = "osGetCount", size = 16 },
  { name = "osContStartQuery", size = 132 },
  { name = "osContGetQuery", size = 44 },
  { name = "func_800075B0", size = 176 },
  { name = "func_80007660", size = 80 },
  { name = "func_800076B0", size = 68 },
  { name = "func_800076F4", size = 44 },
  { name = "osContInit", size = 504 },
  { name = "func_80007918", size = 208 },
  { name = "func_800079E8", size = 248 },
  { name = "osGetTime", size = 144 },
  { name = "osSetTimer", size = 224 },
  { name = "func_80007C50", size = 140 },
  { name = "func_80007CDC", size = 376 },
  { name = "func_80007E54", size = 116 },
  { name = "func_80007EC8", size = 392 },
  { name = "func_80008050", size = 16 },
  { name = "osPfsIsPlug", size = 416 },
  { name = "func_80008200", size = 252 },
  { name = "func_800082FC", size = 212 },
  { name = "osPfsInitPak", size = 624 },
  { name = "func_80008640", size = 540 },
  { name = "func_8000885C", size = 372 },
  { name = "func_800089D0", size = 176 },
  { name = "func_80008A80", size = 208 },
  { name = "func_80008B50", size = 92 },
  { name = "func_80008BAC", size = 104 },
  { name = "func_80008C14", size = 1048 },
  { name = "func_8000902C", size = 408 },
  { name = "func_800091C4", size = 604 },
  { name = "func_80009420", size = 252 },
  { name = "func_8000951C", size = 800 },
  { name = "func_8000983C", size = 116 },
  { name = "func_800098B0", size = 516 },
  { name = "func_80009AB4", size = 380 },
  { name = "func_80009C30", size = 1732 },
  { name = "func_8000A2F4", size = 436 },
  { name = "func_8000A4A8", size = 488 },
  { name = "func_8000A690", size = 272 },
  { name = "func_8000A7A0", size = 360 },
  { name = "func_8000A908", size = 364 },
  { name = "func_8000AA74", size = 380 },
  { name = "osMotorInit", size = 464 },
  { name = "func_8000ADC0", size = 32 },
  { name = "osStopThread", size = 192 },
  { name = "osViSetYScale", size = 96 },
  { name = "__osSpSetPc", size = 64 },
  { name = "_VirtualToPhysicalTask", size = 284 },
  { name = "osSpTaskLoad", size = 400 },
  { name = "osSpTaskStartGo", size = 68 },
  { name = "func_8000B230", size = 48 },
  { name = "func_8000B260", size = 16 },
  { name = "func_8000B270", size = 144 },
  { name = "osSpTaskYield", size = 32 },
  { name = "osSpTaskYielded", size = 128 },
  { name = "func_8000B3A0", size = 16 },
  { name = "osViGetNextFramebuffer", size = 64 },
  { name = "osCreateViManager", size = 392 },
  { name = "func_8000B578", size = 88 },
  { name = "func_8000B5D0", size = 384 },
  { name = "func_8000B750", size = 16 },
  { name = "osViSetEvent", size = 112 },
  { name = "osViSetMode", size = 112 },
  { name = "osViSetXScale", size = 304 },
  { name = "osViSwapBuffer", size = 80 },
  { name = "_bcopy", size = 784 },
  { name = "osViSetSpecialFeatures", size = 448 },
  { name = "osContStartReadData", size = 196 },
  { name = "osContGetReadData", size = 168 },
  { name = "func_8000BFFC", size = 244 },
  { name = "osPfsAllocateFile", size = 1156 },
  { name = "func_8000C574", size = 612 },
  { name = "func_8000C7D8", size = 200 },
  { name = "osPfsDeleteFile", size = 736 },
  { name = "func_8000CB80", size = 568 },
  { name = "func_8000CDB8", size = 248 },
  { name = "func_8000CEB0", size = 1280 },
  { name = "osPfsFileState", size = 752 },
  { name = "osPfsFindFile", size = 448 },
  { name = "osPfsFreeBlocks", size = 1296 },
  { name = "osJamMesg", size = 336 },
  { name = "func_8000DEC0", size = 48 },
  { name = "func_8000DEF0", size = 240 },
  { name = "func_8000DFE0", size = 56 },
  { name = "func_8000E018", size = 96 },
  { name = "func_8000E078", size = 744 },
  { name = "func_8000E360", size = 768 },
  { name = "func_8000E660", size = 68 },
  { name = "func_8000E6A4", size = 84 },
  { name = "func_8000E6F8", size = 84 },
  { name = "func_8000E74C", size = 136 },
  { name = "func_8000E7D4", size = 168 },
  { name = "func_8000E87C", size = 164 },
  { name = "func_8000E920", size = 160 },
  { name = "func_8000E9C0", size = 1088 },
  { name = "func_8000EE00", size = 468 },
  { name = "func_8000F380", size = 300 },
  { name = "func_8000F4AC", size = 1076 },
  { name = "func_8000F8D8", size = 120 },
  { name = "func_8000F950", size = 48 },
  { name = "func_8000F980", size = 224 },
  { name = "func_8000FA60", size = 24 },
  { name = "func_8000FA70", size = 4 },
  { name = "func_8000FA74", size = 20 },
  { name = "func_8000FA88", size = 236 },
  { name = "func_8000FB74", size = 224 },
  { name = "func_8000FC54", size = 464 },
  { name = "func_8000FE24", size = 664 },
  { name = "func_800100BC", size = 176 },
  { name = "func_8001016C", size = 996 },
  { name = "func_8001054C", size = 372 },
  { name = "func_800106C0", size = 32 },
  { name = "func_800106E0", size = 48 },
  { name = "func_80010830", size = 236 },
  { name = "func_8001091C", size = 484 },
  { name = "func_80010AF8", size = 56 },
  { name = "func_80010B30", size = 168 },
  { name = "func_80010BD8", size = 184 },
  { name = "func_80010C90", size = 392 },
  { name = "func_80010E18", size = 396 },
  { name = "func_80010FA4", size = 548 },
  { name = "func_800111C8", size = 112 },
  { name = "func_80011230", size = 500 },
  { name = "func_80011424", size = 24 },
  { name = "func_8001143C", size = 692 },
  { name = "func_800116E4", size = 156 },
  { name = "func_80011780", size = 52 },
  { name = "func_80011840", size = 96 },
  { name = "func_800118A0", size = 128 },
  { name = "func_80011920", size = 16 },
  { name = "func_80011930", size = 160 },
  { name = "func_800119D0", size = 28 },
  { name = "func_800119EC", size = 36 },
  { name = "osAiGetLength", size = 16 },
  { name = "osAiSetNextBuffer", size = 176 },
  { name = "func_80011AD0", size = 48 },
  { name = "func_80011B00", size = 208 },
  { name = "func_80011BD0", size = 16 },
  { name = "func_80011BE0", size = 64 },
  { name = "func_80027C3C", size = 32 },
  { name = "func_80028854", size = 32 },
  { name = "func_80028A60", size = 16 },
  { name = "func_8003997C", size = 96 },
  { name = "func_8004077C", size = 16 },
  { name = "func_80049B40", size = 256 },
  { name = "func_80053F60", size = 16 },
  { name = "func_8005C2F4", size = 32 },
  { name = "func_800618A0", size = 16 },
  { name = "func_80063B70", size = 16 },
  { name = "func_8007F900", size = 16 },
  { name = "func_8008A1AC", size = 16 },
  { name = "func_8008E4BC", size = 16 },
  { name = "func_800920B0", size = 16 },
  { name = "func_8009E838", size = 32 },
  { name = "func_800B01C0", size = 16 },
  { name = "func_800B182C", size = 16 },
  { name = "func_800B843C", size = 16 },
  { name = "func_800C09D0", size = 160 },
  { name = "func_800C4420", size = 48 },
  { name = "func_800CA674", size = 16 },
  { name = "func_800CB6E0", size = 64 },
  { name = "func_800CE1F8", size = 16 },
  { name = "func_800D018C", size = 32 },
  { name = "func_800F4630", size = 16 },
]

exact_size_funcs = [

]

[patches]
stubs = [

]
