[input]
entrypoint                = 0x80025C00
elf_path                  = "../majorleaguebasebal/build/majorleaguebasebal.elf"
rom_file_path             = "../majorleaguebasebal/baserom.z64"
output_func_path          = "../majorleaguebasebalpc/RecompiledFuncs"
relocatable_sections_path = "majorleaguebasebal_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80025C00", size = 80 },
  { name = "func_80025E90", size = 160 },
  { name = "func_80025F30", size = 16 },
  { name = "osGetCount", size = 12 },
  { name = "func_80025F4C", size = 12 },
  { name = "func_80025F58", size = 8 },
  { name = "func_80025F60", size = 160 },
  { name = "osInvalDCache", size = 176 },
  { name = "osSetIntMask", size = 160 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "osInitialize", size = 656 },
  { name = "func_80026410", size = 80 },
  { name = "func_80026460", size = 80 },
  { name = "func_800264B0", size = 16 },
  { name = "func_800264C0", size = 96 },
  { name = "func_80026520", size = 224 },
  { name = "_bzero", size = 160 },
  { name = "func_800266A0", size = 44 },
  { name = "__ull_rem", size = 60 },
  { name = "__ull_div", size = 60 },
  { name = "func_80026744", size = 44 },
  { name = "func_80026770", size = 60 },
  { name = "__ll_div", size = 92 },
  { name = "__ll_mul", size = 48 },
  { name = "func_80026838", size = 96 },
  { name = "func_80026898", size = 156 },
  { name = "func_80026934", size = 44 },
  { name = "func_80026960", size = 16 },
  { name = "func_80026EA4", size = 232 },
  { name = "func_80026F8C", size = 256 },
  { name = "func_8002708C", size = 72 },
  { name = "func_800270D4", size = 396 },
  { name = "func_80027270", size = 16 },
  { name = "osInvalICache", size = 224 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_80027370", size = 16 },
  { name = "osWritebackDCache", size = 128 },
  { name = "func_80027400", size = 96 },
  { name = "osDestroyThread", size = 256 },
  { name = "osSetEventMesg", size = 112 },
  { name = "func_800275D0", size = 64 },
  { name = "osVirtualToPhysical", size = 128 },
  { name = "func_80027690", size = 48 },
  { name = "func_800276C0", size = 1700 },
  { name = "func_80027D64", size = 232 },
  { name = "func_80027E4C", size = 244 },
  { name = "__osDisableInt", size = 32 },
  { name = "__osRestoreInt", size = 32 },
  { name = "func_80027F80", size = 192 },
  { name = "osEPiRawStartDma", size = 560 },
  { name = "func_80028270", size = 256 },
  { name = "osCreatePiManager", size = 400 },
  { name = "func_80028500", size = 240 },
  { name = "func_800285F0", size = 1168 },
  { name = "func_80028A80", size = 80 },
  { name = "func_80028AD0", size = 68 },
  { name = "func_80028B14", size = 44 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "osCreateThread", size = 336 },
  { name = "osGetThreadPri", size = 32 },
  { name = "osRecvMesg", size = 320 },
  { name = "func_80028E20", size = 96 },
  { name = "osSendMesg", size = 336 },
  { name = "func_80028FD0", size = 80 },
  { name = "osSetThreadPri", size = 224 },
  { name = "osStartThread", size = 336 },
  { name = "func_80029250", size = 80 },
  { name = "func_800292A0", size = 80 },
  { name = "func_800292F0", size = 80 },
  { name = "func_80029CB8", size = 888 },
  { name = "func_8002A030", size = 136 },
  { name = "func_800333F8", size = 16 },
  { name = "func_8003BE9C", size = 8 },
  { name = "func_800528B8", size = 48 },
  { name = "func_80069048", size = 48 },
  { name = "func_80085350", size = 16 },
  { name = "func_80087A88", size = 32 },
  { name = "func_80090740", size = 32 },
  { name = "func_80094170", size = 48 },
  { name = "func_800D258C", size = 32 },
  { name = "func_800EB8A8", size = 16 },
  { name = "func_801197C8", size = 16 },
  { name = "func_80119B54", size = 16 },
]

exact_size_funcs = [

]

[patches]
stubs = [
  "func_800333F8",
]
