[input]
entrypoint                = 0x80000400
elf_path                  = "../thps/build/thps.elf"
rom_file_path             = "../thps/baserom.z64"
output_func_path          = "../thpspc/RecompiledFuncs"
relocatable_sections_path = "thps_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80000400", size = 368 },
  { name = "func_80000870", size = 560 },
  { name = "func_80000AA0", size = 104 },
  { name = "func_80000B08", size = 160 },
  { name = "func_80000BA8", size = 40 },
  { name = "func_80000BD0", size = 40 },
  { name = "func_80000BF8", size = 32 },
  { name = "func_80000C18", size = 24 },
  { name = "func_80000C30", size = 12 },
  { name = "func_80000C3C", size = 4 },
  { name = "func_80000C40", size = 168 },
  { name = "func_80000CEC", size = 1412 },
  { name = "func_8000126C", size = 196 },
  { name = "func_80001330", size = 200 },
  { name = "func_800013F8", size = 436 },
  { name = "func_800015AC", size = 216 },
  { name = "func_80001684", size = 52 },
  { name = "func_800016B8", size = 60 },
  { name = "func_800016F4", size = 36 },
  { name = "func_80001718", size = 384 },
  { name = "func_80001898", size = 408 },
  { name = "func_80001A30", size = 256 },
  { name = "func_80001B30", size = 912 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "osInitialize", size = 2012 },
  { name = "func_800026C4", size = 232 },
  { name = "func_800027AC", size = 256 },
  { name = "func_800028AC", size = 72 },
  { name = "func_800028F4", size = 396 },
  { name = "func_80002A90", size = 16 },
  { name = "osInvalICache", size = 128 },
  { name = "osSetIntMask", size = 160 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_80002BD0", size = 16 },
  { name = "func_80002BE0", size = 96 },
  { name = "osWritebackDCache", size = 128 },
  { name = "osDestroyThread", size = 256 },
  { name = "__osDisableInt", size = 32 },
  { name = "__osRestoreInt", size = 32 },
  { name = "osSetEventMesg", size = 112 },
  { name = "func_80002E70", size = 64 },
  { name = "osAiSetFrequency", size = 352 },
  { name = "osViBlack", size = 112 },
  { name = "func_80003080", size = 320 },
  { name = "func_800031C0", size = 864 },
  { name = "osVirtualToPhysical", size = 128 },
  { name = "func_800035A0", size = 192 },
  { name = "func_80003660", size = 80 },
  { name = "func_800036B0", size = 48 },
  { name = "func_800036E0", size = 80 },
  { name = "func_80003730", size = 96 },
  { name = "func_80003790", size = 1700 },
  { name = "func_80003E34", size = 232 },
  { name = "func_80003F1C", size = 244 },
  { name = "osEPiRawStartDma", size = 560 },
  { name = "osCreatePiManager", size = 400 },
  { name = "osCreateThread", size = 336 },
  { name = "osGetThreadId", size = 32 },
  { name = "osSetThreadPri", size = 224 },
  { name = "osStartThread", size = 336 },
  { name = "func_80004770", size = 144 },
  { name = "func_800047F4", size = 92 },
  { name = "func_80004850", size = 240 },
  { name = "func_80004940", size = 256 },
  { name = "func_80004A40", size = 1172 },
  { name = "osRecvMesg", size = 320 },
  { name = "func_80005010", size = 96 },
  { name = "osSendMesg", size = 336 },
  { name = "func_800051C0", size = 80 },
  { name = "func_80005210", size = 80 },
  { name = "func_80005260", size = 80 },
  { name = "func_800052B0", size = 80 },
  { name = "func_80005300", size = 80 },
  { name = "func_80005350", size = 68 },
  { name = "func_80005394", size = 44 },
  { name = "_bzero", size = 160 },
  { name = "func_80005460", size = 44 },
  { name = "__ull_rem", size = 60 },
  { name = "__ull_div", size = 60 },
  { name = "func_80005504", size = 44 },
  { name = "func_80005530", size = 60 },
  { name = "__ll_div", size = 92 },
  { name = "__ll_mul", size = 48 },
  { name = "func_800055F8", size = 96 },
  { name = "func_80005658", size = 156 },
  { name = "func_800056F4", size = 44 },
  { name = "func_80005720", size = 44 },
  { name = "func_8000574C", size = 40 },
  { name = "func_80005774", size = 76 },
  { name = "func_800057C0", size = 36 },
  { name = "func_800057E4", size = 92 },
  { name = "func_80005840", size = 1648 },
  { name = "func_80005EB0", size = 1616 },
  { name = "func_80006500", size = 672 },
  { name = "func_800067A0", size = 256 },
  { name = "func_800068A0", size = 144 },
  { name = "func_80006930", size = 1392 },
  { name = "func_80006EA0", size = 1360 },
  { name = "func_800073F0", size = 16 },
  { name = "osGetCount", size = 16 },
  { name = "osContStartQuery", size = 132 },
  { name = "osContGetQuery", size = 44 },
  { name = "func_800074C0", size = 176 },
  { name = "osInvalDCache", size = 176 },
  { name = "func_80007620", size = 80 },
  { name = "func_80007670", size = 68 },
  { name = "func_800076B4", size = 44 },
  { name = "osContInit", size = 504 },
  { name = "func_800078D8", size = 208 },
  { name = "func_800079A8", size = 248 },
  { name = "osGetTime", size = 144 },
  { name = "osSetTimer", size = 224 },
  { name = "func_80007C10", size = 140 },
  { name = "func_80007C9C", size = 376 },
  { name = "func_80007E14", size = 116 },
  { name = "func_80007E88", size = 392 },
  { name = "func_80008010", size = 16 },
  { name = "osPfsIsPlug", size = 416 },
  { name = "func_800081C0", size = 252 },
  { name = "func_800082BC", size = 212 },
  { name = "osPfsInitPak", size = 624 },
  { name = "func_80008600", size = 540 },
  { name = "func_8000881C", size = 372 },
  { name = "func_80008990", size = 176 },
  { name = "func_80008A40", size = 208 },
  { name = "func_80008B10", size = 92 },
  { name = "func_80008B6C", size = 104 },
  { name = "func_80008BD4", size = 1048 },
  { name = "func_80008FEC", size = 408 },
  { name = "func_80009184", size = 604 },
  { name = "func_800093E0", size = 252 },
  { name = "func_800094DC", size = 800 },
  { name = "func_800097FC", size = 116 },
  { name = "func_80009870", size = 516 },
  { name = "func_80009A74", size = 380 },
  { name = "func_80009BF0", size = 1732 },
  { name = "func_8000A2B4", size = 436 },
  { name = "func_8000A468", size = 488 },
  { name = "func_8000A650", size = 272 },
  { name = "func_8000A760", size = 360 },
  { name = "func_8000A8C8", size = 364 },
  { name = "func_8000AA34", size = 380 },
  { name = "osMotorInit", size = 464 },
  { name = "func_8000AD80", size = 32 },
  { name = "osStopThread", size = 192 },
  { name = "osViSetYScale", size = 96 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "__osSpSetPc", size = 64 },
  { name = "_VirtualToPhysicalTask", size = 284 },
  { name = "osSpTaskLoad", size = 400 },
  { name = "osSpTaskStartGo", size = 68 },
  { name = "func_8000B220", size = 48 },
  { name = "func_8000B250", size = 16 },
  { name = "func_8000B260", size = 144 },
  { name = "osSpTaskYield", size = 32 },
  { name = "osSpTaskYielded", size = 128 },
  { name = "func_8000B390", size = 16 },
  { name = "osViGetNextFramebuffer", size = 64 },
  { name = "osCreateViManager", size = 392 },
  { name = "func_8000B568", size = 472 },
  { name = "func_8000B740", size = 16 },
  { name = "osViSetEvent", size = 112 },
  { name = "osViSetMode", size = 112 },
  { name = "osViSwapBuffer", size = 80 },
  { name = "_bcopy", size = 784 },
  { name = "osViSetSpecialFeatures", size = 448 },
  { name = "osContStartReadData", size = 196 },
  { name = "osContGetReadData", size = 168 },
  { name = "func_8000BEBC", size = 244 },
  { name = "func_8000BFB0", size = 16 },
  { name = "osJamMesg", size = 336 },
  { name = "func_8000C110", size = 48 },
  { name = "func_8000C140", size = 36 },
  { name = "func_8000C164", size = 56 },
  { name = "func_8000C19C", size = 60 },
  { name = "func_8000C1D8", size = 88 },
  { name = "func_8000C230", size = 56 },
  { name = "func_8000C268", size = 96 },
  { name = "func_8000C2C8", size = 24 },
  { name = "func_8000C2E0", size = 48 },
  { name = "func_8000C310", size = 8 },
  { name = "func_8000C318", size = 664 },
  { name = "func_8000C5B0", size = 768 },
  { name = "func_8000C8B0", size = 68 },
  { name = "func_8000C8F4", size = 84 },
  { name = "func_8000C948", size = 84 },
  { name = "func_8000C99C", size = 136 },
  { name = "func_8000CA24", size = 168 },
  { name = "func_8000CACC", size = 164 },
  { name = "func_8000CB70", size = 160 },
  { name = "func_8000CC10", size = 1088 },
  { name = "func_8000D050", size = 468 },
  { name = "func_8000D224", size = 924 },
  { name = "func_8000D5D0", size = 300 },
  { name = "func_8000D6FC", size = 200 },
  { name = "func_8000DBA0", size = 48 },
  { name = "func_8000DBD0", size = 224 },
  { name = "func_8000DCB0", size = 40 },
  { name = "func_8000DCD8", size = 236 },
  { name = "func_8000DDC4", size = 224 },
  { name = "func_8000DEA4", size = 464 },
  { name = "func_8000E074", size = 664 },
  { name = "func_8000E30C", size = 176 },
  { name = "func_8000E3BC", size = 1372 },
  { name = "func_8000E910", size = 32 },
  { name = "func_8000E930", size = 48 },
  { name = "func_8000E960", size = 288 },
  { name = "func_8000EA80", size = 236 },
  { name = "func_8000EB6C", size = 212 },
  { name = "func_8000EC34", size = 332 },
  { name = "func_8000ED80", size = 168 },
  { name = "func_8000EE28", size = 184 },
  { name = "func_8000EEE0", size = 392 },
  { name = "func_8000F068", size = 396 },
  { name = "func_8000F1F4", size = 548 },
  { name = "func_8000F418", size = 604 },
  { name = "func_8000F674", size = 24 },
  { name = "func_8000F68C", size = 104 },
  { name = "func_8000F6F0", size = 736 },
  { name = "func_8000F9D0", size = 52 },
  { name = "func_8000FA04", size = 140 },
  { name = "func_8000FA90", size = 96 },
  { name = "func_8000FAF0", size = 128 },
  { name = "func_8000FB70", size = 16 },
  { name = "func_8000FB80", size = 160 },
  { name = "func_8000FC20", size = 28 },
  { name = "func_8000FC3C", size = 36 },
  { name = "osAiGetLength", size = 16 },
  { name = "osAiSetNextBuffer", size = 176 },
  { name = "func_8000FD20", size = 48 },
  { name = "func_8000FD50", size = 208 },
  { name = "func_8000FE20", size = 16 },
  { name = "func_8000FE30", size = 64 },
  { name = "osPfsAllocateFile", size = 1156 },
  { name = "func_800102F4", size = 612 },
  { name = "func_80010558", size = 200 },
  { name = "osPfsDeleteFile", size = 736 },
  { name = "func_80010900", size = 568 },
  { name = "func_80010B38", size = 248 },
  { name = "func_80010C30", size = 252 },
  { name = "func_80010D2C", size = 1028 },
  { name = "osPfsFileState", size = 752 },
  { name = "osPfsFindFile", size = 448 },
  { name = "osPfsFreeBlocks", size = 336 },
  { name = "func_80011730", size = 336 },
  { name = "func_80011880", size = 608 },
  { name = "func_8002BFCC", size = 16 },
  { name = "func_80049CE8", size = 64 },
  { name = "func_8005D2B4", size = 16 },
  { name = "func_8005FC5C", size = 16 },
  { name = "func_80093478", size = 128 },
  { name = "func_800AAD64", size = 16 },
  { name = "func_800DD1DC", size = 16 },
  { name = "func_800DF748", size = 144 },
  { name = "func_800FE108", size = 16 },
]

exact_size_funcs = [

]

[patches]
stubs = [
  "func_800AAD64",
]
