[input]
entrypoint                = 0x80000480
elf_path                  = "../residentevil2/build/residentevil2.elf"
rom_file_path             = "../residentevil2/baserom.z64"
output_func_path          = "../residentevil2pc/RecompiledFuncs"
relocatable_sections_path = "residentevil2_overlays.txt"

uses_mips3_float_mode = true

function_sizes = [
  { name = "func_80000480", size = 112 },
  { name = "func_800004F0", size = 16 },
  { name = "func_80000500", size = 12 },
  { name = "func_8000050C", size = 12 },
  { name = "func_80000518", size = 8 },
  { name = "func_80000520", size = 120 },
  { name = "func_80000598", size = 296 },
  { name = "func_800006C0", size = 16 },
  { name = "func_80000CE4", size = 240 },
  { name = "func_80000DD4", size = 308 },
  { name = "func_80000F08", size = 72 },
  { name = "func_80000F50", size = 540 },
  { name = "func_80001180", size = 32 },
  { name = "func_800011A0", size = 528 },
  { name = "func_800013B0", size = 36 },
  { name = "func_800013D4", size = 116 },
  { name = "func_80001448", size = 100 },
  { name = "func_800014AC", size = 100 },
  { name = "func_80001510", size = 208 },
  { name = "func_800015E0", size = 184 },
  { name = "func_80001698", size = 3108 },
  { name = "func_800022BC", size = 88 },
  { name = "func_80002314", size = 76 },
  { name = "func_80002360", size = 120 },
  { name = "func_800023D8", size = 1584 },
  { name = "func_80002A08", size = 388 },
  { name = "func_80002B8C", size = 52 },
  { name = "func_80002BC0", size = 960 },
  { name = "func_80002F80", size = 104 },
  { name = "func_80002FE8", size = 116 },
  { name = "func_8000305C", size = 320 },
  { name = "func_8000319C", size = 40 },
  { name = "func_800031C4", size = 1324 },
  { name = "func_800036F0", size = 204 },
  { name = "func_800037BC", size = 308 },
  { name = "func_800038F0", size = 1512 },
  { name = "func_80003ED8", size = 144 },
  { name = "func_80003F68", size = 364 },
  { name = "func_800040D4", size = 40 },
  { name = "func_800040FC", size = 504 },
  { name = "func_800042F4", size = 124 },
  { name = "func_80004370", size = 384 },
  { name = "func_800044F0", size = 96 },
  { name = "func_80004550", size = 68 },
  { name = "func_80004594", size = 72 },
  { name = "func_800045DC", size = 336 },
  { name = "func_8000472C", size = 388 },
  { name = "func_800048B0", size = 48 },
  { name = "func_800048E0", size = 8 },
  { name = "func_800048E8", size = 36 },
  { name = "func_8000490C", size = 36 },
  { name = "func_80004930", size = 36 },
  { name = "func_80004954", size = 204 },
  { name = "func_80004A20", size = 48 },
  { name = "func_80004A50", size = 28 },
  { name = "func_80004A6C", size = 240 },
  { name = "func_80004B5C", size = 80 },
  { name = "func_80004BAC", size = 56 },
  { name = "func_80004BE4", size = 48 },
  { name = "func_80004C14", size = 16 },
  { name = "func_80004C24", size = 16 },
  { name = "func_80004C34", size = 56 },
  { name = "func_80004C6C", size = 48 },
  { name = "func_80004C9C", size = 96 },
  { name = "func_80004CFC", size = 456 },
  { name = "func_80004EC4", size = 28 },
  { name = "func_80004EE0", size = 160 },
  { name = "func_80004F80", size = 32 },
  { name = "func_80004FA0", size = 12 },
  { name = "func_80004FAC", size = 8 },
  { name = "func_80004FB4", size = 192 },
  { name = "func_80005074", size = 192 },
  { name = "func_80005134", size = 132 },
  { name = "func_800051B8", size = 100 },
  { name = "func_8000521C", size = 472 },
  { name = "func_800053F4", size = 68 },
  { name = "func_80005438", size = 2636 },
  { name = "func_80005E84", size = 100 },
  { name = "func_80005EE8", size = 100 },
  { name = "func_80005F4C", size = 436 },
  { name = "func_80006100", size = 1360 },
  { name = "func_80006650", size = 160 },
  { name = "osContStartReadData", size = 136 },
  { name = "osContGetReadData", size = 156 },
  { name = "func_80006814", size = 188 },
  { name = "osContInit", size = 412 },
  { name = "func_80006A6C", size = 180 },
  { name = "func_80006B20", size = 192 },
  { name = "func_80006BE0", size = 336 },
  { name = "osCreateMesgQueue", size = 48 },
  { name = "osCreateThread", size = 208 },
  { name = "osDestroyThread", size = 208 },
  { name = "func_80006F00", size = 80 },
  { name = "func_80006F50", size = 16 },
  { name = "osEPiStartDma", size = 160 },
  { name = "func_80007000", size = 16 },
  { name = "osGetThreadPri", size = 32 },
  { name = "osGetTime", size = 144 },
  { name = "osInitialize", size = 528 },
  { name = "func_800072D0", size = 16 },
  { name = "__osDisableInt", size = 32 },
  { name = "__osRestoreInt", size = 32 },
  { name = "func_80007320", size = 176 },
  { name = "func_800073D0", size = 128 },
  { name = "osJamMesg", size = 320 },
  { name = "func_80007590", size = 1292 },
  { name = "func_80007A9C", size = 208 },
  { name = "func_80007B6C", size = 180 },
  { name = "osEPiRawStartDma", size = 464 },
  { name = "func_80007DF0", size = 256 },
  { name = "func_80007EF0", size = 96 },
  { name = "osMotorStop", size = 448 },
  { name = "osMotorStart", size = 448 },
  { name = "osMotorInit", size = 1232 },
  { name = "func_800087A0", size = 564 },
  { name = "func_800089D4", size = 412 },
  { name = "func_80008B70", size = 544 },
  { name = "func_80008D90", size = 416 },
  { name = "func_80008F30", size = 72 },
  { name = "func_80008F78", size = 104 },
  { name = "func_80008FE0", size = 152 },
  { name = "func_80009078", size = 168 },
  { name = "func_80009120", size = 80 },
  { name = "func_80009170", size = 336 },
  { name = "func_800092C0", size = 432 },
  { name = "func_80009470", size = 464 },
  { name = "osPfsAllocateFile", size = 912 },
  { name = "func_800099D0", size = 460 },
  { name = "func_80009B9C", size = 148 },
  { name = "func_80009C30", size = 56 },
  { name = "func_80009C68", size = 68 },
  { name = "func_80009CAC", size = 736 },
  { name = "func_80009F8C", size = 356 },
  { name = "func_8000A0F0", size = 480 },
  { name = "func_8000A2D0", size = 196 },
  { name = "func_8000A394", size = 728 },
  { name = "func_8000A66C", size = 84 },
  { name = "osPfsFileState", size = 576 },
  { name = "osPfsFreeBlocks", size = 272 },
  { name = "func_8000AA10", size = 224 },
  { name = "func_8000AAF0", size = 144 },
  { name = "func_8000AB80", size = 128 },
  { name = "osPfsInitPak", size = 464 },
  { name = "func_8000ADD0", size = 1100 },
  { name = "func_8000B21C", size = 344 },
  { name = "func_8000B374", size = 364 },
  { name = "osPfsIsPlug", size = 380 },
  { name = "func_8000B65C", size = 164 },
  { name = "func_8000B700", size = 192 },
  { name = "osPfsReadWriteFile", size = 1072 },
  { name = "osPfsFindFile", size = 400 },
  { name = "osPiStartDma", size = 176 },
  { name = "func_8000BE30", size = 32 },
  { name = "func_8000BE50", size = 16 },
  { name = "osCreatePiManager", size = 400 },
  { name = "osCartRomInit", size = 224 },
  { name = "func_8000C0D0", size = 960 },
  { name = "func_8000C490", size = 400 },
  { name = "func_8000C620", size = 16 },
  { name = "func_8000C630", size = 336 },
  { name = "func_8000C780", size = 84 },
  { name = "func_8000C7D4", size = 108 },
  { name = "func_8000C840", size = 48 },
  { name = "func_8000C870", size = 208 },
  { name = "func_8000C940", size = 160 },
  { name = "osRecvMesg", size = 304 },
  { name = "func_8000CB10", size = 80 },
  { name = "osSendMesg", size = 304 },
  { name = "osSetEventMesg", size = 96 },
  { name = "__osSetFpcCsr", size = 16 },
  { name = "func_8000CD00", size = 64 },
  { name = "osSetIntMask", size = 160 },
  { name = "func_8000CDE0", size = 16 },
  { name = "osSetThreadPri", size = 208 },
  { name = "osSetTimer", size = 160 },
  { name = "func_8000CF60", size = 84 },
  { name = "func_8000CFB4", size = 108 },
  { name = "func_8000D020", size = 48 },
  { name = "func_8000D050", size = 416 },
  { name = "func_8000D1F0", size = 192 },
  { name = "func_8000D2B0", size = 32 },
  { name = "func_8000D2D0", size = 144 },
  { name = "func_8000D360", size = 112 },
  { name = "func_8000D3D0", size = 88 },
  { name = "func_8000D428", size = 56 },
  { name = "osSpTaskLoad", size = 524 },
  { name = "osSpTaskStartGo", size = 52 },
  { name = "func_8000D6A0", size = 800 },
  { name = "func_8000D9C0", size = 32 },
  { name = "func_8000D9E0", size = 256 },
  { name = "__osSpSetPc", size = 48 },
  { name = "func_8000DB10", size = 16 },
  { name = "osSpTaskYielded", size = 80 },
  { name = "func_8000DB70", size = 16 },
  { name = "func_8000DB80", size = 16 },
  { name = "osStartThread", size = 288 },
  { name = "osStopThread", size = 192 },
  { name = "osStopTimer", size = 192 },
  { name = "func_8000DE30", size = 16 },
  { name = "func_8000DE40", size = 56 },
  { name = "func_8000DE78", size = 36 },
  { name = "func_8000DE9C", size = 52 },
  { name = "func_8000DED0", size = 64 },
  { name = "func_8000DF10", size = 84 },
  { name = "func_8000DF64", size = 316 },
  { name = "func_8000E0A0", size = 96 },
  { name = "func_8000E100", size = 272 },
  { name = "func_8000E210", size = 264 },
  { name = "func_8000E318", size = 56 },
  { name = "osViBlack", size = 96 },
  { name = "func_8000E3B0", size = 272 },
  { name = "osCreateViManager", size = 408 },
  { name = "func_8000E658", size = 408 },
  { name = "func_8000E7F0", size = 16 },
  { name = "osVirtualToPhysical", size = 96 },
  { name = "func_8000E860", size = 192 },
  { name = "osViSetEvent", size = 96 },
  { name = "osViSetMode", size = 80 },
  { name = "osViSetSpecialFeatures", size = 368 },
  { name = "osViSetXScale", size = 208 },
  { name = "osViSetYScale", size = 80 },
  { name = "osViSwapBuffer", size = 80 },
  { name = "func_8000ECB0", size = 752 },
  { name = "func_8000EFA0", size = 128 },
  { name = "osWritebackDCacheAll", size = 48 },
  { name = "func_8000F050", size = 1392 },
  { name = "func_8000F5C0", size = 1216 },
  { name = "func_8000FA80", size = 1088 },
  { name = "func_8000FEC0", size = 152 },
  { name = "func_8000FF58", size = 1448 },
  { name = "func_80010500", size = 132 },
  { name = "func_80010584", size = 316 },
  { name = "func_800106C0", size = 1456 },
  { name = "func_80010C70", size = 592 },
  { name = "func_80010EC0", size = 1232 },
  { name = "func_80011390", size = 80 },
  { name = "osAiSetFrequency", size = 304 },
  { name = "osAiSetNextBuffer", size = 160 },
  { name = "func_800115B0", size = 32 },
  { name = "func_80016310", size = 32 },
  { name = "func_800E1198", size = 32 },
]

exact_size_funcs = [

]

[patches]
stubs = [
  "func_800E1198",
]
